### ISSUE TITLE
Hamburger menu button dude inspired

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1010]
Am I the only one here who gives a shit about the rules ?????

**Comment by ghost** [comment]
Hey be carefull!!


There's a beverage here!!!!


_The man in me will do
nearly any tasks,
and as for a compensation
there's al litlle he will ask_

**Comment by eri-trabiccolo** [comment]
maybe TODO:
implement js like in hueman, though in hueman it doesn't always do what it declares (sequence pf animation) + we rely on the bootstrap4 collapsing, not sure adding a js for this would be worthwhile.
