### ISSUE TITLE
Wrong view on first load.

### ISSUE THREAD

**Issue by PeopleInside** [Nikeo/customizr#1016]
Hi,
if I open a new incognito mode on Firefox and also Chrome I see my website showed not well on the first load.

The error is solved when you scroll down and scroll up again.

Can this be fixed?

![screen 1](https://user-images.githubusercontent.com/5006150/27985939-30c64c7e-63f6-11e7-9ec9-c15ee4912e9a.png)

https://www.peopleinside.it/

Thank you!

**Comment by PeopleInside** [comment]
I hope you can help me to find if this is an issue with your theme.
Thanks.

I know my header image is large but I AM using this template because I want to have that look on my website. Hope you can help to find a fix, thanks!

**Comment by PeopleInside** [comment]
I tested today without plugin and can confirm the issue is in the theme.
I AM looking for help:

- https://webcompat.com/issues/9367

**Comment by PeopleInside** [comment]
Unable to reproduce anymore at the moment

**Comment by PeopleInside** [comment]
Still valid

**Comment by PeopleInside** [comment]
Seems easy to reproduce with Firefox 57 incognito mode by visiting http://www.peopleinside.it
![screen](https://user-images.githubusercontent.com/5006150/32832564-340c2d6a-c9fc-11e7-98ab-8debb3b56aba.png)

**Comment by PeopleInside** [comment]
https://github.com/webcompat/web-bugs/issues/9367

**Comment by ghost** [comment]
> Regarding my previous message to you the issue on Customizr theme is present in all Customizr Wordpress website also
> http://www.marcoborla.it/
> and
> https://blog.peopleinside.it/
> 
> when you load for the first time or on incognito mode the website from Firefox 57 sometimes i am able to reproduce the issue also with Edge.
> 
> hope to find with you a fix.
> Have a great time!

**Comment by PeopleInside** [comment]
Thank you for take care about this.
I AM trying in all this days to solve this issue but was not able to do and to find any other help.

I created a new Wordpress install Today for test the issue without plugin and to made possibile by you to see the issue.

Access to the Wordpress website was sent to your email address.
Web address is https://customizr.peopleinside.it

Hope this will help to understand and fix soon.

![1](https://user-images.githubusercontent.com/5006150/33327098-f207e318-d456-11e7-8c43-eb3e2e6e89ff.png)

**Comment by PeopleInside** [comment]
For Christmas I hope I can get an update that can fix this issue.
More late I hope not over March... this seems to be a theme visual bug that is very evident on my websites.

So for let you have less work I worked for you to create a test blog ( https://customizr.peopleinside.it )
and I sent also credentials on ticket that you confirmed to have received.

I can imagine you have a lot of work and topics here, this is the only mine topic important about I will hope in a fix also will hope the fix will be not complex and long for you.
Just maybe a small correction.

Thank you very much!

**Comment by PeopleInside** [comment]
A suggestion has come from: https://github.com/webcompat/web-bugs/issues/9367#issuecomment-348822829

> The same thing is happening in both Safari, Firefox and Chrome.
> This is not a webcompat issue.
> It would be better to ask on stackoverflow, this kind of questions.
> I would also encourage you to explore flexbox for solving your issues.
> https://css-tricks.com/snippets/css/a-guide-to-flexbox/
> https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes

I asked on stackoverflow but no solution.
https://stackoverflow.com/questions/47485935/wordpress-theme-issue-on-first-load-elements-under-header-can-you-help-me

**Comment by PeopleInside** [comment]
I do not know if can be useful:
https://css-tricks.com/forums/topic/wordpress-theme-issue-on-first-load-elements-under-header-can-you-help-me/#post-263444

I do not understand how to try the fix I will try to ask more.

**Comment by PeopleInside** [comment]
Until this will be not fixed I used the fix (that seems work) on all my websites

https://css-tricks.com/forums/topic/wordpress-theme-issue-on-first-load-elements-under-header-can-you-help-me/#post-263444

The fix works.
I will keep online the demo with the unfixed bug/issue at https://customizr.peopleinside.it until the end of Jenuary.
After this date I will close also this demo and maybe I will consider to send the ZIP file of this test demo if you want.

Seems to be a script issue.
I AM so happy to have a temporary fix for now! I am waiting before this summer ^_^ and this was very big visual and frequent bug for me.

Thanks for this great theme!
I looked into Wordpress Theme but Customizr is the only once I can imgine because alow me to have long logo and so the template I have.

**Comment by PeopleInside** [comment]
Sorry, demo was closed.
I will try to send zip file to the ticket. You will able to download on the next 30 days.

**Comment by ghost** [comment]
OK. thank you.
Installing an entire website is not our preferred way to fix this type of problem.
Can this bug be reproduced somwhere else, like for example on the [demo website](https://demo.presscustomizr.com) when switching to incognito mode ?
Best wishes for 2018 !

**Comment by PeopleInside** [comment]
Hi @Nikeo,
I think I will be not able to reproduce in the demo or you need to change a lot of the theme because seems the issue is present with my customization in all website.

You have to understand your theme is amazing :D is the only one theme that allow me to have a big long header so the look of the website can be as my previous website before i swith to the new HTML 5 responsive theme.

Seems my setting create the bug that I resolved for now with the fix suggested here:
[](https://css-tricks.com/forums/topic/wordpress-theme-issue-on-first-load-elements-under-header-can-you-help-me/#post-263444)

If I can login in a demo I can try to set my settings and show to you the issue. Let me know. I do not if I can access to a demo and customize the theme for reproduce the issue.

I will be very happy on see the issue fixed.

**Comment by PeopleInside** [comment]
Happy new year 2018 :) also to you :)

**Comment by PeopleInside** [comment]
Hi @Nikeo , this issue is closed as question? The issue was not fixed in the theme?
Fortunately [i found help on the web](https://css-tricks.com/forums/topic/wordpress-theme-issue-on-first-load-elements-under-header-can-you-help-me/#post-263444) so thanks to a code added in my website now i solved this issue... but i have to remember in future if i will install your theme on a new website.
