### ISSUE TITLE
Topbar : a prototype for contact block + social display in mobile / desktop

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1053]
Example : https://megagym.oceanwp.org/

**Comment by ghost** [comment]
Another user requesting it here
https://secure.helpscout.net/conversation/486186856/35482/?folderId=607547

**Comment by ghost** [comment]
And another related ( for classic, but still, same concept ) https://secure.helpscout.net/conversation/507485687/36680?folderId=607541

@eri-trabiccolo we need to discuss this during our next chat.

**Comment by eri-trabiccolo** [comment]
Mmm, this is in my column now before hueman fa5 upgrade... is this correct?

**Comment by ghost** [comment]
the order is 

1. phone number
2. opening hours
3. email

**Comment by eri-trabiccolo** [comment]
Topbar Question.
Display it in mobile and/or desktop.
We now have a checkbox to display it in desktops, we can
1) add a new checkbox for mobiles
2) turn the current option in a select saying "Display a topbar in the header", with options
- Do not display
- Only in desktops
- Only in mobiles
- Both in desktops and mobiles

1) is the more simple one and respects our options header sections structure, but the 2) would be more easy for the users.
On our side the 2) would require a backward compatibility routine (which is now something we can rely on without problems).
The new option 2) will be listed under the **Header > General design settings** section

Any preference @Nikeo?

**Comment by ghost** [comment]
yes 2) is better. My only 2 cents would be to add the word _devices_

- Do not display
- Only in desktops devices
- Only in mobiles devices
- Both in desktops and mobiles devices

tnx and good evening !

**Comment by eri-trabiccolo** [comment]
The "contact-info" block will follow the same logic:
- Do not display
- Only in desktops devices
- Only in mobiles devices
- Both in desktops and mobiles devices

In my opinion the **socials in header option** should now follow this logic too (backward compat needed).
I'm doing it this way unless you have anything against it.

**Comment by eri-trabiccolo** [comment]
Customizr: https://github.com/presscustomizr/customizr/pull/1403
Bugfix js:  https://github.com/presscustomizr/customizr-front-js-parts/pull/32

Now we have to find a way to make the Header -> General design settings less crowded.

To discuss:
- maybe center socials and contact info in small devices (smartphones only) and decrease font size

**Comment by ghost** [comment]
Thank you, this is a very good addition.

Change => The contact block feature will be included in the pro-bundle instead of here.
In the future, it will turned into a module in which users will be able to add any contact informations they need, choose the icon, or not display an icon, order the items, style them, etc ...

Here are some specification updates.

## Contact block
- [customizer] A new section will be created under Header : Contact Informations. It will include the prototype's options as they are now. ![contact_block](https://user-images.githubusercontent.com/3038156/35234186-88bfd8f0-ffa0-11e7-8bae-3558843595ed.jpg)

- [customizer] The transport should be postmessaging
- [customizer] For the email option, there should be a 'sanitize_callback' checking that the email address is well formed.
- [front] on mobile, every contact block should be centered

## Topbar and socials
When porting options for topbar and social links, even if the topbar was not displayed before in mobile, the ported option should be `desktop_mobile` and not `desktop` like it is in the prototype. The reason is that I think most of the users, including my self, find it more consistent to see it in all devices when the topbar is checked.

## Dev Process
So your next PR in customizr free should only cover the topnav and social links part, and include the above modifications.
There will be another PR in the pro-bundle for the contact block, including the above modifications.

Let me know if there's something we need to discuss more in details in this specification update.

**Comment by eri-trabiccolo** [comment]
> [customizer] The transport should be postmessaging

mmm so creating the not existing elements via js?!

> [customizer] For the email option, there should be a 'sanitize_callback' checking that the email address is well formed.

Didn't I add it?
https://github.com/presscustomizr/customizr/pull/1403/commits/05695f22ee897d7c563304e1beeb821b64e4df40#diff-f54424c17a661e350bba8856d2a758deR629
Well that's the old way, so you mean to print a message in the customizer. I get it

> [front] on mobile, every contact block should be centered

one on top of each other?
= phone =
= opening hours =
= email =
?

### Last question:
I guess we can move both the module and the template in the pro-bundle while we keep the controller and the topbar logic in customizr. Right?!

Topbar logic:
https://github.com/presscustomizr/customizr/pull/1403/files#diff-d3a4525d3a6fdc4a30580b2b6b9acaceR23
https://github.com/presscustomizr/customizr/pull/1403/files#diff-3c1313869231209fa7e9893eccf134d7R9

**Comment by ghost** [comment]
ah yes, forget about postMessaging then :)

sanitize 👍 but how come I wasn't notified then when I tested a wrong email address...

Centered => yes.

code organization => do as you prefer. ( I guess you love this type of answer... )

**Comment by eri-trabiccolo** [comment]
Yes I do, and I'll do as I said :P 
also the CSS, which is tiny, doesn't need to be moved.

About the email, not sure why didn't work ... have to check.
Might be because of our custom email control...

I'll create a totally new PR anyways.

**Comment by eri-trabiccolo** [comment]
about Contact **Informations** wording:
https://dictionary.cambridge.org/grammar/british-grammar/uncountable-nouns/information
https://www.collinsdictionary.com/dictionary/english/information

Looks like that "informations" is used only in legal english (but cannot find the link where I read it recently)

**Comment by ghost** [comment]
ok, tnx for this no plural form then

**Comment by eri-trabiccolo** [comment]
About this:

> Topbar and socials
> When porting options for topbar and social links, even if the topbar was not displayed before in mobile, the ported option should be desktop_mobile and not desktop like it is in the prototype. The reason is that I think most of the users, including my self, find it more consistent to see it in all devices when the topbar is checked.

Are you sure?
Because that "porting routine" is for already existing users, can we be sure they would be happy to see the topbar appearing in mobiles when they were used to see it only in desktops?

**Comment by ghost** [comment]
Yes sure. We can't be sure, but this is simpler.

**Comment by eri-trabiccolo** [comment]
customizr: https://github.com/presscustomizr/customizr/pull/1408
bundle: https://github.com/presscustomizr/pro-bundle/pull/126

So I think I didn't miss anything from the latest specs.
Just one thing:
[front] on mobile, every contact block should be centered

I read the "mobile" as "extra small devices" (smartphones only then)
and "contact block centered" as only the contact info elements (not socials then) one on top of each other and text center aligned.

Let me know what you think and if I miss anything.

**Comment by ghost** [comment]
OK thanks for the hard work 👍 
social should be centered. Yes that was not said in the specs but yes.

**Comment by ghost** [comment]
but no hurry it will be part of the minor final adjustments.

**Comment by eri-trabiccolo** [comment]
ok, no problem, I can do that easily.

Done.

**Comment by eri-trabiccolo** [comment]
I think I'm not sure having the contact info block on top of each others in mobiles is good, might lead to a too high topbar. Probably having them just centered would be fine enough.

**Comment by ghost** [comment]
@eri-trabiccolo let's schedule a skype this morning to discuss the following spec update.

### Model / View / Controller changes
- [x] the topbar menu should not be replaced by the contact informations in desktop devices. After trying it, I find it not flexible enough. We might have user who need to have this topbar menu and their phone number on top of it for example. When a topbar menu is displayed, the contact information will be printed **above** it. It's up to the user to decide whether or not this menu should be displayed. This won't change the fact that the topbar menu is not displayed on mobile for now.

### Customizer changes
- [x] in `customizer > Header > Contact Information > Display contact info block in the topbar`, replace the current control label by : **_Display a block with your contact information in the topbar._**
- [x] in `customizer > Header > Contact Information > Display contact info block in the topbar`, remove the following note : _Note: In desktop devices this will replace the Top Bar Menu (horizontal), which is, anyways, never displayed in mobile devices_
- [x] in `customizer > Header > General Design settings > Display a topbar`, replace the current notice by the following one : **_You can display a content zone above the header, called topbar. The topbar can be populated with various blocks like a menu, your social links, or your contact information ( pro )._**
- [x] in `customizer > Global settings > Social links > Social links in the topbar`, replace the current notice by the following one : **_Make sure the topbar is displayed. You can control the visibility of the topbar in the [Header general design settings](http://control-focus-link.com)._**  <= the link is unchanged : `javascript:wp.customize.control('tc_theme_options[tc_header_show_topbar]').focus();`
- [x] in `Menus > View All Locations > Top Bar Menu...`, replace the current control label by : **_Horizontal Top Bar Menu. (make sure that the topbar is displayed in the header settings )._**

### Design changes
I've already removed the text-align center.
- [x] the font-size of the contact info icons should be smaller. 0,9em would be ok.

**Comment by eri-trabiccolo** [comment]
Are you fine that socials and tagline, if both contact info and topbar menu are present, are vertically centered?
<img width="572" alt="centered" src="https://user-images.githubusercontent.com/7689242/35507429-0743b966-04ed-11e8-86ca-08132b21904e.png">
And, that, in small mobile, this (the choice of having ci items one on top of each other):
<img width="171" alt="is_this_better" src="https://user-images.githubusercontent.com/7689242/35507454-20370270-04ed-11e8-93ef-bad182808607.png">

is better than this:
<img width="174" alt="than_this" src="https://user-images.githubusercontent.com/7689242/35507458-23208826-04ed-11e8-8154-30e2dfacd919.png">

**Comment by ghost** [comment]
> Are you fine that socials and tagline, if both contact info and topbar menu are present, are vertically centered?

Ah no my fault. this is a point that we forgot to discuss.
=> If both contact info and topbar menu are present, the social + tagline should be aligned with the menu.

For mobile yes => items on top of each other

**Comment by eri-trabiccolo** [comment]
Anyway
bundle: https://github.com/presscustomizr/pro-bundle/pull/132
customizr: https://github.com/presscustomizr/customizr/pull/1422

**Comment by eri-trabiccolo** [comment]
Ah no my fault. this is a point that we forgot to discuss.
=> If both contact info and topbar menu are present, the social + tagline should be aligned with the menu.

Considering that the topbar menu can drop on two lines this kinda changes the things a lot.
But ok, will see how to achieve this in a simple way.
But I'm not sure I will succeed with just one contact-info block template printed.

**Comment by ghost** [comment]
@eri-trabiccolo I understand, this is a difficulty that I was expecting.
I prefer to push the version as it is then for the moment.

**Comment by eri-trabiccolo** [comment]
@Nikeo I'm working on it,
printing 2 templates when needed.
this won't be visible in *Customizr* templates, I'm using two new action hooks.

Can I continue?
About 'as it is then for the moment', do you mean with or without https://github.com/presscustomizr/customizr/pull/1422
?

**Comment by ghost** [comment]
I was at a meeting
Cool. OK then go ahead and finish.
I mean with the latest #1422

**Comment by eri-trabiccolo** [comment]
a meeting? really? did you wear stuff like a top hat while drinking champagne? :P

**Comment by ghost** [comment]
Ah ah I knew you would react to this one.

much less cool than that. I was at an appointment with a guy for the kitchen. Awesome isn't it ? :D

**Comment by eri-trabiccolo** [comment]
Well kitchen brings to meal, so it's awesome of course :P

**Comment by ghost** [comment]
mmm....that's why I found this appointment not that boring actually. now I understand !

**Comment by eri-trabiccolo** [comment]
PRs updated:
customizr: #1422
bundle: https://github.com/presscustomizr/pro-bundle/pull/133

if "we" don't like them you can still merge them and then revert the latest commit for both of them

**Comment by eri-trabiccolo** [comment]
Let me know.
I will do some support, then the SEO thing and back on testing this with a free brain.

Talk you later.
