### ISSUE TITLE
Comment date misaligned in the comment list

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1073]
https://github.com/presscustomizr/customizr/blob/dev/assets/front/scss/0_4_layout/_article.scss#L501
Should be float: right;

Sorry, introduced yesterday night.

**Comment by ghost** [comment]
Ah ok. too late for today.
thx for reporting

**Comment by eri-trabiccolo** [comment]
Mmmm do we have a thousand fixes release? :D 
Ok I'll push a PR in a moment. 
Some changes to the comment template and the reordering blocks via flex system.

**Comment by ghost** [comment]
well...

that's just your opinion man.

**Comment by ghost** [comment]
There are BEVERAGES here

**Comment by eri-trabiccolo** [comment]
Ahah ok.
So I'll split the PR :P
