### ISSUE TITLE
grid masonry : post title color on hover

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1074]
it uses the skin for the moment but it doesn't look good, at least with the default skin.
A light grey could be a better candidate.

![joie](https://user-images.githubusercontent.com/3038156/28500763-5081e0f8-6fce-11e7-9c9d-092252034728.png)

**Comment by eri-trabiccolo** [comment]
Ah ok. This is for the "full-image" type in alternate too. Meaning galleries and images (without excerpt)

**Comment by eri-trabiccolo** [comment]
Looks that the tags buttons in those kind of posts are skinned too
