### ISSUE TITLE
sticky menu not getting the right height when back on top => related to the branding site title being shrinked

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1079]
easy to replicate here : https://wp-themes.com/customizr/

![2017-07-23_20-25-57](https://user-images.githubusercontent.com/3038156/28501866-78888306-6fe5-11e7-9efe-c40389a0cf0d.jpg)

**Comment by eri-trabiccolo** [comment]
Might depend on the throttling sometimes happens sometimes doesn't

**Comment by eri-trabiccolo** [comment]
Well but actually that's not the problem.
The height is right, since it has been set before the sticky happens.
The problem is that the sticky candidate doesn't unstick while it should.

**Comment by ghost** [comment]
http://onwardnews.com/category/cute-funny/
