### ISSUE TITLE
WooCommerce product main image conflict with the opacity force used to show images only when 'centered'

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1080]
That image should be excluded as it's the one wc shows when zooming on hover.
When not zooming that image's opacity is set to 0 via js (inline style)
Forcing it's opacity to 1!important produces the following:
<img width="709" alt="wc" src="https://user-images.githubusercontent.com/7689242/28502012-63f6ef32-6fe9-11e7-9424-acf460590d26.png">

**Comment by ghost** [comment]
scope opacity css to only .czr-img => which is added by a unified way to get the thumbnail model. Not the case right now.
