### ISSUE TITLE
Masonry Grid Layout Option ( Customizr Pro 2.0.2 )

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1082]
Hi,

In post list design, I selected masonry layout.
I can see the following options -> title color. title custom color, Post titles in big caps
but they are not working.

They should be hidden if not intend to work with masonry layout

Please my screen-cast
http://screencast-o-matic.com/watch/cbiZnrlvir

Thank you

**Comment by ghost** [comment]
@denzelchia thanks for reporting the issue. this should be fixed in v2.0.4. Do you confirm ?

**Comment by denzelchia** [comment]
Hi @Nikeo ,

Yes, it's working properly now.

Thank you
