### ISSUE TITLE
Shopping cart icon in topbar breaks responsive layout 

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1083]
Hi,

Enabled topbar with WooCommerce shopping icon. ( Customizr Pro 2.0.2 and Customizr 4.0.2 )
Website is able to scroll right.
I am using all available menus.

Please screen-cast.
http://screencast-o-matic.com/watch/cbiZndlvj5

Thank you

**Comment by eri-trabiccolo** [comment]
Hi David,
Thanks for reporting this.

I'm not able to reproduce it atm.
Are you sure it happens only when the the shopping icon is in the topbar?

**Comment by eri-trabiccolo** [comment]
Other 2 things.
1) any error in chrome console?
2) can you set the horizontal menu position to the right?

**Comment by denzelchia** [comment]
Hi Rocco,

I am Denzel not David. :)

I checked on other browsers, it happens only on my Firefox browser, does not happen in Chrome or Safari.

Does not happen if I remove the shopping cart icon.
Happen if shopping icon is on topbar or primary navbar.

There is no error in firebug.

I can set the horizontal menu position to right.

Please see my screen-cast of all the above mentioned.
http://screencast-o-matic.com/watch/cbiTnYlwhJ

Thank you. :)

**Comment by eri-trabiccolo** [comment]
Ahah sorry Denzel.
Thanks for reporting it!

And it happens only when
1) the navbar where the cart is not sticky
2) the submenu reveal with a fade effect

right?

**Comment by ghost** [comment]
Thanks for reporting the problem @denzelchia !

**Comment by ghost** [comment]
Thanks for the fix @eri-trabiccolo !
