### ISSUE TITLE
Desktop : missing max-width 250px when tc_logo_resize is checked

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1101]
> Hi Nicolas,
> 
> Thanks for a great website, which I have been using for some time now. Regarding “modern”, the following questions:
> 
> – Is it intentional that indents (bullet points and numbering) are no longer indented?
> – Is it intentional that the logo is no longer adjusted in size, although “ticked” in the box?
> 
> Best regards
> Robert

http://www.arvedson.ch/

@eri-trabiccolo is it missing or intentional ? Any feedback / PR welcome thx

# CLASSIC
![classic](https://user-images.githubusercontent.com/3038156/28608930-ce2a176c-71e2-11e7-8586-70cabc830191.jpg)

# MODERN
![modern](https://user-images.githubusercontent.com/3038156/28608937-d1b1ce8e-71e2-11e7-9d3b-e7dfd8ed1828.jpg)

**Comment by eri-trabiccolo** [comment]
Right! :(
