### ISSUE TITLE
List Formatting

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1102]
> Hi Nicolas,
> 
> Thanks for a great website, which I have been using for some time now. Regarding “modern”, the following questions:
> 
> **– Is it intentional that indents (bullet points and numbering) are no longer indented?**
> 
> Best regards
> Robert

**Comment by eri-trabiccolo** [comment]
Cannot reproduce it.
Maybe a plugin resets the indentation?
![list_indentation](https://user-images.githubusercontent.com/7689242/28610583-120fb01c-71e9-11e7-9a9c-39bff4fa0996.png)

Anyway I push a fix to use the same indentation for ul and ol

**Comment by eri-trabiccolo** [comment]
Ah I see, we're talking about the right sidebar.
Ok

**Comment by eri-trabiccolo** [comment]
fixed in #1105
