### ISSUE TITLE
Various minor problems reported in the release note

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1103]
http://presscustomizr.com/wp-admin/edit-comments.php?p=210847&comment_status=approved

> Hi Nicholas, great job on this theme, I find it awesome!
> 
> However, I found some bugs after switching to the modern style:
> – The hierachy of categories is not shown in the categories widget
> – Featured pages don’t appear on the main page
> – The word “Archives” is doubled in the archives widget
> 
> When I switch back to the classical style, the problems above are no more. Is it only my page or have you already heard about those bugs?
> 
> Keep it going, I think it’s one of the best WordPress themes!
> 
> Best regards,
> Michal

**Comment by eri-trabiccolo** [comment]
1. fixed in #1105 
2. fixed (as far as I can see) in #1098
3. fixed in #1106
