### ISSUE TITLE
related posts should be added to classical style

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1117]

**Comment by ghost** [comment]
the block repositionning will not be our friend...flex less...js will be our friend...

**Comment by ghost** [comment]
for the rest, row, span6, etc...

**Comment by ghost** [comment]
@eri-trabiccolo I can see your incredulous face from where I am... :)

**Comment by eri-trabiccolo** [comment]
Ahah.
You have a good sight! :P

**Comment by eri-trabiccolo** [comment]
Specific request:
In the modern style the related posts are outside the "article-container" in desktop viewport (meaning that the allowed space for them doesn't depend on the layout: 2,1 or no sidebars).
In the classic style that wouldn't be true, as:
1) author info
2) comments
3) post navigation
are inside the article container and the related posts should sit between 1 and 2, so inside the article-container.

This means that, for example, in a layout with 2 sidebars, we end up to display pretty small related posts,  so they should appear like in the modern style (with the title below the image).

**Comment by ghost** [comment]
where does the specific request comes from ? forum ? or you ?

**Comment by eri-trabiccolo** [comment]
Me :)
Typo, I meant: Specification request

Il 07/ago/2017 09:27 PM, "Nicolas Guillaume (@nikeo on wp.org)" <
notifications@github.com> ha scritto:

**Comment by ghost** [comment]
Ah ok
forget my first answer.
