### ISSUE TITLE
Classical: WooCommerce enabled generates PHP Notice

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1120]
PHP Notice:  Trying to get property of non-object in wp-includes/class-wp-query.php on line 3760

Because of this:
https://github.com/presscustomizr/customizr/blob/v4.0.4/inc/_dev/class-fire-plugins_compat.php#L895

Basically that filter is triggered too early and is_woocommerce produces the notice there.

I'll use another filter already available for the same purpose:
`tc_set_grid_hooks`

**Comment by eri-trabiccolo** [comment]
This notice might be the cause of this:
https://secure.helpscout.net/conversation/402104583/30198/?folderId=607709

As php warnings might "break" some ajax routines

**Comment by ghost** [comment]
ok merged.
thx for the fix
