### ISSUE TITLE
Modern style : form design revamp

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1122]
https://secure.helpscout.net/conversation/402104583/30198/?folderId=607709#thread-1100611512
> It also messes up the formatting of the checkout and makes it hard to fill out.

**Comment by ghost** [comment]
yes, this becomes urgent. We'll discuss it during our next hangout

**Comment by ghost** [comment]
example before fix : https://www.freitasgouvea.com/premediacao/
