### ISSUE TITLE
In grids > expanding the featured image of a post should always open it as pop in the same context, not open the image media file

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1126]
https://twomando.pl/en/

**Comment by eri-trabiccolo** [comment]
That's clearly a conflicting plugin which is preventing the mfp related js from working fine, of course the image should expand with mfp.
view-source:https://twomando.pl/en/
around line 840:
```
<script type="text/javascript">
  jQuery.fn.prettyPhoto   = function () { return this; };
  jQuery.fn.fancybox      = function () { return this; };
  jQuery.fn.fancyZoom     = function () { return this; };
  jQuery.fn.colorbox      = function () { return this; };
  jQuery.fn.magnificPopup = function () { return this; };
</script>
```
At maximum we can make a further check in js: if $.magnificPopup is not the one we expect, hide or remove the "expand img" icon.

**Comment by twomando** [comment]
Hi, I just found this thread by coincidence. If it is still an issue to fix, I found out which plugin caused a problem: FooBox Image Lightbox. When I deactivated the plugin, everything works fine. I hope it will help you. Thanks for an awesome theme!
