### ISSUE TITLE
In singles the category metas are too close from the post featured image

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1127]
![image1](https://user-images.githubusercontent.com/3038156/28976807-babb8044-793f-11e7-99dc-0685a3f2ae29.PNG)

**Comment by ghost** [comment]
About the spacing, we might need to check different scenarios to make sure we are always looking good.

- For example with and without breadcrumb, => by the way shall we reduce the margin top and bottom for breadcrumb to 2em instead of 2.5em
- With and without a featured image
- with and without metas
- ...

**Comment by eri-trabiccolo** [comment]
- I reduced the breadcrumb margin to 2em
- I apply the "vertical spacing" to the featured image wrapper depending on the location (when boxed before the title => no margin top)
- the margin between the image and the following sibling element (metas, or title) is always the same as it (the following sibling element) doesn't have any margin-top

Please, let me know if the spacing I applied is fine for you too.
