### ISSUE TITLE
w3c validation problem

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1129]
> Hello, Nicolas. When validating a site for validity on the site, validator.w3.org indicates an error
> Error: A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute with the value IE=edge.
> I’ve been searching for a long time how to fix this mistake and found such an option.
> If instead of
> 
> ↩
> 
> Prescribe
> <!–[if IE]
> 
> The error disappears.
> Look, maybe this will help you and you will correct this error in the next update of the topic.

**Comment by eri-trabiccolo** [comment]
Mmm should affect only the classical though.
