### ISSUE TITLE
Slider title from H1 to H2. Any impact ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1130]
Even if this is not a key ranking factor for SEO, we have users complaining about it from time to time.

What would be the impact to switch from H1 to h2 ?

> Hi
> 
> On my home page, I have a slider with just 3 images on it.
> 
> Bing webmaster tools shaow I have 4 H1s. One being the H1 for the page and the other 3 being the titles of each slide - not the page title of the image.
> 
> This damages my SEO. Is there any way to make them H2 or H3, which would be ideal because then they can contribute to the SEO of the page!
> 
> If not then is there a way to have the titles with no H at all?
> 
> Best regards
> 
> John

**Comment by JTS-IL** [comment]
The slider title shouldn't be any h at all, according to accessibility
rules WCAG 2.0, the h should be applied only for hierarchy, and not for
design.
On my sites i remove the h1, and replaced it with plain style

יעקב גלזר
-----------------------------------------------
בקרו באתר שלי : www.glezer.co.il
