### ISSUE TITLE
404 page quotation

### ISSUE THREAD

**Issue by Growlertiger** [Nikeo/customizr#1142]
Customizr provides a 404 page which contains a quotation from George Orwell. There is no option to remove the quotation.

There are two problems with this.
1. For many websites this quotation is not appropriate. 
2. George Orwell never wrote it or said it, it is one of those things that gets repeated on the internet but is not correct. This page gives you all the information:
http://quoteinvestigator.com/2013/02/24/truth-revolutionary/
So please may I request that you simply remove the quote entirely, or make it an option. Having a false quote does not reflect well on the system or any website using it.

While investigating this I looked for the text in the files and found it in the file customizr-en_GB.po at lines 2939 onward.

I found there is another quotation, this one attributed to Winston Churchill. And this is also a false quotation. Winston Churchill never said it or wrote it, and it is often attributed to Abraham Lincoln (who also didn’t say it).
See here: http://quoteinvestigator.com/2014/06/28/success/

Here is the text I saw in the file:
#: inc/czr-init.php:703
msgid “Speaking the Truth in times of universal deceit is a revolutionary act.”
msgstr “Speaking the Truth in times of universal deceit is a revolutionary act.”

#: inc/czr-init.php:704
msgid “George Orwell”
msgstr “George Orwell”

#: inc/czr-init.php:705 templates/content/no-results/404.php:14
msgid “Sorry, but the requested page is not found. You might try a search below.”
msgstr “Sorry, but the requested page is not found. You might try a search below.”

#: inc/czr-init.php:710
msgid “Success is the ability to go from one failure to another with no loss of enthusiasm…”
msgstr “Success is the ability to go from one failure to another with no loss of enthusiasm…”

#: inc/czr-init.php:711
msgid “Sir Winston Churchill”
msgstr “Sir Winston Churchill”

**Comment by ghost** [comment]
Thank you very much @Growlertiger. The quote investigations looks very well documented.
Anyway, correct or not, I agree with your statement. Those quotations are not appropriate for all websites and should be either more generic or customizable.
Something has to be improved here !

**Comment by eri-trabiccolo** [comment]
I remove the 2-ms label as they are not used there

**Comment by ssknits** [comment]
Thank you all, especially @Growlertiger for opening this issue. I would very much like to see this fixed.

**Comment by ssknits** [comment]
It looks like the quote is no longer there. Thank you!

**Comment by Growlertiger** [comment]
It is still there, @ssknits - perhaps you switched from "Classic" to "Modern" which doesn't have the issue.

**Comment by ssknits** [comment]
Indeed, @Growlertiger that is what I did. Sorry. I hope this gets resolved soon!

**Comment by cjbatson** [comment]
Hi everyone! I agree that quotes should be accurate but now my 404 and Search Not Found pages are boring! The quotes were PERFECT for my blog but I agree, I can't have inaccurate quotes!! @Nikeo I hope you guys are going to add some format options etc "insert your quote here" type format options!! Thank everyone and keep up the good work!!

**Comment by ghost** [comment]
@cjbatson :)
The customization of the 404 and no results page should be available in future. This is something I've always had in mind.
