### ISSUE TITLE
Sticky posts not displayd on top of post list on home page.

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1143]
> Here is my website URL: repaircafetoronto.ca. We have a sticky post for our next event. That post has always been at the top of the post list on the home page as it should be. But now it is not at the top. I believe this started to happen after the last update I did to the theme but I'm not 100% sure about that.
> 
> I have tested by unchecking the "sticky" option on the post, saving, then re-checking "sticky" and re-saving. I have also created a test post with "sticky" checked but backdated the publish date so that it won't appear among the first three posts. In both cases, the post does show up in the list but NOT at the top of the list as it should be. So the post exists but the list is ordered ONLY by date and "sticky" is being ignored by the theme.

> 
> WORDPRESS: WordPress 4.8.1 running Customizr theme.BROWSER: I don't think this is relevant. I've tried different browsers but of course the home page is created by the server not the browser so it's always the same error everywhere.
> --
>

**Comment by ghost** [comment]
Website : repaircafetoronto.ca
@eri-trabiccolo any idea ? I can't reproduce this on my end.

**Comment by ghost** [comment]
not urgent

**Comment by eri-trabiccolo** [comment]
Well the first post in that home page is a sticky post actually.
So that doesn't be a good example... :/
