### ISSUE TITLE
html is stripped out of the featured text on the front page.

### ISSUE THREAD

**Issue by sbaeder** [Nikeo/customizr#1146]
https://github.com/presscustomizr/customizr/blob/559d7a0f0e27520344034d6f1073b675c0fc97e2/inc/czr-front.php#L3761

In this line, the html is stripped out.  BUT when using the Customizer function to add this special featured text, it allows HTML and shows its effects (which would be a good thing).  The html is stored in the featured text, BUT it is stripped out before this text is passed to the web page being constructed below.

Either the front end customization when adding this text should not honor any HTML - OR (preferred), modify this line by just removing the code in bold below...

  $featured_text = apply_filters( 'tc_fp_text_sanitize', **strip_tags**( html_entity_decode( $featured_text ) ), $fp_single_id, $featured_page_id );

**Comment by JTS-IL** [comment]
I agree,
I think that the text should be full html

יעקב גלזר
-----------------------------------------------
בקרו באתר שלי : www.glezer.co.il
