### ISSUE TITLE
In modern style author name changes to user name instead of public display name

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1148]
> I like the modern style.
> But in modern style author name changes to user name instead of public display name.
> There is no problem with classical style.
> I tried many things but I couldn’t solve this.
> Please advise how to change author name from user name to public display name.
> Thanks

**Comment by eri-trabiccolo** [comment]
Ah ok,
this happens only in the metas.
Will do that later

**Comment by ghost** [comment]
ok
