### ISSUE TITLE
WooCommerce : "add to cart" buttons on the WC shortcode do not work ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1155]
http://www.raffermir-seins.fr/test02061963/

> Hi,
> 
> I use your theme and I am very satisfied. I have the latest version and all my plugins are up to date.
> I noticed a problem.
> The "add to cart" buttons on the WC shortcode do not work.
> The degug shows this script error:
> 
> TypeError: 'toString' called on an object that does not implement interface HTMLAnchorElement.http://www.raffermir-seins.fr/test02061963/wp-includes/js/jquery/jquery.js?ver=1.12.4 line 4
> 
> I disable each plugin but error is always here. Has anyone ever had this error and have you a solution for me? You can see the error on the page www.cryotonic-beaute.com..
> Thank you in advance

**Comment by eri-trabiccolo** [comment]
I cannot reproduce this :/

**Comment by ghost** [comment]
OK thank you for the tests

**Comment by eri-trabiccolo** [comment]
Here's another user reporting this.
The user also found the conflicting feature (external links):
https://secure.helpscout.net/conversation/432368244/32287/?folderId=607546#thread-1170196421

**Comment by eri-trabiccolo** [comment]
This bug also affects (same reason: link is in the `.entry-content` ) add to cart buttons of cross-sell products in the cart page:
https://wordpress.org/support/topic/woocommerce-issue-cross-sell-doesnt-get-added-to-cart/

From my tests - I did some time ago - the way the code is done at the moment makes avoiding this conflict impossible - cannot use the skip selector list (don't remember at the moment why), just running the jquery plugin on the element produces the conflict.

We should be able to avoid this very (cross sell add to cart) issue by disabling both the ext links options at least in the WooCommerce cart page.

**Comment by eri-trabiccolo** [comment]
see https://github.com/presscustomizr/customizr/issues/1634
