### ISSUE TITLE
WpDataTables plugin edit entry form not formatting correctly

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1158]
> WpDataTables plugin provides functionality for Users to edit tables on the front end. When a user clicks on Edit or New a popup form allows the User to add a new row of information to the table. For 8 months I have used this plugin with Customizr as my theme. WpDataTables recently updated to version 2.02 and now the popup edit form will not format correctly. Strangely the form still formats correctly on an iPhone but not on browsers, Edge, Explorer, and Chrome. After contacting WpDataTables support their suggestion was to contact Customizr authors to understand what can be done with the bootstrap files to be compatible with this plugin. Can you help or is changing themes the only solution?

**Comment by eri-trabiccolo** [comment]
See https://github.com/presscustomizr/customizr/issues/1152
