### ISSUE TITLE
Yoast SEO : when show_on_front option is set to "nothing" => homepage SEO not editable / front page meta not working

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1170]
Reported here
https://wordpress.org/support/topic/homepage-seo-not-editable-because-the-page-doesnt-exist/
https://wordpress.org/support/topic/cant-activate-frontpage-meta-using-yoast-seo/

> Anyway, i looked a little closer in Yoast’s code (/wp-content/plugins/wordpress-seo-premium/admin/views/tabs/metas/home.php) and saw this:
> 
> if ( 'posts' == get_option( 'show_on_front' ) ) {
> 
> In wordpress wp_options table if i set show_on_front = posts (with this setting, customizr pro is showing latest articles on front page) i also get the homepage meta description and keywords and it is also enabled in the Admin panel. So with this setting everything is fine, but the problem is i don’t want to enable latest articles on my homepage 🙂
> 
> L.E: because the default value of “show_on_front = nothing”, an unorthodox way to make it work without activating posts on frontpage is to modify in yoast plugin “/public_html/wp-content/plugins/wordpress-seo-premium/frontend/class-frontend.php” line 218 to:
> return ( is_home() && 'nothing' == get_option( 'show_on_front' ) );
> and “(/wp-content/plugins/wordpress-seo-premium/admin/views/tabs/metas/home.php” line 12 to:
> if ( 'nothing' == get_option( 'show_on_front' ) ) {
> 
> This will make it work, until maybe in the future will be fixed.

**Comment by eri-trabiccolo** [comment]
Well show_on_front cannot be nothing for wp, so yoast seo dosen't treat that case.
The theme introduces something that plugins are not aware of.
I can try to see whether yoast seo has some filters we can use, but I doubt about it.

**Comment by ghost** [comment]
filter : yep that's the idea.

**Comment by ghost** [comment]
the priority is the gallery dev for the moment tough

**Comment by eri-trabiccolo** [comment]
yeah sure.
and 

> filter : yep that's the idea.

but what I wanted to highlight was my "I doubt..." :D
