### ISSUE TITLE
Single posts : add option to display the author box and the related posts after the content, not only after the content + sidebars

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1173]

**Comment by eri-trabiccolo** [comment]
requested on helpscout too:
https://secure.helpscout.net/conversation/457965433/33899?folderId=607541

**Comment by norbusan** [comment]
Just to add my 5 Yen, please please ;-)

**Comment by ghost** [comment]
# Quick spec

this dev will be done In 2 PRs

## First PR
Add 3 select settings in main-content > Pages & Post layout
- author box
- related posts
- comments ( shared by posts and pages )


Html => blocks are embedded outside the article

adapt models and templates to use the options.

## Second PR

- ubiquity of customizer controls
- shall we create a simple control with small layout icons ?
- style adjustments : for related posts and nested comments with 2 sidebars in particular

**Comment by norbusan** [comment]
Thanks a lot
