### ISSUE TITLE
Menu position problem : right / left positions are not applied

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1175]
> I'm using a local server to learn how to work with wordpress. I installed and activated your theme. I went to header options and navigate menu's. From there i tried to change the position of the main menu. So i was at 'MAIN MENU DESIGN' --> 'Menu position (for "main" menu)' --> i chose 'menu on the left'
> BUT THE FREAKIN menu stay on the right. Fix it please.

**Comment by ghost** [comment]
I could reproduce the issue for both styles

**Comment by eri-trabiccolo** [comment]
I cannot reproduce it for the classical style.
Do you confirm you can?

**Comment by ghost** [comment]
The problem is only for modern yes.
