### ISSUE TITLE
ul, ol margins

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1183]
Following this feedback http://presscustomizr.com/release-note-for-customizr-pro-v2-0-9-and-customizr-free-v4-0-8/comment-page-1/#comment-375711

> With the option “Modern”, the theme handles bullet point and numbering differently compared with “Classic” and what is considered correct. I.e. with bullet points and numbering, the second and following lines normally indent to the start of the text in line one.
> 
> Is the intention with “Modern”, that it refrains from doing so, or will it be adjusted?

This user raise a good point, I would prefer having a left margin ( right for RTL ) on lists, just like here for example : http://docs.presscustomizr.com/article/3-creating-a-slider-with-customizr-wordpress-theme#remove-default-slider
This margin should be applied only for the lists inside a page or post content.
I think we already discussed this point a few monthes ago.

@eri-trabiccolo from your standpoint, would there be any unwanted side effect ( with plugins or smthing else) of modifying the current css rules for ul, ol, which are 
```
ol, ul {
    margin: 0;
    padding: 0;
}
```

to something like

```
.entry-content ol, .entry-content ul {
    margin: 0 0 9px 25px;
    padding: 0;
}
```

To be discussed next monday !

**Comment by eri-trabiccolo** [comment]
I did this using em unit according to the previous style.
Please check if it's fine for you.
The ul/ol relevant part in the following commit
https://github.com/eri-trabiccolo/customizr/commit/96a3c260f794c436e4e38e67edb8e0b382055356
is the one in
assets/front/scss/0_4_layout/_content.scss
