### ISSUE TITLE
Prevdem error on singulars

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1194]
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function CZR_prevdem::czr_fn_filter_thumb_src(), 1 passed in /srv/www/wordpress-default/public_html/wp-includes/class-wp-hook.php on line 298 and exactly 6 expected in /srv/www/wordpress-default/public_html/wp-content/themes/customizr/core/class-fire-prevdem.php:151

**Comment by eri-trabiccolo** [comment]
solution:
replace:
https://github.com/presscustomizr/customizr/blob/v4.0.8/core/front/models/content/common/media/class-model-thumbnail.php#L189
with:
```
               $post_thumbnail['tc_thumb'] = apply_filters( 'czr_thumb_html', get_the_post_thumbnail( $post_id, $this->size ), $requested_size = $this->size, $post_id = $id, $custom_thumb_id = null, $_img_attr = null, $tc_thumb_size = $this->size );
```
(in a near future the post thumbnail should be get using czr_fn_get_thumbnail_model() too)

**Comment by eri-trabiccolo** [comment]
Are you about to release the free version too? If yes take a look a this issue+solution as it affects the prevdem => wp.org preview too then.

**Comment by ghost** [comment]
No I'll wait for the custom header color to release the free.
Yes thanks for the reminder. I'm on it now !
