### ISSUE TITLE
Slider lead text length truncated

### ISSUE THREAD

**Issue by tilmanbremer** [Nikeo/customizr#1195]
The lead text of a slider is being truncated when saved. This did not happened previously, but I couldn't find out what version changed that and as I don't change the sliders ofter, I don't know exactly when it appeared for the first time. 

In my case, this is bad, because I have multilanguage text there with qtranslate-x. Because customizr doesn't work well with qtranslate-x here, I have to post all languages in the one field with e.g.
`[:en]This is the lead text[:de]Dies ist der Beschreibungstext[:]`
This understandibly gets longer, so the text is just truncated sharply upon saving.

I tried this solution in my child theme, but it doesn't seem to work:
https://presscustomizr.com/snippet/changing-the-default-length-limits-of-the-slider-texts/

A solution to my problem would be
a) Having the slide setup work with qtranslate-x, so that there is a seperate field for the lead text for every language (I have no idea what is needed for that but it would be the best solution).
b) A working snipped to increase the text length of that field
c) A way to completely disable the truncation of text in those fields.

Customizr Free 4.0.8 with Wordpress 4.8.2

**Comment by eri-trabiccolo** [comment]
Hi there,
thanks for reporting this.

This issue has been addressed and the fix will be most likely shipped in the next theme release.

**Comment by tilmanbremer** [comment]
Wow, thanks a lot for that fast fix! Nice to know this was actually something and not just me being stupid :-).
