### ISSUE TITLE
Unify the way images can be navigated

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1197]
https://wordpress.org/support/topic/customizr-classical/#post-9545935

> Photographers best WordPress theme is Customizr Classical (not mordern). Because when you click on any published image, automatically it shows the next image. While any other theme exposes the full image for download or save, which is ridiculous for original image producers i.e photographers. By that ways big or small groups are blogging on stolen images and discouraging photographers from uploading good content online. Hopefully Customizr is helping photographers with its Classical version, till now.

http://www.rayphoto.in/culture/durga-idol-6191/

**Comment by ghost** [comment]
Adding an attachment fmk inner template ( not a wp tmpl)

**Comment by eri-trabiccolo** [comment]
Diving into this I realized that Customizr classical style doesn't display attachments which are not images. Its attachment "template" assumes all the attachments are images, but this is not true at all (e.g. you can have audio/video attachments).
So  for this issue I would care only about attachments which are images. Meaning that all the attachments which aren't an image would be displayed using the fmk post inner template.
I'm moving into this direction unless you (@nikeo) do not agree.

p.s.
then a similar thing should be done for the classical style too.

**Comment by ghost** [comment]
I'm with you. Let's do it this way.
