### ISSUE TITLE
Modern style: the language of the theme sticks to English

### ISSUE THREAD

**Issue by cjamin** [Nikeo/customizr#1201]
In modern style, the language of the theme appears to be in English even though the site is configured to be in French.
If I switch to Classical style, then it's in French.

**Comment by cjamin** [comment]
Any news on this?

**Comment by eri-trabiccolo** [comment]
I cannot reproduce this issue,
can you be a little bit more specific? E.g. what are the untranslated strings? Are they in the admin or in front?
Have you read the documentation about the theme strings translation?
https://docs.presscustomizr.com/article/71-translating-the-customizr-wordpress-theme

**Comment by cjamin** [comment]
Sorry, I had not updated the theme to the latest version. It seems to be fixed!

**Comment by eri-trabiccolo** [comment]
Thanks for the feedback, glad to hear it's fixed for you too :D
