### ISSUE TITLE
Modern: h* position, should not be relative by default?!

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1202]
https://wordpress.org/support/topic/image-link-problem-in-connection-with-headline

Having them relatively positioned might create the kind of issue reported in the above topic.

The `position: relative` was a _design choice_ most likely due to the fact that most of the headings have the "underline" (after pseudo element) which is absolutely positioned in reference to them.

Though that should limited to those h* which have the "underline" and not to all.
Consider that all these elements (^) already have the `position` attribute set to relative, so I really don't see why we shouldn't remove the position: relative here:
https://github.com/presscustomizr/customizr/blob/v4.0.8/assets/front/scss/0_1_base/_typography.scss#L90

(more in depth tests are needed)

**Comment by ghost** [comment]
@eri-trabiccolo can you terminate this one ?

**Comment by eri-trabiccolo** [comment]
Just have to test all the h* so verify I didn't miss anything.
