### ISSUE TITLE
Feature request: submenu collapsing in mobile and sidenav menu.

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1204]
Since the mobile menu now is a totally different menu we can add an option to display the submenu collapsed (uncollapsing on click) as it won't interfere with the "horizontal" menus.
Same can be done for the sidenav menu.

With some additional work we can then port this for the classical style (meaning porting also the different mobile menu there).

**Comment by ghost** [comment]
@eri-trabiccolo to be discussed during the next point

**Comment by ghost** [comment]
Ah yep
cool !

**Comment by ghost** [comment]
> I like the new modern style of your theme. I’m working with the pro version and actually starting to built my new site. My database crashed and so I started to built a completely new site. I’m not so happy with the style of the mobile menue. Is there a possibility to change the fact, that all items are open? Think about click on the parent items to open the childs? I have used Max Mega Menue for my previous site. The mobile menue looked nice but I would like to built my new site without the plugin. Do you have some advices how to manage the mobile menue more comfortable? Thanks a lot.
> Birgit
> P.S. Because I could not see my comment on my PC I post it again. Sorry, when it is a second comment now.
