### ISSUE TITLE
update wpml compat for featured page

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1205]
> I've followed the instructions on your support page here:
> 
> http://docs.presscustomizr.com/article/207-turning-your-wordpress-site-multilingual-with-wpml-and-the-customizr-theme
> 
> ...to set up a site running in english and french.
> 
> But my translated featured pages aren't showing in french on the front page, when I switch to that lanugage.
> 
> Does WPML support only work with the Pro version of the theme?

> The site I am working on is
> 
> http://aptpuo.jungle.ca
>

**Comment by ghost** [comment]
@eri-trabiccolo don't be sarcastic please :)

**Comment by eri-trabiccolo** [comment]
Mmm I think that article misses how to translate the the featured text and featured text button:
https://wordpress.org/support/topic/featured-page-front-page-content-not-translating/#post-9562624

I just tested it works with wpml 3.7.1

**Comment by eri-trabiccolo** [comment]
As reported by the user the featured pages (page ids) are not translated in modern style.

**Comment by eri-trabiccolo** [comment]
posts slider works fine too
