### ISSUE TITLE
Slider : Add an option to control the visibility of the bullets

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1207]
relevant only for desktop.
we won't display the bullets on mobiles

**Comment by eri-trabiccolo** [comment]
I guess the slider bullets?!

**Comment by ghost** [comment]
yep :)

**Comment by ghost** [comment]
Ah we did not talk about this one.
can you put it next in your list ? @eri-trabiccolo

**Comment by eri-trabiccolo** [comment]
sure man

**Comment by eri-trabiccolo** [comment]
just wanted to update the specs as we agreed to display the dots in mobiles too (right?)

**Comment by eri-trabiccolo** [comment]
Fixed with:
https://github.com/presscustomizr/customizr/pull/1257
https://github.com/presscustomizr/customizr-front-js-parts/pull/19
