### ISSUE TITLE
Modern Skin: the global skin CSS isn't printed if no custom header skin choosen

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1215]
I think this commit hasn't been completely merged:
https://github.com/presscustomizr/customizr/pull/1198/commits/106dd9c5f0cc0ee8f1e74abfc978de2132b792c1

Pushing a new PR in a minute

**Comment by eri-trabiccolo** [comment]
@Nikeo this is important to fix before next release.

**Comment by ghost** [comment]
yep important
merged
