### ISSUE TITLE
WC_Cart::get_cart_url obsoleto

### ISSUE THREAD

**Issue by SUGO-es** [Nikeo/customizr#1223]
PHP Notice:  WC_Cart::get_cart_url ha quedado <strong>obsoleto</strong> desde la versión 2.5. Utiliza wc_get_cart_url en su lugar.

/wp-content/themes/customizr/inc/czr-init-ccat.php - line:1470

Después de instalar WC 3.2.1 me llena el registro con este mensaje.

Solución : 
`1470  <a class="cart-contents" href="<?php echo esc_url( wc_get_cart_url() ); ?>" title="<?php _e( 'View your shopping cart', 'customizr' ); ?>">`

Saludos cordiales

**Comment by eri-trabiccolo** [comment]
Thanks for reporting this.
Will be fixed in the next release. ;)

**Comment by benxaque** [comment]
Hello friends!!
I have the same problem and i don´t know how to fix it!

Any help are welcome

Notice: WC_Cart::get_cart_url ha quedado obsoleto desde la versión 2.5. Utiliza wc_get_cart_url en su lugar. in /var/www/vhosts/35/208229/webspace/siteapps/WordPress-220203/htdocs/wp-includes/functions.php on line 3831

**Comment by eri-trabiccolo** [comment]
Hi there,
the fix will be shipped in the next Customizr theme release.

Anyway on a production website you should not have any warning print ;)

**Comment by SUGO-es** [comment]
Exactly, it's annoying in the debug log, but it's a warning, not an error;)

Sorry for my English if it is not very correct.

Best regards.

**Comment by benxaque** [comment]
Thanks very much friends!!!

Gracias a los dos por contestar tan pronto amigos!!!
Tu inglés es más que bueno

Un abrazo desde La Coruña
