### ISSUE TITLE
Description of an image in an attachment page should always be displayed below the image

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1231]
Following #1197 implementation
Here's the problem

![attachment_description](https://user-images.githubusercontent.com/3038156/31730693-fe211c12-b432-11e7-85f3-6b7caba46148.png)

A short description is not displayed below the image.
@eri-trabiccolo  Can you "flexilize it" ?

**Comment by eri-trabiccolo** [comment]
ops, that's weird and should not happen

**Comment by ghost** [comment]
yep

**Comment by eri-trabiccolo** [comment]
Anyway the figure should be centered too,
so the CSS has not been compiled.

I'm on it

**Comment by eri-trabiccolo** [comment]
Man, anyway I'm not sure what you're testing, because there are also php files to concatenate.

Anyway this is a bug and I'm about to push a fix
