### ISSUE TITLE
Improve style switching suggestion for child-theme users

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1236]
At the moment we:
1) say to add the constant definition in the wp-config.php file.
This is not necessarily good in multisites, as they have one wp-config.php file, and one might want to apply it not to all the sites.
We should say that that constant definition should be added in the child-theme functions.php (at least for multisites).
2) the notice reads:
> Add the the following code to your wp-config.php file to switch between the classical and modern styles : 
> define( 'CZR_MODERN_STYLE', true );.

we should remove that '.' (dot) after the semicolon, as it might create confusion.

All in all, child-theme users can always perform the following steps:
1) activate the parent theme
2) switch to modern or classical style
3) activate the child-theme

Without messing with code.

We might also want to create a specific doc for this.

**Comment by ghost** [comment]
The notice has been updated in v4.0.10 / v2.0.15

**Comment by JTS-IL** [comment]
Just thinking...
Why does a simple user need to edit wp-config.php?
Can't it be a configuration menu switch?
