### ISSUE TITLE
[Customizr] WooCommerce - Account Details Password change input broken layout.

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1243]
Hi @Nikeo,

Issue is reported by customer on helpscout.
https://secure.helpscout.net/conversation/453308599/33625?folderId=607541

I am able to replicate issue on my localhost.
I am using Customizr 2.0.11 ( Modern Design ) , WP 4.8.2, WooCommerce 3.2.1

After login to WordPress admin, go to My Account and Click on Account Details.
The Password change input is squeezed at the right hand side.

Please see screen-cast.
http://screencast-o-matic.com/watch/cb60exINRi

Have a nice day,

Best regards,
Denzel

**Comment by ghost** [comment]
OK Thanks for reporting this @denzelchia
