### ISSUE TITLE
New option to make sidebars sticky top, bottom, both

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1250]
like in hueman
like in the WP admin

**Comment by ghost** [comment]
example

https://freeyourselffromyourjob.com/ using https://fr.wordpress.org/plugins/q2w3-fixed-widget/

**Comment by eri-trabiccolo** [comment]
requested:
https://secure.helpscout.net/conversation/497300895/36118?folderId=607709

**Comment by ghost** [comment]
will be implemented for Nimble https://github.com/presscustomizr/nimble-builder/issues/294
