### ISSUE TITLE
WP4.9 compat => customizer additional CSS => fix default value producing incorrect code

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1255]
## First what happens with 4.9:
<img width="282" alt="2017-10-26_13-04-02" src="https://user-images.githubusercontent.com/7689242/32049686-37fe8c78-ba4e-11e7-9566-1f89887eeb93.png">

## then the culprit:
https://github.com/presscustomizr/customizr/blob/v4.0.9/core/_dev/_czr/class-czr-init.php#L247

## then the reason:
In 4.9 wp removes the comment block in the additional CSS default:
```
/*
You can add your own CSS here.

Click the help icon above to learn more.
*/
```
(improved and moved in the section description)
so  our `substr( $original, 0, strlen($original) - 2)`, in the code above makes no great sense, plus we don't add a trailing `/*` to our chunk : `$new_def = sprintf( "%s\n%s\n%s\n*/",`

## finally the "solultion to implement":
in wp 4.9+ we should:
a) not append our "comment" to the setting's default
b) rather add it to the section description 

we can keep the current code when wp<4.9

edit:
Additionally it breaks the customizer:
<img width="749" alt="2017-10-26_14-17-03" src="https://user-images.githubusercontent.com/7689242/32052412-72fae1fa-ba58-11e7-956e-3ef2451ff7c5.png">

But I think this side effect is more a wp issue, it should not happen, because even broken options cannot be amended then.

**Comment by ghost** [comment]
Let's remove this

**Comment by ghost** [comment]
I'm on it
