### ISSUE TITLE
404 content not displayed (and casual post/page content displayed) in a very rare case

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1260]
Can be verified on the demo:
https://demo.presscustomizr.com/tag/a/b

this should display the 404 content while it displays the content of the page with post id 1656 (not sure why this particular id in this case), as it is an actual 404 as you can also see from the title tag.

This happens because for some reason (I think due to a wp bug) `is_404()` can `have_posts()` while we assume it's not the case:
https://github.com/presscustomizr/customizr/blob/v4.0.8/templates/index-no-model.php#L87

This weird wp behavior can be verified with whatever theme (e.g. with twentyseventeen using the following code: https://hastebin.com/olawakoxan.php)

**Comment by ghost** [comment]
oh ok good catch.
You should report this to core I think
thank for the fix !

**Comment by eri-trabiccolo** [comment]
Yeah I should :)
