### ISSUE TITLE
v4.0.10 tests

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1264]
## Added features
- [ ] slider => full worklflow of creation + display it on home and on a post / page
- [ ] slider => smartload test on ms and cs
- [ ] attachment => layout meta filed test

## Others
- [ ] WooCommerce => random tests
- [ ] Version of WordPress => are we sure that everything works, including the customizer, with both 4.8 and 4.9beta4

## User started before
- [ ] From **none** to **Customizr Dev**: expected Modern => tested Modern
- [ ] From **none** to **Customizr Pro Dev**: expected Modern => tested Modern 
----------------------------
- [ ] From **Customizr Stable** to **Customizr Dev**: expected Modern => tested Modern
- [ ] From **Customizr Stable** to **Customizr Pro Dev**: expected Modern => tested Modern 
---------------------------------------------
- [ ] From **Customizr Pro Stable** to **Customizr Pro Dev**: expected Modern => tested Modern
---------------------------------------------
- [ ] From **Customizr Old** to **Customizr Dev**: expected Classic => tested Classic
- [ ] From **Customizr Pro Old** to **Customizr Pro Dev**: expected Classic => tested Classic

**Comment by eri-trabiccolo** [comment]
Tests I conducted:
## Added features
- [x] slider => full worklflow of creation + display it on home and on a post / page
- [x] slider => smartload test on ms and cs
- [x] attachment => layout meta filed test

## Others
- [x] WooCommerce => random tests
- [x] Version of WordPress => are we sure that everything works, including the customizer, with both 4.8 and 4.9beta4
(see https://github.com/presscustomizr/pro-bundle/issues/106)
## User started before
- [x] From **none** to **Customizr Dev**: expected Modern => tested Modern
- [x] From **none** to **Customizr Pro Dev**: expected Modern => tested Modern 
----------------------------
- [x] From **Customizr Stable** to **Customizr Dev**: expected Modern => tested Modern
- [x] From **Customizr Stable** to **Customizr Pro Dev**: expected Modern => tested Modern 
---------------------------------------------
- [ ] From **Customizr Pro Stable** to **Customizr Pro Dev**: expected Modern => tested Modern
---------------------------------------------
- [ ] From **Customizr Old** to **Customizr Dev**: expected Classic => tested Classic
- [x] From **Customizr Pro Old** to **Customizr Pro Dev**: expected Classic => tested Classic
