### ISSUE TITLE
The comment text area should be white or lighter than now

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1268]
![2017-10-29_18-15-18](https://user-images.githubusercontent.com/3038156/32146304-6bcbb844-bcd5-11e7-80a6-0a116edc814d.jpg)

**Comment by eri-trabiccolo** [comment]
Ah,
it has the same background of:
- post/page navigation
- related posts (content background)
at least, which is our $grey-latest in scss.

I just write it here in case we want to opt for another grey, to not miss this omogeneity.

**Comment by ghost** [comment]
yep, thanks
