### ISSUE TITLE
Mobile menu : child menu expansion on click. Let's discuss it.

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1271]
> I like the new modern style of your theme. I’m working with the pro version and actually starting to built my new site. My database crashed and so I started to built a completely new site. I’m not so happy with the style of the mobile menue. Is there a possibility to change the fact, that all items are open? Think about click on the parent items to open the childs? I have used Max Mega Menue for my previous site. The mobile menue looked nice but I would like to built my new site without the plugin. Do you have some advices how to manage the mobile menue more comfortable? Thanks a lot.
> Birgit
> P.S. Because I could not see my comment on my PC I post it again. Sorry, when it is a second comment now.

**Comment by eri-trabiccolo** [comment]
see:
https://github.com/presscustomizr/customizr/issues/1204

**Comment by ghost** [comment]
Yeah. added to short term devs.
