### ISSUE TITLE
WooCommerce Shopping cart  icon : need to be tapped twice on mobile to open the cart page

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1274]
> Regarding the Shopping Cart, you can verify for on your own Demo that it does not work properly. It requires a double-click on a mobile device. How quickly can you fix this?

I am able to reproduce the bug.
@eri-trabiccolo can you take a look ?

**Comment by eri-trabiccolo** [comment]
yep.

**Comment by ghost** [comment]
thx

**Comment by eri-trabiccolo** [comment]
it acts like a dropdown. i'm on it.

**Comment by ghost** [comment]
yes exactly. cool thx
