### ISSUE TITLE
Text in right sidebar is right aligned instead of left ( Modern Style )

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1280]
Hi @Nikeo,

This issue is reported in the following support thread.
https://wordpress.org/support/topic/left-align-the-right-sidebar/

I made a test in Modern Style, by using a text widget with some text in paragraph, and deploy it in the right sidebar.

<img width="1670" alt="screen shot 2017-11-02 at 11 08 58 am" src="https://user-images.githubusercontent.com/9284811/32307996-6b4825b0-bfbe-11e7-85a6-66e88e2e3542.png">

On the front-end, you can see the text is right aligned.

<img width="1674" alt="screen shot 2017-11-02 at 11 09 05 am" src="https://user-images.githubusercontent.com/9284811/32308044-b877b8fa-bfbe-11e7-9fcc-9bc425cb411b.png">

I am not sure if this is by design or a bug.
If it's by design, I think we should provide an option to left align text in right sidebar.

Thank you

**Comment by ghost** [comment]
Thank you for reporting this @denzelchia

**Comment by JTS-IL** [comment]
Please make sure that fixing it will still right align on RTL sites

**Comment by eri-trabiccolo** [comment]
That was a design choice anyway, nothing unexpected. ;)

**Comment by ghost** [comment]
yes but I agree that this can be misleading

**Comment by eri-trabiccolo** [comment]
sure, just wanted to say it's not a bug :)
Anwyay the code should be ready to accept this change of mind (or an option) easily:
https://github.com/presscustomizr/customizr/blob/dev/core/class-fire-init.php#L50

the CSS is determined by that class, and is rtl compliant.
