### ISSUE TITLE
4.0.10 release test

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1281]
- [ ] - FPU as standalone plugin
- [ ] - Customizr free and pro with a child theme
- [ ] - Customizr Pro Infinite on +  all types of grids +cs + ms
- [ ] - Customizr Pro masonry with and without infinite
- [ ] - Customizr Free smartload disabled + check on post lists various grids + singulars +cs +ms
- [ ] - Customizr Free with centering enabled / disabled. + cs + ms
- [ ] - activate Twenty Seventeen + and preview Customizr Free prevdem mode from the customizer
- [ ] - old php Customizr Free + Pro + cs + ms
- [ ] - Font Customizr on Customizr Pro
- [ ] - Customizr Free and Pro on 4.8.3

**Comment by ghost** [comment]
I'm building the versions

**Comment by eri-trabiccolo** [comment]
could you let me know when they're ready, not sure I get notifications because of the overwriting...

**Comment by ghost** [comment]
ah sorry they are

**Comment by ghost** [comment]
https://github.com/presscustomizr/customizr-pro/releases/tag/v2.0.15
https://github.com/presscustomizr/customizr/releases

**Comment by ghost** [comment]
well you know where they are
the builds are done

**Comment by eri-trabiccolo** [comment]
- [x] - old php Customizr Free + Pro + cs + ms
- [x] - Customizr Pro masonry with and without infinite
- [x] - Customizr Free and Pro on 4.8.3

FPU placeholders (fresh install) do not seem to be correctly centered on init ONLY when img smartload is disabled ....
