### ISSUE TITLE
Load mCustomScrollbar asynchronously

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1282]

**Comment by eri-trabiccolo** [comment]
ah you want to add mCustomScrollbar to 1-cs too, well yeah, would make sense.

**Comment by eri-trabiccolo** [comment]
jquery-magnific-popup
is another async candidate, need some small code changes I think, but can be done.
not sure if flickity too.

**Comment by ghost** [comment]
yes totally

**Comment by ghost** [comment]
flickity is could be, the idea would be to encapsulate the printing of the script in the current fire and include some sort of event emitter at the end of the  flickity js saying " hey I've been loaded, use me"

**Comment by eri-trabiccolo** [comment]
like ... https://davidwalsh.name/loading-scripts-jquery

**Comment by ghost** [comment]
yes ! perfect
