### ISSUE TITLE
SVG logo not displayed in modern style

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1283]
https://secure.helpscout.net/conversation/460703906/34034?folderId=607541

Flex system doesn't seem to be able to correctly size svg image (which have no width and height).
Even setting, the width and height attribute, the CSS rule "width: auto" (default for the logo image) makes the image to not show (occupies 0 pixels)

We need a solution.

Also the svgs (as img src) do not scale, at least in flexbox... :/
We really should not allow them.

**Comment by ghost** [comment]
OK.
Do you think there's a quick win solution allowing us to maintain the svg upload ?
Is there a solution available : https://css-tricks.com/snippets/wordpress/allow-svg-through-wordpress-media-uploader/

Or would it be safer to simply not allow theme anymore for now ?

**Comment by eri-trabiccolo** [comment]
Not sure what you mean with that link ... :/
We already use that filter.

The problem is not that users are not able to upload an svg, but that svgs and flexbox don't work fine together... 

Not allowing svg would be fine for me, but I don't know what will happen if a user already has an svg set as logo.

**Comment by giorgioriccardi** [comment]
We could point users to use their own snippet to support SVG... easier than dragging all the hassle of handling SVG support:
`function cc_mime_types($mimes) {
  $mimes['svg'] = 'image/svg+xml';
  return $mimes;
}
add_filter('upload_mimes', 'cc_mime_types');`

**Comment by giorgioriccardi** [comment]
dunno, maybe this tread helps... height in vh:
https://stackoverflow.com/questions/37242454/containing-a-svg-image-within-flexbox

**Comment by eri-trabiccolo** [comment]
looks like I'm now able to see svg logos at least with chrome and firefox (they must've implemented a solution)
