### ISSUE TITLE
Slider images not centered on firefox

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1284]
(hard refresh so to not use the cached images):
<img width="949" alt="ff-nocenter" src="https://user-images.githubusercontent.com/7689242/32384023-e8a45dd4-c0b9-11e7-90c4-1c9e1c78520e.png">

Firefox 56.0.2 (64-bit) on Windows

**Comment by eri-trabiccolo** [comment]
locally I can reproduce it with the slider smartload option on.
It doesn't happen with the first slide though (the active one), but all the others are not centered.
The centering for them should happen on:
1) smartload
2) select.flickity

## Let's start with 2)
the second one never happens because it's triggered on the flickity carousel, not on the image, nor the cell (and we listen to the cell).

## And now 1)
the first one happens on smartload as far as I can see, but the directions (top/left), at least, are wrong:
and the reason should be here -> 
https://github.com/presscustomizr/front-jquery-plugins/blob/master/jqueryimgSmartLoad.js#L188

This I think is a specific Firefox issue, the first time the img.load is executed if we analyze the width and the height of the image we get a square (the placeholder one?, though checking the src it correctly reports the correct one, mah). 
That's most likely why we accepted to trigger the smartload event more than once (I kinda remember something about this, we might have something in the github issues). 

So, ok, we should trigger the smartload event only once, but I'm not sure how to fix this. 
If it's a matter of standard delay, it's fine, we just need a delay before firing the event and the `data-tcjp-recalc-dims` thing (jetpack's photon compatibility, not sure if still needed).
But if this delay depends on the lazy loaded image size?! we cannot do that much...
Do we want to accept to fire the smartload event twice? Or even more?

**Comment by eri-trabiccolo** [comment]
Ah, I see, this issue happens (at least) when the responsive image option is enabled and there are responsive images for a given slide (or whatever image), that's why it doesn't happen locally on my first slide => it doesn't have a responsive image.
Anyway we need a fix :D

**Comment by ghost** [comment]
Thank you for pointing this + your analysis.
I have fixed the problem. the smartLoad plugin will again potentially trigger the smartload twice + better listening to select.flickity event
