### ISSUE TITLE
Why is "You may also like" not translated in French ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1294]
http://unenantaisedigitale.fr/vivre-centre-ville-inconvenients/

https://translate.wordpress.org/projects/wp-themes/customizr/fr/default?filters%5Bterm%5D=ALSO+LIKE&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by eri-trabiccolo** [comment]
I think because the french locale completion percentage is under the needed threshold (>90%?) to re-generate the locale lang pack.
I just switched locally to french, updated translations and can see that that string is not translated in my
wp-content/languages/themes/customizr-fr_FR.po

**Comment by ghost** [comment]
ah yeah that's why, my fault, I need to bring it back to 95%+
thanks !

**Comment by cjamin** [comment]
Could it be related to #1201?
