### ISSUE TITLE
Broken WooCommerce checkout page on Mobile device. TablePress conflict ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1298]
https://wordpress.org/support/topic/broken-order-review-on-mobile-device-2/#post-9681058

> I just made following 3 tabs to readable to everyone
> 
> In order to see what is going on with the cart section here is the Woocommerce/shop
> [Shop](https://www.cocwithsd.com/%EB%B6%80%EC%8A%A4%ED%8A%B8-%EC%97%85-%EA%B5%AC%EB%A7%A4/)
> 
> Woocomerce/cart
> [Cart](https://www.cocwithsd.com/%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88/)
> 
> And here is the TablePress plugin that I use
> [TablePress](https://www.cocwithsd.com/%EA%B3%B5%EA%B2%A9%EB%B2%88%ED%98%B8/)
> 
> Had to manually put some .css to work
> 
> .tablepress-id-8 .column-1 {
> 	width: 100px;
> }
> .tablepress-id-8 .column-2 {
> 	width: 120px;
> }
> .tablepress-id-8 .column-3 {
> 	width: 120px;
> }
> Here is the custom .css for customizr
> 
> .breadcrumbs {
> display: none;
> }
> .navbar-brand-sitename {
> display: none;
> }
> .entry-title {
> font-weight: bold !important;
> }
> I was not able to integrate with child theme. Therefore, I use regular functions.php at themes folder. Prevent automatic update and copy the list of hooks/filters/actions before I update.

**Comment by eri-trabiccolo** [comment]
I tested some stuff and found the culprit plugin:
https://wordpress.org/plugins/custom-registration-form-builder-with-submission-manager/


I tested it with classical style, hueman and twentyseventeen too.
Same result (twentyseventeen):
<img width="884" alt="broken-table" src="https://user-images.githubusercontent.com/7689242/32856893-72f59300-ca46-11e7-8bb9-9ad219166b81.png">

see removing that display:block:
<img width="841" alt="right-table" src="https://user-images.githubusercontent.com/7689242/32856913-7e13124e-ca46-11e7-9104-7bf1bf5a9a24.png">

I set this as invalid then, unless I'm missing something :)
