### ISSUE TITLE
CTA slider button => white-space: nowrap can hide long text

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1299]
@eri-trabiccolo was there a particular reason why we kept the` white-space: nowrap;` rule there ?

Reported by a user on facebook

> Bonjour, je voulais vous signaler que le texte du bouton (pour le slider de la page accueil) n'est pas responsive. Si vous pouviez faire quelque chose. Merci

**Comment by eri-trabiccolo** [comment]
Mmm not really on purpose I think. Most likely because bs did so for .btn

**Comment by ghost** [comment]
OK, yes thanks
