### ISSUE TITLE
WordPress gallery widget is broken

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1300]
![gallery_widget_broken](https://user-images.githubusercontent.com/3038156/32829501-8fda3a06-c9f2-11e7-8db8-f1dc36211eb1.png)

**Comment by eri-trabiccolo** [comment]
Yes I expected it...
Should only affect the modern... no?
But honestly I don't have a clear idea on how to fix this, unless there's a way to understand if we are in a sidebar or not.
They just did something wrong :(
