### ISSUE TITLE
Mobile menu: we should not display it if no menu && not search displayed in it

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1302]
Also:
https://github.com/presscustomizr/customizr/blob/dev/core/front/controllers/class-controller-header.php#L104

CZR_controller_header->czr_fn_display_view_mobile_search()

doesn't exist anymore, so if we select to not display any menu, that will trigger a fatal error.

I push a small fix for the latest, but fixing the "main" issue would require some time...

**Comment by ghost** [comment]
ok good catch thanks.
Merged
