### ISSUE TITLE
Related posts right after the content with two sidebars should have free height

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1304]
It's like this at the moment:
<img width="307" alt="wrong" src="https://user-images.githubusercontent.com/7689242/32849297-067fee94-ca2f-11e7-8a4c-c2e83b9a4cc7.png">

Should be like this:
<img width="333" alt="good" src="https://user-images.githubusercontent.com/7689242/32849303-0a3c2516-ca2f-11e7-9a20-810b7124c504.png">

The easiest way to achieve that is by scoping some CSS rules:
https://github.com/presscustomizr/customizr/blob/v4.0.12/assets/front/scss/0_4_layout/_grid.scss#L953
should be 
`#content:not(.col-md-6) & section.entry-content__holder`
as well as this
https://github.com/presscustomizr/customizr/blob/v4.0.12/assets/front/scss/0_4_layout/_grid.scss#L959
`#content:not(.col-md-6) &  .entry-content__wrapper `

**Comment by eri-trabiccolo** [comment]
My first way to scope the CSS rules was wrong because, of course, the rule `#content:not(.col-md-6) & section.entry-content__holder` would not apply to the related posts when outside the `#content` :D
Anyway, done.

**Comment by ghost** [comment]
ok. fine thanks
