### ISSUE TITLE
Feature request : Buddypress profile field display in two columns instead of just single column.

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1305]
> Dear Sir / Madam,
> 
> I have selected your theme for my social site, only one think is stopping me is that buddypress profile view.
> 
> Is it possible to change profile field display in two columns table just like twenty seventeen theme rather than just single column.
> 
> If this problem is resolve then I would like to go for your unlimited sites + lifetime update plan for customizr pro theme.
> 
> 
> Looking forward to hear from your prompt response is highly appreciated.
> 
> 
> Thanks & Best Regards,
> 
> Devendra

**Comment by eri-trabiccolo** [comment]
For what I can see, if the user is talking about something like this (when referring to the two columns display in twentyseventeen):
<img width="498" alt="bpress" src="https://user-images.githubusercontent.com/7689242/32883678-4c799bd2-cab8-11e7-89f5-80b451ccb46e.png">

That is true only when in twentyseventeen the pages (all the pages) layout is set to 1 column (no sidebars).
We can do it, using exactly the same principle.

Note: always consider that when it's about the default wp themes, plugins like woocommerce  and buddypress (etc.) embed specif styles/templates for them
