### ISSUE TITLE
Comment form location => new option to change the location ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1306]
> Can you confirm that the comment form is still not directly after content when using modern style ? I mean that the comment form is at the bottom of the pages after ALL comments. This is what I had seen, but since, I haven’t tried again.

**Comment by eri-trabiccolo** [comment]
what do you mean?
In 1-cs it is (and has always been so)
in 2-ms it's not the default for old users.

Do you mean as first element before author or related posts?

**Comment by eri-trabiccolo** [comment]
Comment form should be always displayed before the list of comments.
