### ISSUE TITLE
Gallery compat with jetpack ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1307]
> Hi, I'm using Customizr on portraitsbyrachel.com and had used it previously for my website with NO issues. Currently it appears photo galleries don't operate correctly with WordPress Jet Pack (unless I switch to classic but that doesn't help my next, bigger problem either). My site also won't render properly on mobile- It looks like a pile of junk on iPhone. Go try it. What gives? I loved this theme and don't want to have to switch, but it no longer works properly.

**Comment by eri-trabiccolo** [comment]
I will look for the jetpack compatibility, but anyways the Customizr
gallery can be disabled with the proper option.
In mobiles, as of now, the user doesn't use the Customizr theme but the
jetpack's mobile theme.

So one of the two is not an issue, the other is something the user should be able to avoid disabling the theme's gallery.

Il 16 nov 2017 10:23 PM, "Nicolas Guillaume (@nikeo on wp.org)" <
notifications@github.com> ha scritto:

**Comment by ghost** [comment]
Following up with the bug report

> My bigger problem is my site is NOT mobile responsive with Customizr. PLEASE solve or I'm done with it today. I was considering upgrading to Pro, but not until I see this ongoing issue solved. Clients are complaining there's nothing on my site because it just looks like a crappy wordpress site.
> 
> Jet pack issue- I use a mosaic gallery which is choppy if I don't select the classic version.
> 
> This whole site used to work lovely and looked lovely and I'm super disappointed it's gone to crap.
