### ISSUE TITLE
Errors when activating the theme

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1308]
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1322
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1322
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1322
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1322
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1322
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1322
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1322
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1322
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1322
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1322
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1322
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1322
> 
> Warning: array_merge(): Argument #5 is not an array in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1159
> 
> Warning: array_diff(): Argument #2 is not an array in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1160
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1162
> 
> Warning: array_merge(): Argument #1 is not an array in /srv/www/customizr-dev/htdocs/wp-includes/widgets.php on line 1170

![2017-11-20_13-37-39](https://user-images.githubusercontent.com/3038156/33018860-58f92c4a-cdf8-11e7-963d-71dafd87d85f.png)
![2017-11-20_13-38-18](https://user-images.githubusercontent.com/3038156/33018861-5911c908-cdf8-11e7-99e3-3415bfa8a3b0.png)

**Comment by ghost** [comment]
@eri-trabiccolo could you please let me know if you can reproduce the problem. And if it occurs only with our themes ? Thx
( when you get the chance, no hurry )

**Comment by eri-trabiccolo** [comment]
I cannot reproduce it actually.
:/

**Comment by ghost** [comment]
OK that's actually not a bad news. There must be something wrong on my local install then.

**Comment by eri-trabiccolo** [comment]
Let's hope! :)

Il 20 nov 2017 5:02 PM, "Nicolas Guillaume (@nikeo on wp.org)" <
notifications@github.com> ha scritto:

**Comment by eri-trabiccolo** [comment]
Should be this WP bug now fixed in WP 4.9.2
https://core.trac.wordpress.org/ticket/42603
