### ISSUE TITLE
CSS issue - text-transform applied on category widget title when used in footer

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1309]
Hi @Nikeo 

This happens in Modern style.
When a category widget is deployed in footer widget area, the category widget title gets text-transformed to upper-case.

This does not happen to Recent posts widget and Recent comments widget, therefore I assume it's a css bug.

This issue is reported by customer on helpscout.
https://secure.helpscout.net/conversation/471844718/34630?folderId=607541#thread-1281120548

Thank you
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks Denzel.
PR pushed ;)

**Comment by FabriceAllard** [comment]
Hello guys,

I've reported this bug in the product support yesterday evening and I'm wanted to thank you all for your quick reply and fix.
I really appreciate your work and therefore I'm happy to have invested in this plugin.

All the best,
Fabrice

**Comment by denzelchia** [comment]
Hi @FabriceAllard

Thank you! I glad to be of some help.

A big thank you to @eri-trabiccolo too! :)
