### ISSUE TITLE
[ Customizr Pro Theme ] Featured pages layout option disappears after making selection

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1311]
Hi @Nikeo 

I stumbled upon this during answering a support question regarding featured pages in Customizr Pro Theme.

In Appearance -> Customize -> Main Content -> Featured Pages
The option -> Featured pages layout, will disappear after you make a selection.

It will appear after you publish changes, get out of customizer and then re-visit the option in customizer.

Please see my screen-cast.
http://screencast-o-matic.com/watch/cbXrf32T6u

Thank you

**Comment by ghost** [comment]
OK thanks for reporting the problem @denzelchia !

**Comment by eri-trabiccolo** [comment]
weird that it doesn't happen when you set 4 fps per row...

**Comment by eri-trabiccolo** [comment]
Well, not that weird if we consider this:
https://github.com/presscustomizr/tc-unlimited-featured-pages/blob/dev/back/assets/js/fpu-customizer-control.js#L70

```
  settingMap[OptionPrefix + "[tc_fp_number_per_line]"] = {
      controls: FPbyline,
      callback: function( to ) { return 'four' == to; }
  };
```

mah :)

**Comment by eri-trabiccolo** [comment]
I close this here as it pertains to fpu:
https://github.com/presscustomizr/tc-unlimited-featured-pages/issues/107

Thanks Denzel!
