### ISSUE TITLE
[mixed content issue] use relative URL

### ISSUE THREAD

**Issue by PeopleInside** [Nikeo/customizr#1313]
Hi,
I have a Wordpress website that is not HTTP but is HTTPS on login page and also if HTTPS is not forced the website can be loaded from HTTP or HTTPS.

Image logo etc loaded by the theme can be with relative URL? So will load image under HTTP if the website is HTTP and under HTTPS if the website is under HTTPS.

**Comment by eri-trabiccolo** [comment]
Hi Marco,
the support team handles the support on the wp.org forum.
As general rule would you mind opening a topic there?

About your issue, anyway, I'm not sure it's theme related.
The theme always loads the logo in the header with the correct protocol as far as I can see.
Are we talking about that?

If you're talking about a logo in the login page, well ... the theme doesn't handle the login page logo at all so, in that case, the issue would be not theme related.

**Comment by PeopleInside** [comment]
Hi @eri-trabiccolo,

> About your issue, anyway, I'm not sure it's theme related.
> The theme always loads the logo in the header with the correct protocol as far as I can see.
> Are we talking about that?

> The theme always loads the logo in the header with the correct protocol as far as I can see.
Yes, how you can know that?

I tested now and seems the two logo icon that I set on Customizr are loaded as http under https administration page.

In the visitor side seems you are correct.

**Comment by eri-trabiccolo** [comment]
Do you mean in Appearance -> Customize?

**Comment by PeopleInside** [comment]
When I AM on the admin area I see warning mixed content so I check with Firefox and the http file are the logo icon that is used by the theme Customizr

**Comment by PeopleInside** [comment]
In any case this issue I AM not sure if can be or not from the theme and can be resolved with .htaccess rule so I will close this.

In a website where always https is forced the issue is not present only if visitor side site support http and https and https is forced on admin side.
