### ISSUE TITLE
Maybe open submenus on the left by default when primary horizontal menu aligned to the right?

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1326]
https://secure.helpscout.net/conversation/478440896/35082?folderId=607541

**Comment by eri-trabiccolo** [comment]
Additionally: do we want to exclude the first level menu items arrow flip? Doesn't seem to have very sense actually to have this flip there as the dropdown, whether it opens on the right or on the left, will still be placed right below the menu item.

**Comment by eri-trabiccolo** [comment]
about the comment above, what do you think about this @Nikeo 
https://github.com/presscustomizr/customizr-front-js-parts/pull/26
to me is better...

**Comment by ghost** [comment]
yep let's go this way
