### ISSUE TITLE
Conflict with plugin : All In One Schema Rich Snippets

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1327]
https://secure.helpscout.net/conversation/479177199/35126?folderId=607541
> When I active it, all the widgets located in the right bar change their position and are automatically located under the main body of a page or post.
> 
> I attach a list of the installed plugins, my question is about
> ​ this matter, maybe you ​detected some kind of conflict between then or with Customizr

**Comment by eri-trabiccolo** [comment]
Actually I've been not able to reproduce the issue with that plugin only.
The issue might be due to another plugin then...

**Comment by ghost** [comment]
OK let's close it for now then
