### ISSUE TITLE
retina.js: Browser warns that getAttributeNode() is deprecated

### ISSUE THREAD

**Issue by ElectricFeet** [Nikeo/customizr#1328]
Hi there,
I'm getting a browser warning (FF 57.0 / MacOS 10.13.1):

> Use of getAttributeNode() is deprecated. Use getAttribute() instead.

retina.js seems to be the culprit.

**Comment by ElectricFeet** [comment]
And https://github.com/strues/retinajs doesn't use `getAttributeNode()` any more, so maybe it's just a simple(ha!) matter of updating retina.js.

**Comment by eri-trabiccolo** [comment]
Thanks @ElectricFeet 
glad to see you :D 

TODO:
Update retina.js

**Comment by ElectricFeet** [comment]
You too! :))
