### ISSUE TITLE
Problem with Customizr Modern when sending a form with Contact Form 7 ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1330]
# THEME | VERSION : customizr | v4.0.13# WP VERSION : 4.9.1

- Contact Form 7: 4.9.2
- Contact Form 7 Conditional Fields: 1.3.4
- Contact Form 7 Signature Addon: 4.2
- Contact Form 7 Style: 3.1.6

> Hello,
> I have a problem with your Customizr theme (Modern version). I use it on many of my sites and I have the same problem with each of them: the Contact Form 7 extension seems to work badly with your theme. Indeed, I do not have this problem on my sites working with other themes and disable all other plugin does not change anything.
> 
> Here are the symptoms: When I use my contact form, at the click of the "Send" button, the treatment indicator runs in a vacuum and no information message is displayed (message sent, error in the form, impossible to send the mail ...). However, I receive the mail, and the information I enter is stored correctly in my database.
> 
> When I look in the console, it seems that my request AJAX returns a 404 error. Would not there be a problem of javascript not loaded in the page? If so, how can I solve that? A function to add in the header of your theme?

https://secure.helpscout.net/conversation/484872674/35406?folderId=610151

**Comment by ghost** [comment]
@eri-trabiccolo can you take a look on your side when you get the chance ?
thanks

**Comment by eri-trabiccolo** [comment]
Yeah sure, I will.

Il 12 dic 2017 12:34 PM, "Nicolas Guillaume (@nikeo on wp.org)" <
notifications@github.com> ha scritto:

**Comment by eri-trabiccolo** [comment]
So I made some tests with the above plugins installed and applied to my contact form. I couldn't reproduce the issue on my end. The conflict might be with some other plugin then.
p.s. I cannot access the hs ticket.

**Comment by ghost** [comment]
Ah  yes, this issue was send on the contact form, that's why you can't access it.

Thanks for your tests.
