### ISSUE TITLE
Desktop submenu snake : when parent item is the last of a column, its child submenu block can be difficult to access

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1333]
http://www.ipnetsolusindo.com/

Steps to reproduce on http://www.ipnetsolusindo.com/ and following screenshot below

1. Hover on Services menu item in the orange box
2. Hover on Service Provider Solution in the violet box
3. Try to access the red block => difficult, it's easy to lose everything

=> The red child block should be pulled up.

![menu_problem](https://user-images.githubusercontent.com/3038156/34146369-03272412-e49a-11e7-8a0e-9ef3dc86de60.png)

**Comment by eri-trabiccolo** [comment]
Not sure I get, you mean that the submenu "top" at the middle of the parent menu item makes it hard to be accessed?
Maybe a top of 10px instead of 55% would be better.

**Comment by ghost** [comment]
I've updated the description.
To be discussed during our point anyway

**Comment by eri-trabiccolo** [comment]
Ah ok, yes, so I got, and I agree.
Should be pulled up, I think a top of 10px is fine. Consider that in the first design draft that top was 100% :|
