### ISSUE TITLE
Vertical menu drodown => mobile => the nav height should adapt to expanded submenus.

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1334]
![submenus](https://user-images.githubusercontent.com/3038156/34200282-c2e0796c-e570-11e7-9762-351e28c711c7.gif)

**Comment by eri-trabiccolo** [comment]
Nico I'm not able to reproduce this issue, neither the one with the sidenav. I tried with 7 levels.
Can you still reproduce it?

**Comment by ghost** [comment]
No I can't reproduce it anymore.
It was related to the customScrollBar bug before I did the last build I think.
All good sorry for the wrong alert !

**Comment by eri-trabiccolo** [comment]
Oh, no problem.

Good it's sorted!
