### ISSUE TITLE
Side menu : font too big +  word-break: break-all might not be the best solution

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1339]
https://demo.presscustomizr.com/
![2017-12-20_21-38-17](https://user-images.githubusercontent.com/3038156/34227730-77918484-e5ce-11e7-90df-c74242f4d814.png)

**Comment by eri-trabiccolo** [comment]
break-word would be better maybe, because we still have to handle edge cases.
Unless we want to apply some sort of "fittext" (per menu-item?) we cannot cover everything.
A fine tuning in CSS, case by case, is needed. This is where WFC can help.
IMHO
