### ISSUE TITLE
Problem with structured data ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1344]
> i have problem with structured data , so many error missing author and missing update. How to fix that ?
https://www.idblog.net/

**Comment by eemlandict** [comment]
me too on the pages :(

**Comment by joshin16** [comment]
I have nearly 1560 structured data issue for my blog https://web3mantra.com please help how to resolve it.

**Comment by eri-trabiccolo** [comment]
Hi there.
This theme fixed that issue.
Your website doesn't seem to run this theme
