### ISSUE TITLE
[ Customizr Pro 2.0.20 ] Headers already output error in WordPress admin

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1346]
Hi @Nikeo and @eri-trabiccolo 

Following errors appearance in WordPress admin after updating to 2.0.20, with WP_DEBUG turn on.

<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/customizr-pro-modern/wp-content/themes/customizr-pro/addons/wfc/back/classes/class_admin_font_customizer.php:2) in <b>/Applications/MAMP/htdocs/customizr-pro-modern/wp-admin/includes/misc.php</b> on line <b>1114</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/customizr-pro-modern/wp-content/themes/customizr-pro/addons/wfc/back/classes/class_admin_font_customizer.php:2) in <b>/Applications/MAMP/htdocs/customizr-pro-modern/wp-includes/option.php</b> on line <b>919</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/customizr-pro-modern/wp-content/themes/customizr-pro/addons/wfc/back/classes/class_admin_font_customizer.php:2) in <b>/Applications/MAMP/htdocs/customizr-pro-modern/wp-includes/option.php</b> on line <b>920</b><br />

If logged out and accessing http://localhost/customizr-pro-modern/wp-admin/
You will get the following error

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/customizr-pro-modern/wp-content/themes/customizr-pro/addons/wfc/back/classes/class_admin_font_customizer.php:2) in /Applications/MAMP/htdocs/customizr-pro-modern/wp-includes/pluggable.php on line 1216

If WP_DEBUG is turn off, you will get a blank page when accessing http://localhost/customizr-pro-modern/wp-admin/ , but fortunately login can still be access at http://localhost/customizr-pro-modern/wp-login.php

Nevertheless, I still think this is a serious issue and needs immediate attention.

Thank you

**Comment by denzelchia** [comment]
Hi,

Customers are starting to report this issue on helpscout
https://secure.helpscout.net/conversation/494007651/35894/?folderId=631714#thread-1339777160

Thank you

**Comment by denzelchia** [comment]
Hi,

Update to my findings.
This issue is affecting the following features in WordPress admin.

1) Unable to edit or create new post or page.
2) Media library does not load images.

Thank you

**Comment by eri-trabiccolo** [comment]
Hi @denzelchia thanks!
@nikeo https://github.com/presscustomizr/wordpress-font-customizer/blob/916acd007c995f3149126c3400b4892361cf4749/back/classes/class_admin_font_customizer.php#L1
(Unwanted blank line).
This kind of error anyways doesn't happen to all users (e.g. doesn't happen here, I have to force PHP to report this error)

**Comment by ghost** [comment]
@denzelchia @eri-trabiccolo thanks
I'm on it. building a new version after fixing the blank line problem.

**Comment by denzelchia** [comment]
Hi @Nikeo ,

Thank you.
No more headers already sent error in v 2.0.21

Thank you

**Comment by eri-trabiccolo** [comment]
Thank you Denzel!
