### ISSUE TITLE
[ Customizr Pro 2.0.20 ] Customizer error message when publishing

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1347]
Hi @Nikeo and @eri-trabiccolo 

In Customizer the following message will appearance when you click on Publish.

> Looks like something’s gone wrong. Wait a couple seconds, and then try again.

Please see my screen-cast
https://screencast-o-matic.com/watch/cbltVP2RkE

I have clear browser history and no plugins activated when doing this screen-cast.

This issue also needs immediate attention.

Thank you

**Comment by ghost** [comment]
@eri-trabiccolo are you able to reproduce the described issue in [v2.0.21](https://github.com/presscustomizr/customizr-pro/releases/tag/v2.0.21) ?

**Comment by eri-trabiccolo** [comment]
The headers already sent?
https://github.com/presscustomizr/customizr/issues/1348#issuecomment-354075105

For this specific issue reported by Denzel here, nope, I guess is still related to the headers already sent issue...

**Comment by ghost** [comment]
hopefully yes it should be related to this issue, but I wanted to have another feedback

**Comment by ghost** [comment]
let's say normally instead of hoppefully

**Comment by denzelchia** [comment]
Hi @Nikeo ,

Customizer saving properly now.
I am not seeing the error message in v 2.0.21

Thank you

**Comment by eri-trabiccolo** [comment]
Hi @denzelchia thanks for the feedback!
