### ISSUE TITLE
Test process : always make sure we don't miss before build "Warning: Cannot modify header information - headers already sent by"

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1348]
To be discussed @eri-trabiccolo during our next point 
Thx
https://github.com/presscustomizr/customizr/issues/1346

**Comment by eri-trabiccolo** [comment]
The only way I have to "catch" it at the moment is by disabling the output buffering in php.ini
`output_buffering: Off`

will see if I can find something else
