### ISSUE TITLE
[ Customizr Pro ] Font Customizer Menu Items 

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1349]
Hi @Nikeo and @eri-trabiccolo 

In Customizr Pro, modern style.
The menu items style in font customizer does not apply to menu items with sub-menu, if the option Expand submenus on click is selected.

For example, to replicate issue.
Go to Appearance -> Customize -> Header Design settings for smartphones and tablets
Find the setting -> Expand submenus on click
Check this option and save changes.

Next go to Appearance -> Font Customizer -> Menu items
Select a font family and save changes.

In browser developer tool load the responsive mode on front-end and view site in mobile,
You will see the font family does not apply to menu items with sub-menu.

With reference to the following screen-shot, the font family does not apply to Home and Contact

![screen shot 2017-12-28 at 11 10 05 am](https://user-images.githubusercontent.com/9284811/34399275-cdd38782-ebc0-11e7-989c-2c311b4b3082.png)

This issue is reported by customer on helpscout.
https://secure.helpscout.net/conversation/493301773/35859?folderId=607544

Thank you

**Comment by eri-trabiccolo** [comment]
Hi Denzel,
you're right, thanks for reporting this!
I move this in the WFC repo.
