### ISSUE TITLE
Woocommerce template issue?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1352]
> I use the free version of Customizr. I really like your theme, but recently it stopped working properly with Woocommerce. The add to cart buttons only work from product pages and not the shop page or any other page. It does not seem to be a plugin issue, and they work fine if I change to another theme. Not sure if other people are having this issue, so I thought I'd bring it to your attention. In the meantime, I guess I'll have to use another theme. :(
> 
> I am using Chrome on my Asus laptop.
> 
> Using Wordpress 4.9.1 with Customizr 4.1.14 and Woocommerce 3.2.6

**Comment by eri-trabiccolo** [comment]
Might be an ajax add to cart issue (in single products WC doesn't use ajax when clicking on the add to cart button).
Anyway I cannot reproduce the issue here (not in the demo). Do we have the user website?

**Comment by eri-trabiccolo** [comment]
see https://github.com/presscustomizr/customizr/issues/1155
