### ISSUE TITLE
elementor issue with page attributes

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1353]
> hi all,
> 
> I would like to purchase the PRO template but... I would like to be sure that the PRO CUSTOMIZR template is compatible 100% with Elementor https://elementor.com/
> 
> I explain the doubt:
> 
> currently I created all pages, articles, etc with customizr (free version) with page builder Elementor (pro version). I have experienced that when I select in the page attributes drop-down manu the Elementor canvas, your template (free version) cut-off some images. I made some test with other templates and the problem does't exist.
> 
> Please cloud you let me know why and if I solve the issue purchasing the pro-version of your customizr?
> 
> regards
> 
> GMA

**Comment by eri-trabiccolo** [comment]
Mmm,
not sure how to reproduce this.
Any tip would be very welcome.
