### ISSUE TITLE
Bulleted list in WooCommerce product description is missing list style type

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1354]
Hi @Nikeo and @eri-trabiccolo 

Customer reported this issue on helpscout.
https://secure.helpscout.net/conversation/496922658/36094?folderId=631714#thread-1348070402

I am able to replicate this issue on my test site.

On my test site, I am using Customizr Pro Theme Modern style and WooCommerce plugin.
In the WooCommerce product description, I have created a bulleted list and it's missing the bullets on front-end.

Please see my screen-cast.
https://screencast-o-matic.com/watch/cFVen1onue

Have a nice day,

Best regards,
Denzel

**Comment by eri-trabiccolo** [comment]
Hi @denzelchia 
thanks for reporting this.

Will push a PR soon
