### ISSUE TITLE
Issue with Ninja form ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1362]
https://secure.helpscout.net/conversation/500594090/36304/?folderId=607541

> Sorry, the issue is fixed.
> 
> It was a plugin called 'ninja forms' that caused the issues. I disabled it and everything appears to be good now. I am not sure where I got the plugin….. You might want to make note that it causes conflicts.

Earlier ...
> I'm missing most of my pro menus. I only figured that out when clicking the edit featured pages button, it's the only way I get to my missing menus. When I try to make changes to the featured pages it will not save, gives error "there must be a problem......". I cannot figure out how to reinstall the theme and I cannot find how to redownload the zip file! Also, the help files for editing the features pages do not match what I have, I assume it's because I have a bad install.
> 
> It appears you guys put a bunch a work into your free copy (which works perfect) and neglected the Pro copy, which I was suckered into purchasing! On top of all of this, considering I purchase the unlimited license, where the f... is the support phone number!!! This rant will soon become a glaring feedback on google.....

**Comment by ghost** [comment]
> It's Ninja Forms 3.2.8

**Comment by ghost** [comment]
@eri-trabiccolo I place this one before the start ot FA upgrade in https://github.com/orgs/presscustomizr/projects/2
This is the first time this is reported, but Ninja form is used by 1m+ users so... let's see.
thx

**Comment by eri-trabiccolo** [comment]
Hi Nico,
cannot recreate this issue on my end.
Did you?

**Comment by ghost** [comment]
nope I did not try yet
