### ISSUE TITLE
Animated underline not removable in some navigation menus

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1363]
When unchecking the option "Animated underline effect on link hover" in _global settings > Formatting, links_, the animated underline is still visible when hovering the menu item ( or when  displaying the item context ) in :
- side menu
- mobile menu

https://secure.helpscout.net/conversation/500270930/36278?folderId=607547

![sans titre](https://user-images.githubusercontent.com/3038156/34662281-ba52e94a-f44f-11e7-9220-815e73988c05.png)

**Comment by eri-trabiccolo** [comment]
It happens only with menu items with children in vertical menus, right?

I would also say that also the current menu items, when that option is disabled, should not be underlined at all. What do you think @Nikeo?

**Comment by ghost** [comment]
> I would also say that also the current menu items, when that option is disabled, should not be underlined at all. What do you think @Nikeo? 
👍 

Yes => no underline when the option is disabled. This includes when hovering, current menu item, current parent menu item (if the case ), etc...

**Comment by ghost** [comment]
> It happens only with menu items with children in vertical menus, right?

From what I could test yes, but you'll need to test more _edge_ cases in the horizontal menus I think

**Comment by ghost** [comment]
@eri-trabiccolo this issue is becoming the most urgent in our scheduled dev. see https://github.com/orgs/presscustomizr/projects/2#card-6527768

**Comment by eri-trabiccolo** [comment]
horizontals are fine

yeah I saw it was the most urgent

**Comment by ghost** [comment]
thanks 👍

**Comment by ghost** [comment]
Hope you had a nice week end by the way !

**Comment by eri-trabiccolo** [comment]
Yeah, I had a nice one (ate a lot :P)
