### ISSUE TITLE
Footer : style of widgets zone and colophon could be differentiated when selecting dark or light.

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1368]
as requested here : https://secure.helpscout.net/conversation/500718661/36316?folderId=607541

> It's me again! I am using the Pro version, with the modern theme.
> 
> I am putting the final touches on a client's landing page, and I have read articles and checked out the forum, yet still remain stumped.
> 
> **I would like to change the background color of the "credits" footer (other than light or dark). My attempts to do so with CSS have failed, though I did manage to change the font color and the top border.** Suggestions? Also, can I add a text widget inside there, to the left of the social icon bar to include my client's contact information. Many thanks in advance,
> 
> Dave

And colophon could even have custom color option.

**Comment by eri-trabiccolo** [comment]
related to this?
https://github.com/presscustomizr/customizr/issues/1332

**Comment by ghost** [comment]
Yep, those are connected.
But the custom color might be more complex to implement for the widget zones.
To be discussed. As soon as the current priorities are addressed.
In connection with #1369 too.
