### ISSUE TITLE
Footer : add a widget zone before the footer, not styled like the footer => white background

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1369]
It could be used to display bottom contact informations for example. Of anything a user want to add there.

Requested here  ( not exactly this way but still, same concept ) https://secure.helpscout.net/conversation/500718661/36316?folderId=607541
> I would like to change the background color of the "credits" footer (other than light or dark). My attempts to do so with CSS have failed, though I did manage to change the font color and the top border. Suggestions?
 **Also, can I add a text widget inside there, to the left of the social icon bar to include my client's contact information. Many thanks in advance,**

connected to https://github.com/presscustomizr/pro-bundle/issues/121

**Comment by ghost** [comment]
to be approached globally with 

- #1332
- https://github.com/presscustomizr/pro-bundle/issues/121
- #1368

**Comment by ghost** [comment]
- before the footer
- not styled
- with an option to make it full width
- customizer => "Horizontal widget area in your footer", a select control in footer > Footer global settings with 3 options : don't display, display full width, display boxed

**Comment by eri-trabiccolo** [comment]
So I added this, displayed and in full-width by default
I added also the front placeholder and the customizer placeholder.
I'm not sure about:
1) having the front placeholder - even if for old users might be a way to inform about this new area
2) having this area outside the footer (meaning that it won't inherit the background for instance...)
