### ISSUE TITLE
Mobile hamburger menu gets expanded then collapse automatically

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1373]
The bug can be easily reproduced on https://cb-electronics.com with chrome

> For the website design on mobile phones, the menu button (The three lines) when pressed, the menu doesn't appear, and it gives the sign of X instead the three lines.
> 
> Device that we tried it on: iPhone 5S - iPhone 6S+ and iPhone 7
> 
> Browser: SAFARI

> SITE_URL: https://cb-electronics.com
> HOME_URL: https://cb-electronics.com
> IS MULTISITE : No
> 
> THEME | VERSION : customizr | v4.0.14# WP VERSION : 4.9.1
> PERMALINK STRUCTURE : /%postname%/
> 
> ACTIVE PLUGINS :
> Contact Widgets: 1.4.1
> Custom Product Tabs for WooCommerce: 1.6.3
> Download Manager: 2.9.61
> GoDaddy Email Marketing: 1.2.0
> Limit Login Attempts: 1.7.1
> TablePress: 1.9
> WooCommerce: 3.2.6
> 
> PHP Version: 7.1.7
> MySQL Version: 5.6.36-cll-lve
> Web Server Info: Apache
> 
> WordPress Memory Limit: 40MB
> PHP Memory Limit: 256M
> PHP Upload Max Size: 2M
> PHP Post Max Size: 8M
> PHP Upload Max Filesize: 2M
> PHP Time Limit: 30
> PHP Max Input Vars: 1000
> PHP Arg Separator: &
> PHP Allow URL File Open: Yes
> WP_DEBUG: Disabled
> 
> Show On Front: nothing
> Page On Front: (#0)
> Page For Posts: (#0)

**Comment by ghost** [comment]
@eri-trabiccolo can you investigate it in priority during your next work session ?
thx!

**Comment by ghost** [comment]
I've asked the user to test without plugins. ( table press might be conflicting ). I'll update the issue once he replies.

**Comment by eri-trabiccolo** [comment]
Download manager uses bootstrap3 : collapse conflict.
We should use a custom code

Il 10 gen 2018 9:39 PM, "Nicolas Guillaume (@nikeo on wp.org)" <
notifications@github.com> ha scritto:

**Comment by eri-trabiccolo** [comment]
see https://github.com/presscustomizr/customizr/issues/1144

**Comment by ghost** [comment]
update

> Hello Nicolas,
> Here's what I did. I deactivated each plugin alone and tested the site.
> It worked when I deactivated the "Download Manager" Plugin, (Some details: Version 2.9.61 | By Shaon | View details)
> What do you suggest to do? This plugin is important to the website and we already uploaded many files using it.

@eri-trabiccolo I guess Download Manager is not the only plugin using an old version of bootstrap. Can we try to implement the simple compatibility fix detailed here #1144.

Ideally, I would prefer to have a pure js solution, in which we restrict the addition of this css rule(s) to the cases where b3 is used. The solution to implement would be something like 

1. we detect if bootstrap 3 js is also running, check if a b3 function exists for example
2. we inject a compatibility stylesheet if needed

for the moment the stylesheet would simply include this rule
```
.collapse.in {
    display: block;
}
```

This code would be located in `assets\front\js\_parts\_parts_modern\_main_userxp_9_various.part.js` and fired here `assets\front\js\_parts\_parts_modern\_z_main_xfire_modern_theme_specific.part.js`

This is urgent. I add this one before the font awesome update. ( again ... )

**Comment by ghost** [comment]
Another issue that might be related to bootstrap conflict, reported by the same user

> My friend, when you **click on the search bar** in the PC version, you have to re-click in the field to be able to write. 
> 
> Will this be automatic (Once I click on search icon, I will be able to start writing without having to re-click in the field) in the pro version?

**Comment by eri-trabiccolo** [comment]
Hi Nico,
yeah all the plugins using a non prefixed bootstrap js/css might conflict with the hamburger.
I would rather go with a "copy" of the collapse but using custom namespace for now. (in the future we should prefix also columns/container/rows CSS classes etc.)

About the search in desktop.
Not a conflict as far as I can see.
It just doesn't focus the search form input when clicking on the search icon in desktop.

**Comment by eri-trabiccolo** [comment]
Did it in local.
Gotta go, will run some more tests tomorrow and will push the multi-repo PR.

Talk you soon ;)

**Comment by eri-trabiccolo** [comment]
fixed in:
this repo: https://github.com/presscustomizr/customizr/pull/1377
front js parts: https://github.com/presscustomizr/customizr-front-js-parts/pull/28

(tested with download manager that I tested it conflicts without applying those PR)
