### ISSUE TITLE
Search form focus

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1374]
> My friend, when you click on the search bar in the PC version, you have to re-click in the field to be able to write.
> 
> Will this be automatic (Once I click on search icon, I will be able to start writing without having to re-click in the field) in the pro version?

@eri-trabiccolo said

> About the search in desktop.
> Not a conflict as far as I can see.
> It just doesn't focus the search form input when clicking on the search icon in desktop.

**Comment by ghost** [comment]
@eri-trabiccolo  I'm now quoting you man !

**Comment by eri-trabiccolo** [comment]
I will write it in my Bio :P

**Comment by ghost** [comment]
I should add it too :P :P

**Comment by eri-trabiccolo** [comment]
should this be done before fa or not?!

**Comment by ghost** [comment]
ah not. I just updated the column https://github.com/orgs/presscustomizr/projects/2

**Comment by eri-trabiccolo** [comment]
Ok, thanks Nico.
I'm on the fa upgrade then, as its previous task have a PR pushed except for the Ninja form issue that I cannot actually recreate, though I will give it another try.

**Comment by ghost** [comment]
OK.
Leave the Ninja form investigation, and the search form focus  aside for the moment.
For the today's release the remaining part is Font Awesome + usual tests.

**Comment by eri-trabiccolo** [comment]
Fixed in https://github.com/presscustomizr/customizr-front-js-parts/pull/30
