### ISSUE TITLE
old slider fading transition question

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1376]
> I LOVE the customizr theme! I am using the classical style - and I have two questions. 1. How can I get the mobile version of the menu to support collapsible sub-menus? The second question is if I have to use the modern style instead of the classical for that feature, how can I get the slider to fade instead of "slide?"

https://secure.helpscout.net/conversation/503676122/36499?folderId=607544

**Comment by eri-trabiccolo** [comment]
About 2.
As far as I know flickity itself doesn't support fade. The author said it was outside the flickity set because of the physics hard coded in flickity. Though probably he will change is mind.
There CSS hacks here:
https://github.com/metafizzy/flickity/issues/26

About 1.
really? :D

**Comment by ghost** [comment]
issue will be followed up in #1428
