### ISSUE TITLE
The retina php code creates also unwanted (and broken) PDF files retina versions

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1387]
If you upload A.pdf, it creates 'retina' versions like:
A-{thumb-size}@2x.pdf
A-{thumb-size-2}@2x.pdf
A-{thumb-size-3}@2x.pdf

Consider that WP since 4.7 creates images and thumbs from the pdf like:
A-pdf.jpg
A-pdf-{thumb-size}.jpg
A-pdf-{thumb-size-2}.jpg
A-pdf-{thumb-size-3}.jpg

So we should rather have something like:
A-pdf@2x.jpg
A-pdf-{thumb-size}@2x.jpg
A-pdf-{thumb-size-2}@2x.jpg
A-pdf-{thumb-size-3}@2x.jpg

https://secure.helpscout.net/conversation/505992657/36606?folderId=607709

**Comment by ghost** [comment]
ok.
