### ISSUE TITLE
Lightbox doesn't work for images in the WooCommerce description/short description

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1394]
1) when in the description tab, the link wrapping the image (link to the media file) doesn't match the delegated element's selector we use here:
https://github.com/presscustomizr/customizr-front-js-parts/blob/04569189946e45b1b34ef5e499280ce912397308/_parts_modern/_main_jquery_plugins.part.js#L348
(this happens only for the Modern style) 

2) when in the short description:
- the php parsing doesn't occur (as the wc short description, I guess, doesn't apply the the_content filter - same for the Classical style too )
- even if the php parsing occurred, the js part wouldn't match the link as in 1)

1) reported here https://secure.helpscout.net/conversation/507324491/36668?folderId=607709

**Comment by ghost** [comment]
How do you feel about fixing this ?

**Comment by eri-trabiccolo** [comment]
1) is fast, minor js change
2) I have to look for the wc filter, shouldn't be long, assuming we want it :D

**Comment by ghost** [comment]
OK I've placed this one and #1393 WooCommerce related before hueman FA5 upgrade then

**Comment by eri-trabiccolo** [comment]
customizr part in: https://github.com/presscustomizr/customizr/pull/1395
customizr-front-js part in: https://github.com/presscustomizr/customizr-front-js-parts/pull/31
