### ISSUE TITLE
When the logo/title is centered the header takes too much stick (trigger point) 

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1396]
That's even when the behavior on scroll is set as **Always visible**
http://www.von-kronberg.com/www

or at least we should change the wording "Always visible" as it might mislead

**Comment by ghost** [comment]
Let me know if you're ok to fix this

**Comment by eri-trabiccolo** [comment]
I think this h*2 is too high:
https://github.com/presscustomizr/customizr-front-js-parts/blob/master/_parts_modern/_main_userxp_1_stickify_header.part.js#L182
https://github.com/presscustomizr/customizr-front-js-parts/blob/master/_parts_modern/_main_userxp_1_stickify_header.part.js#L176

Maybe a fixed value of say 50px would be enough.
But I guess you had a reason for setting that value that way.

So I can, but I need to deeply test it.
