### ISSUE TITLE
link effect => Improve compatibility with some Jetpacks widgets

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1399]
Overall improve the links in widgets CSS which was mostly designed for accepting the "underline" effect, but can create problems when the underline shouldn't be applied.
For example when links wrap an image, like in the Jetpack widget here:
<img width="162" alt="2018-01-19_18-51-03" src="https://user-images.githubusercontent.com/7689242/35164423-9b56885e-fd4a-11e7-9cc0-08feec48f6e7.png">

Reported here:
https://wordpress.org/support/topic/size-thumbnail-in-top-post-pages/
for this website : https://hobiternak.com/

**Comment by ghost** [comment]
yes this should be definitely improved ! tnks for reporting.
The primary problem reported is the size of the Jetpack widget images. Is this connected to the underline effect being activated for those links ?

**Comment by eri-trabiccolo** [comment]
Yes.
Because of the display inline-block applied to the 'a' which is so to allow
a 'better' underline-effect.

Sorry to not having explained it in detail.

Il 19 gen 2018 7:16 PM, "Nicolas Guillaume (@nikeo on wp.org)" <
notifications@github.com> ha scritto:

**Comment by ghost** [comment]
Ah ok. Yes I can see it with the dev tool.
mmm...
When you'll have time, let me know if we can find a css solution without applying an `inline-block` display.
If it's the only way to make this effect work nice, we'll have to think about a new option to control where the effect should be applied. ( even if I'm not really fan of the idea to add new checkboxes.... )

**Comment by eri-trabiccolo** [comment]
My idea is to apply it (in widgets) only to links in known widgets types,
like pages, menus etc, and of course only if the option that we already
have for the whole site, is enabled.

Il 19 gen 2018 7:35 PM, "Nicolas Guillaume (@nikeo on wp.org)" <
notifications@github.com> ha scritto:

**Comment by ghost** [comment]
yeah I like it.

**Comment by ghost** [comment]
let's schedule this for the next release, and before Hueman upgrade to FA 5.
we'll talk about it on monday.
if there's nothing else urgent for this week, enjoy your week end, have good meals, etc.

**Comment by ghost** [comment]
( no I wont say what you think to terminate this )

**Comment by eri-trabiccolo** [comment]
'idad

You too, thanks!!!

**Comment by ghost** [comment]
I was in a rrooooaaaaaaaah mood

**Comment by eri-trabiccolo** [comment]
Did it in https://github.com/eri-trabiccolo/customizr/commit/6e189d3a6155222f20c66199539eea1ff8ca1aa2
I need a way to properly test it with jetpack : cannot on the test website because stats need to be collected to make that very widget to display something - will find a different way, and then will make the PR.
After the contact-info stuff (I guess).

**Comment by eri-trabiccolo** [comment]
I've found a way to test it:
https://github.com/presscustomizr/customizr/pull/1409
