### ISSUE TITLE
Feature request: collapsible sub-menu in mobile for classical style.

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1402]
Hi @Nikeo 

Customer on helpscout request for collapsible sub-menu in mobile for Classical Style
https://secure.helpscout.net/conversation/509014866/36802/?folderId=631714#thread-1383850786

Thank you
Denzel

**Comment by ghost** [comment]
Thanks for reporting this request @denzelchia 
@eri-trabiccolo let's discuss this point during the next point.
