### ISSUE TITLE
RTL breadcrumb issue

### ISSUE THREAD

**Issue by hosseinfarnia** [Nikeo/customizr#1420]
Hi,
The separator between breadcrumbs in RTL languages should be flipped horizontally.
I mean this sign ( ») should be like this: «
Thank you very much

**Comment by eri-trabiccolo** [comment]
That's weird.
Not able to reproduce it here Hossein.
In rtl (using the WordPress function) the separator is '&laquo;' 
https://github.com/presscustomizr/customizr/blob/v4.0.17/core/front/models/modules/common/class-model-breadcrumb.php#L47

Can you share a link to your website?

**Comment by hosseinfarnia** [comment]
Yes
there is a test site that you can check it:
https://zarinmag.ir

**Comment by eri-trabiccolo** [comment]
Hi, thanks
so yeah the separator is actually a '«' (you can see it if you inspect the element), but the rtl direction seems to flip it.
Weird enough cannot reproduce it with the RTL tester plugin.
Thanks, will investigate furthermore.

**Comment by hosseinfarnia** [comment]
You're welome.

**Comment by eri-trabiccolo** [comment]
This seems to happen only in the modern style.
In classical we don't actually use a different separator in RTL: always &raquo;
(see http://www.glezer.co.il/2017/08/%D7%A9%D7%9C%D7%9E%D7%94-%D7%A9%D7%9C%D7%9E%D7%94-%D7%A9%D7%9C%D7%9E%D7%94-%D7%A9%D7%9C%D7%9E%D7%94-%D7%A9%D7%9C%D7%9E%D7%94/)

Basically what happens is that the browsers, recognizing that the word that precedes the &laquo; or &raquo; is a "RTL set of characters", automatically rotates the  &laquo; or &raquo;.

I propose then to use the same separator (&raquo;) both in LTR and RTL, as we do in the classical style.
