### ISSUE TITLE
slider : fade effect and new slider lib idea

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1428]
I have received this request from the contact form.

> Hi.The paid version of the Customizr theme allows change the slider transition to fade? … Actually I am using the free version theme with the Modern StyleThanks

This is a recurring question since the very beginning. But I've looked for a simple fade solution and I've stumbed upon this slider : https://github.com/kenwheeler/slick/

@eri-trabiccolo did you already review it when we were looking for an alternative to bootstrap.
Any opinion ? => bootstrap potential collision, responsiveness, etc..

I think that a prototype could be interesting....
to be discussed.

**Comment by eri-trabiccolo** [comment]
Yeah,
recently I thought maybe we had to replace our current slider, which is great for several aspects but the fade effects are really missing.
A prototype is needed as you said.

**Comment by eri-trabiccolo** [comment]
requested:
https://secure.helpscout.net/conversation/568329726/122885?folderId=607541

**Comment by ghost** [comment]
Work in priority on the Nimble Builder slider module, which will include a fade option.
https://github.com/presscustomizr/nimble-builder/issues/82

Need to explore this : https://github.com/kenwheeler/slick/

Closed for now.

**Comment by JTS-IL** [comment]
I've implemented fade with simple css (merged some suggestions found on several forums) on those sites:
http://www.spotting.co.il/
http://www.medi-kal.com/content/

**Comment by eri-trabiccolo** [comment]
https://github.com/metafizzy/flickity-fade
@Nikeo ^
