### ISSUE TITLE
Is there a problem with the Jetpack gallery ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1433]
The following comment has been posted today by a very upset user.

> This feature DOES NOT WORK. This theme conflicts with the JetPack gallery feature, leaving us, as users, with ugly options. WHY would you do this without providing an attractive option? WHY!?!?

> Update it to reflect that you aren't going to bother fixing the fact that your theme conflicts with JetPack's galleries. Then I wouldn't have spent all this time trying to figure out how to fix it!
> I will be moving several clients to BETTER themes that don't disable useful features without providing a useful alternative.
> If I had seen ANY evidence you were addressing this issue, I'd probably upgrade to PRO - but when complaints are left unanswered and the issues still exist - well I'm not going to spend money on something that's broken. Would you??

**Comment by eri-trabiccolo** [comment]
Which feature DOES NOT WORK?
Where has it been reported? 
Yes we do filter the gallery shortcode for our own purpose but, long time ago, to avoid issues with other plugins, we added options to disable the theme galleries.

See http://test.presscustomizr.com/2016/11/23/jetpack-tiled-gallery-test/
(with our gallery disabled)

**Comment by ghost** [comment]
The featured which DOES NOT WORK ... :) ... is the image gallery.

This problem has been reported in this doc article : http://docs.presscustomizr.com/article/116-image-galleries-in-the-customizr-theme
By clicking on the button `Was this article helpful? =>  "No" ` at the bottom

![2018-02-02_07-34-32](https://user-images.githubusercontent.com/3038156/35719871-9da7a7e0-07eb-11e8-8929-11287dc0bfed.jpg)

![2018-02-02_07-34-06](https://user-images.githubusercontent.com/3038156/35719915-c5b06d6c-07eb-11e8-84bc-45894efcdf73.jpg)

Yes we have this option to disable the Customizr gallery, but this user did not find it apparently.
I'm updating the doc quickly.

**Comment by eri-trabiccolo** [comment]
Ah I see. :/

**Comment by ghost** [comment]
doc updated : http://docs.presscustomizr.com/article/322-using-the-jetpack-gallery-with-the-customizr-theme
