### ISSUE TITLE
RTL taxonomy separator issue

### ISSUE THREAD

**Issue by hosseinfarnia** [Nikeo/customizr#1434]
Hi,
I noticed a very small issue that wanted to say.
In RTL languages the separator between categories is misplaced.
For example the link below is a post with two categories that the separator is not between them:
https://zarinmag.ir/test-post/
and in the post below the separator before the last category is gone before the first category:
https://zarinmag.ir/test-post-2/
this issue is even seen on homepage in grid of posts and everywhere esle that there are more than one or two categories.
Thank you very much

**Comment by eri-trabiccolo** [comment]
Hi @hosseinfarnia thanks for reporting this!
