### ISSUE TITLE
contact info => move harcoded rule in pro bundle into customizr stylesheet

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1436]
this ugly hack has been done to avoid publishing a new version, but it needs of course to be fixed
https://github.com/presscustomizr/pro-bundle/issues/135

**Comment by eri-trabiccolo** [comment]
customizr: https://github.com/presscustomizr/customizr/pull/1462
bundle: https://github.com/presscustomizr/pro-bundle/pull/141
