### ISSUE TITLE
Problem whith navigation menu when scrolling

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1439]
> Hi,
> 
> When I scroll a page down with my mouse's middle button while I have a navigation menu open, which have many sub-pages, the menu dissappears instantly. This is very annoying for the users when the navigation menu gets long with many subpages and users have lower resolution. This is a desktop issue.

**Comment by ghost** [comment]
I'm asking the user to share an url + theme infos

**Comment by eri-trabiccolo** [comment]
Well, opened on hover? Yes it happens.
You can see it on the demo with the topbar. Looks like it loses the focus.

**Comment by eri-trabiccolo** [comment]
Ah, that might depend on the fact that we forbid the pointer-events when 'is-scrolling'.
Have to test.

**Comment by eri-trabiccolo** [comment]
should be fixed with
js    : https://github.com/presscustomizr/customizr-front-js-parts/pull/35
css  : https://github.com/presscustomizr/customizr/pull/1440
