### ISSUE TITLE
Fontawesome list update with the latest version in the next theme update

### ISSUE THREAD

**Issue by emran1** [Nikeo/customizr#1445]
TIcket: https://secure.helpscout.net/conversation/518102501/37449?folderId=1845241

The user wants a Flipboard icon in social icons, and font awesome has approved that icon in their 5.0.5 release.

**Comment by ghost** [comment]
@emran1 thank you for reporting
We will upgrade FA to 5.0.5 + add this icon to the list of social icons

**Comment by ghost** [comment]
addressed here : https://github.com/presscustomizr/social-links-modules/issues/6
