### ISSUE TITLE
RTL Post/Page Navigation issue

### ISSUE THREAD

**Issue by hosseinfarnia** [Nikeo/customizr#1448]
Hi,
In RTL languages:
Navigation in single posts and pages should be switched. I mean left navigation should be at right side and right navigation should go to left. (previous post should be at left and next post should be at right but it's not.)
Homepage and other post lists are ok (newer posts/older posts).
Although it is not so important but I wanted to mention it.
Thanks

**Comment by eri-trabiccolo** [comment]
Hi Hossein,
this is the single navigation in LTR:
<img width="954" alt="single_nav_ltr" src="https://user-images.githubusercontent.com/7689242/35797257-6f6c79de-0a5f-11e8-9af0-18e5084653b6.png">

here's the same in RTL:
<img width="953" alt="single_nav_rtl" src="https://user-images.githubusercontent.com/7689242/35797261-739c10e6-0a5f-11e8-9e64-fd6ed4e9f953.png">

so the RTL is the mirrored version of the LTR, isn't this right?

**Comment by JTS-IL** [comment]
I Think this is correct.
Next is left, Previous is right

**Comment by eri-trabiccolo** [comment]
Thanks @JTS-IL

**Comment by hosseinfarnia** [comment]
Yes
I was wrong.

**Comment by eri-trabiccolo** [comment]
Thanks guys.
I close this then! :D
