### ISSUE TITLE
RTL back to top arrow position

### ISSUE THREAD

**Issue by hosseinfarnia** [Nikeo/customizr#1449]
Hi,
like previous issues that I opened this one has the same problem.
in customization panel when it is set to right, it will be displayed at left and so on....

Are you going to fix these issues?
Are they important? I mean shifting left and right

**Comment by JTS-IL** [comment]
I think the same semantic issue was about a year ago, it was about the left/right side bar.
If something is related as "left" or "right" it should be absolute. if something is related "before" or "after" content according to reading order it should be mirrored on RTL
