### ISSUE TITLE
RTL pagination mirror

### ISSUE THREAD

**Issue by hosseinfarnia** [Nikeo/customizr#1450]
Hi,
pagination at the bottom should be mirrored in RTL languages. Because in RTL, numbers beging form left to right, like English.
Thanks

**Comment by eri-trabiccolo** [comment]
Hi,
thanks for reporting this.

Here's the single pagination in RTL:
<img width="425" alt="rtl_pagination" src="https://user-images.githubusercontent.com/7689242/35802982-6f42059c-0a72-11e8-9488-d32b779b59cd.png">
while in LTR looks this way:
<img width="340" alt="ltr_pagination" src="https://user-images.githubusercontent.com/7689242/35803035-a24cec90-0a72-11e8-9180-dfa331696393.png">

so in RTL is mirrored as you say, no?
Is this wrong?

I see for twentyseventeen is the same.

**Comment by hosseinfarnia** [comment]
You are right.
I was wrong again. 
I checked some other sites in Persian right now and they were like twenty seventeen.
but I don't understand this. I think this is wrong.
But It's not so important. you can close this issue.
thanks

**Comment by JTS-IL** [comment]
Salam Aleikum Hossein,
TwentyTwelve is probably the best reference for RTL.
So if you think something should be the other way, there is always a chance you are right.
In this case - the RTL shouldn't be like it's now, I fixed something similar locally on my test site with "float:right"

**Comment by hosseinfarnia** [comment]
Salam Yaacov
I think this is wrong that numbers go to left in paginations. because in RTL we write numbers from left to right like English.
I also checked some famous websites in Persian, the paginations were from right to left (and I think it's very strange and wrong) in all of them.
But it's not very important. No one pays attention to this area!
This was the first time that I myself checked this area in my life!!!
Thank you

**Comment by JTS-IL** [comment]
You are right.
In Hebrew, as in Arabic, numbers are written from left to right, but the problem, talking about UI/UX, is that we are used to click on the left arrow for "next" and right arrow for "prev", and it's the other way with page numbers.
So I think that each one should use it on his site with small CSS patch

**Comment by hosseinfarnia** [comment]
Yes
I will use a css patch for this.
Thank you very much.
