### ISSUE TITLE
RTL sub menu arrow issu

### ISSUE THREAD

**Issue by hosseinfarnia** [Nikeo/customizr#1451]
Hi @eri-trabiccolo 
please take a look at this website which is in Hebrew language:
http://www.glezer.co.il/
The arrow in sub-menus should be mirrored on classic style.

**Comment by JTS-IL** [comment]
Yep
It's an old issue I keep postponing, and forgetting :)

**Comment by eri-trabiccolo** [comment]
Thanks guys for reporting this!
@JTS-IL thanks for reporting it again ;)
