### ISSUE TITLE
Video slider !

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1455]
### requested
https://secure.helpscout.net/conversation/519259554/37529/?folderId=607547
https://secure.helpscout.net/conversation/513947902/37137?folderId=610156
https://secure.helpscout.net/conversation/513371167/37089?folderId=610156
https://secure.helpscout.net/conversation/475466405/34907?folderId=607546
https://secure.helpscout.net/conversation/473461365/34729?folderId=607546
https://secure.helpscout.net/conversation/466745606/34365?folderId=610156
https://secure.helpscout.net/conversation/368854285/27498?folderId=610156

### start from here
https://github.com/presscustomizr/hueman-pro-addons/blob/master/addons/pro/header/front/classes/hap-video-bg.php

**Comment by eri-trabiccolo** [comment]
pro video slider! :P
