### ISSUE TITLE
Feature request: Featured Pages for other pages 

### ISSUE THREAD

**Issue by emran1** [Nikeo/customizr#1457]
Ticket: https://secure.helpscout.net/conversation/522114583/37726/

user wants an option to get featured pages on other pages as well.

**Comment by ghost** [comment]
Thanks for reporting it.

> I'm using the Customizr theme and want to use the Featured Pages on some other pages than just the home page. I didn't see that option in the theme directly so I purchased Featured Pages Unlimited and installed it. Wordpress says I had to disable it because its already included in the theme.
> 
> 
> Here is how I planned on using it. The site mentioned has a "Pro Shop" top level menu item. Under that are two main categories, "Services" and "Products" on the "Pro Shop" page I wanted to include those two categories as featured content. Is there some way to make that work? Or do I need to code it on my own to resemble the home page area?
> 
> Thanks,
> 
> Mark Goolie

**Comment by emran1** [comment]
Another ticket: https://secure.helpscout.net/conversation/536802623/38638?folderId=607541

**Comment by emran1** [comment]
https://secure.helpscout.net/conversation/552283054/39225?folderId=1845241
