### ISSUE TITLE
When the tagline location is set to the topbar in desktop, it is not displayed anymore in mobile

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1458]
Reported here : https://secure.helpscout.net/conversation/522310678/37742/?folderId=607544
![2018-02-12_08-59-38](https://user-images.githubusercontent.com/3038156/36087579-627e651a-0fd3-11e8-8c11-9c3faef34493.jpg)

The problem only occurs when the tagline location is set to topbar in desktops.

**Comment by eri-trabiccolo** [comment]
Ah yeah, because all the taglines share the same model instance, so the same CSS classes.
Hence the mobile tagline happen to have the 'hidden-md-down' set for the topbar one (which is rendered "before").
Hope I've been understandable :D
