### ISSUE TITLE
Plugin compatibility: Ultimate member plugin

### ISSUE THREAD

**Issue by emran1** [Nikeo/customizr#1478]
Ticket: https://secure.helpscout.net/conversation/529909634/38227/

**Comment by eri-trabiccolo** [comment]
Thanks,
cannot reproduce with https://wordpress.org/plugins/ultimate-member/ both with classical and modern style

**Comment by ghost** [comment]
I've asked the user to explain the steps to reproduce the issue

**Comment by eri-trabiccolo** [comment]
Able to reproduce the issue on the user website.
"Load images on scroll" is the involved option: disabled on the user website.
Still not able to reproduce the issue on my end.
