### ISSUE TITLE
Buddypress legacy template problem

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1484]
> I am using buddypress 2.9.3
> 
> The Buddypress settings page has a template pack option.
> 
> It only shows 'Buddypress legacy' as a template, so I have no choice.
> 
> I need to know why customizr uses the legacy template which has problems. (e.g. : https://buddypress.trac.wordpress.org/ticket/7704)
> 
> Should I be uploading a customizr template and using that? (I think so - given https://codex.buddypress.org/themes/updating-custom-themes/template-updates-2-7/ but there is no evidence of this in the customizr support pages.)
> 
> Please advise asap as I am having problems with the legacy template.
> 
> thanks
> 
> Phil

**Comment by eri-trabiccolo** [comment]
Not sure what the user means...
From
https://codex.buddypress.org/themes/updating-custom-themes/template-updates-2-7/

> In BuddyPress 2.7 we introduce some new features that specifically require template adjustment.
> 
> These changes are of importance for theme developers who may have overloaded the templates to the themes directory and these will need to be updated from the details here. If you are simply inheriting templates then there is no need to worry. Do note however some updates are not critical but are enhancements theme developers might like to carry through to their templates.

we don't override any bp template so we don't need to adjust anything.
As far as I can see even with TwentySeventeen the only available Template Pack is "BuddyPress Legacy" too.

For what I can see the BuddyPress Legacy is:
> used as the fallback for any WordPress theme that does not have BuddyPress templates in it.
https://github.com/buddypress/BuddyPress/blob/master/src/bp-templates/bp-legacy/buddypress-functions.php#L20

So, unless we create specific BP templates (and maintain them)... I don't see any other way to not use legacy templates.

I actually can see the BP github repo has a new directory called bp-nouveau, so probably in the next stable release a new template pack would be available.

Probably knowing what's the real issue the user is faceind and whether or not it's theme related would be better :D
