### ISSUE TITLE
Do wo really need to hide the browser appearance (WebKit) for radios and checkboxes ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1487]
This is the source of problems

- fixed here => https://github.com/presscustomizr/customizr/issues/1438
- but reported again here with Formidable Forms => https://github.com/presscustomizr/customizr/issues/1486

Also reported by a user on the contact form 

> im using Web 2.0 as a directory plugin. The checkboxes are part of one of the forms I'm using on that. On mobile device you see the check boxes easily, on desktop computer, they are white and hard to see, as they blend in. My website users have been having trouble creating listings.

And probably on almost all plugins using checkboxes and radios

Let's implement a permanent fix for that

**Comment by ghost** [comment]
@eri-trabiccolo can you set it as first priority in the scheduled devs ?
We can quickly chat about it if you want

**Comment by eri-trabiccolo** [comment]
Well the appearance needs to be hidden if we want a certain style. But I'm with you.
Maybe let's apply this only for those forms we know it works:
- woocommerce
- wpcf7

If you agree.

**Comment by ghost** [comment]
yes I'm with you for this opposite approach, much safer, which is to let the browser style it in all cases but the one we decide ( woocommerce + wpcf7 ).
