### ISSUE TITLE
How impacting would it be to turn slider .czrs-title from H1 to H2 ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1489]
in https://github.com/presscustomizr/customizr/blob/dev/templates/parts/modules/slider/slide.php#L29

@eri-trabiccolo even if we know that the SEO impact of having several H1 headings in a page is minimal, let's align the slider to the recommend practices.

Any opinion ?

**Comment by eri-trabiccolo** [comment]
Well, we might have the opposite complaints :D 
"The front page, when displaying a logo, has no h1".

Except for this, I don't see any other problem.

**Comment by ghost** [comment]
yeah :)
OK so let's implement it. Can you take care about it ?
The only specification is to make sure that the markup change from H1 to H2 has no visual impact on the font size and Line height.   And no impact on javascript ( if any, but I don't think so because we target the class names with fittext ).

**Comment by eri-trabiccolo** [comment]
Done, with the CSS changes, doesn't seem to have any impact, tested with wfc too.

**Comment by eri-trabiccolo** [comment]
This change has been requested for the classical style too:
https://wordpress.org/support/topic/class-h1-slide-are-not-good-for-seo-bing-google-ect/
