### ISSUE TITLE
Early check on php version ( must be >= 5.3 ? ) + WP version ( must be >= 4.5 ? )

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1496]

**Comment by eri-trabiccolo** [comment]
With 4.5 and 4.6 I get the following in the customizer, when trying to change an option whose transport 
is postMessage - same with hueman:
czr-control-modern.js?ver=1520871754:206 Uncaught TypeError: Cannot read property 'get' of undefined
    at Function.api.Setting.preview (czr-control-modern.js?ver=1520871754:206)

But I don't get fatal errors
So we might need to increase the min wp version.
