### ISSUE TITLE
Customizer: "partial" not allowed for the social links block unless you add a new one

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1499]
When I access the customizer,  in the preview, I would expect to "partial customize" the social links, but that's not the case:
<img width="944" alt="before-adding-one" src="https://user-images.githubusercontent.com/7689242/37649918-b17a3884-2c33-11e8-8a34-6cc1b5d486d2.png">

The "partial customization" is allowed only after I add (even without publishing) a new social link (adn added):
<img width="945" alt="after-adding-one" src="https://user-images.githubusercontent.com/7689242/37649905-a9bc2e40-2c33-11e8-9ba9-8c6f287dc752.png">

**Comment by ghost** [comment]
Yes I know. That's because the setting get registered dynamically only after a first modification.
I don't have a solution for the moment :/

**Comment by eri-trabiccolo** [comment]
Yeah I guessed you knew, just thought tracking it was worthwhile and flagged as enhancement and not bug :D
