### ISSUE TITLE
4.1.0 beta build won't pass the theme check and generate localization related warnings

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1501]
1) As it **requires** that every call to the add_setting() method needs to have a sanitization callback function passed.
https://github.com/presscustomizr/customizr/blob/v4.1.0-beta-2/core/czr-base-fmk/czr-base-fmk.php#L1025

2) Other warnings (which won't prevent the acceptance) will be produced, regarding to the fact that in the czr-base-fmk and in czr-modules/social-links we use constants as textdomain. For the theme check this is equivalent to have no text-domain specified.

The latter can be fixed with the addtextdomain grunt tasks (as we do with customizr-pro). Though the textdomain to replace **cannot** be a constant, nor a php varialble, otherwise the task will not understand that's a textdomain to replace, and will just add the 'customizr' text domain as third parameter. E.g:
`                    'title'       => __('Select an icon', PC_SOCIAL_MODULE_TEXT_DOMAIN)`
will become
`                    'title'       => __('Select an icon', PC_SOCIAL_MODULE_TEXT_DOMAIN, 'customizr')`

The solution would be, as we did with other plugins embedded in pro, to use a common string as textdomain, and always run the addtextdomain task when building the 'final' projects which include them.

**Comment by eri-trabiccolo** [comment]
Addtextdomain grunt task added:
customizr: https://github.com/presscustomizr/customizr/pull/1502
grunt-tasks-config: https://github.com/presscustomizr/customizr-grunt-tasks/pull/10

**Comment by ghost** [comment]
hi Rocco, can we quickly chat about the text domain issue ?

**Comment by eri-trabiccolo** [comment]
yes
