### ISSUE TITLE
Customizer not loading when using WPForms Lite: 1.4.5.2

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1507]
First report 

> Having trouble to open the customize page. Only a white side opens.

Then

> I just found out the problem was the plugin WPForms Lite

https://secure.helpscout.net/conversation/548586100/39126/?folderId=610151

**Comment by eri-trabiccolo** [comment]
Cannot reproduce,
might be a ram issue not strictly related to the plugin...

**Comment by ghost** [comment]
can't reproduce. not reported by other users.
