### ISSUE TITLE
Author URL in post metas return 404

### ISSUE THREAD

**Issue by sillyonthestreet** [Nikeo/customizr#1509]
Author pages work fine if visited manually, example: domain.com/author/admin/

But, in post metas everywhere, where it says _By Admin_, the link points to domain.com/author/ instead of domain.com/author/admin/, and domain.com/author/ returns a 404 error.

IIRC, this wasn't the case before the last update.

**Comment by ghost** [comment]
@sillyonthestreet thanks for reporting the problem. A new release with a patch for this is on the way.
