### ISSUE TITLE
How to address Google fonts being not accessible from a particular country, or not supported by a language

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1511]
Right now we use a default Google font for Customizr. This works fine in most of the cases, but there are caveats that we might want to address :

- If google fonts servers are not accessible from a given country, how can we fallback on a self hosted font ?
- If google fonts servers are accessible but the font doesn't support a given language, how can we know it and fallback on a websafe font ?

some ideas here : 
https://github.com/mkdocs/mkdocs/issues/1138

**Comment by Gunni** [comment]
I would like to add that courts have rules that linking stuff like fonts or js to content hosts in the US violates GDPR, without prior user consent.

For example: https://thehackernews.com/2022/01/german-court-rules-websites-embedding.html
