### ISSUE TITLE
A user reports that the comment field does not appear in those posts that are not in the slider.

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1526]
Not reproductible on my end...

> Hi!
> 
> I have Customizr free version. I think it's ok to translate most of the buttons to norwegian.
> 
> Is Costumizr Pro just as good or better to translate the buttons to norwegian?
> 
> Can I install Costumizr Pro in the usual way in the Word Press control panel, like other Word Press templates?
> 
> I have the defoult slider on the front with four pictures from four posts. Only these four posts have a comment field in the blog. I have looked at the settings in the wp control panel and they are okay. Why is it only a comment field on the posts that are in the slider?
> 
> I want to buy the Pro edition, but with the comment field problem, I'm skeptical.
> 
> Thank you for the answer!
> 

Then 

> Tis is the email I intended to send before you replied: «Hi! And thanks for the answer. 
> I do not understand that the carousel has no connection with the comments in wp. I thought it might be interesting to know this: I had the slider on the front page set to show the last 4 posts. I adjusted it to show the last 10 posts, but then it showed only 3. Then I adjusted it to show the last 4 posts again, but it still shows only the 3 first. 
> My webpage: http://kallvatnet.no/ « What are you doing with this problem and what happens to my web page?

**Comment by ghost** [comment]
@eri-trabiccolo let me know if you think there can be any possible connection between the post slider and the comments being active or not...

**Comment by eri-trabiccolo** [comment]
Well, no cannot think of any connection between them...
And cannot reproduce it.

Cannot reproduce the slider showing only 4 posts either: also the website shows 4 posts.

Might be a caching issue. Both can be caching issues actually...
