### ISSUE TITLE
Jetpack portfolio post type

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1530]
https://wordpress.org/support/topic/excellent-theme-296/

**Comment by eri-trabiccolo** [comment]
Mmm, not totally sure what should we do with this.
I mean, at the moment, the portfolio post type shows up as any other post, and that's fine since it doesn't really have any special field/property.
Maybe the "request" is about differentiating the portfolio items from the standard post in a way.

**Comment by ghost** [comment]
Ah ok. The first thing to test for me was that it could be displayed. So that's fine. Customizr is compatible with it.

Yes maybe the request is more about styling the jetpack portfolio. It's not specficied in the user's feedback.
