### ISSUE TITLE
Classical style : WooCommerce 3.4.0 checkout page checkbox/radio misalignment

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1536]
reported here:
https://secure.helpscout.net/conversation/588123362/163057?folderId=607709

E.g.
<img width="608" alt="2018-05-26_15-01-46" src="https://user-images.githubusercontent.com/7689242/40576422-5cb860ee-60f6-11e8-92ed-ac485fbeebed.png">

**Comment by eri-trabiccolo** [comment]
with #1547 it will look like this:
<img width="685" alt="2018-06-14_17-19-08" src="https://user-images.githubusercontent.com/7689242/41421419-15e0d556-6ff7-11e8-84b5-d28dbed64033.png">

**Comment by ghost** [comment]
Thanks for PR !

**Comment by ghost** [comment]
Let me know if you're available for a quick chat this morning

**Comment by eri-trabiccolo** [comment]
I am ;)
