### ISSUE TITLE
Style new comment form checkbox for GDPR compliance included in WP 4.9.6

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1538]
This is how it looks in the modern style
<img width="632" alt="2018-05-30_14-21-08" src="https://user-images.githubusercontent.com/7689242/40735900-beda898e-643c-11e8-8e66-0fc2cbf18670.png">

and similarly in the classical one.

**Comment by eri-trabiccolo** [comment]
with #1539 : 
<img width="590" alt="2018-05-30_14-33-42" src="https://user-images.githubusercontent.com/7689242/40736015-120984a2-643d-11e8-8ebc-725791110571.png">

**Comment by Mia65** [comment]
Hi,
this change (#1539 :) is not displayed on my page. I have free theme and the classic style. 
Attached a file (a screenshot)
I appreciate your help
[Comments Format.pptx](https://github.com/presscustomizr/customizr/files/2069458/Comments.Format.pptx)
Thank you

**Comment by eri-trabiccolo** [comment]
Hi @Mia65 ,
https://github.com/presscustomizr/customizr/pull/1539
ONLY styles the checkbox **WordPress** introduced for the standard comment form for non logged users.
This theme doesn't add any checkbox to the standard comment form.

Looking at your site, it seems you're using the Jetpack's comments system, which probably didn't add a similar checkbox. In any case the theme doesn't style the jetpack's comment form.
