### ISSUE TITLE
Social links: changes to already existent socials are not displayed in live preview

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1541]
This happens when you start customizing because the partial is not active yet.
If you change whatever setting that forces a refresh of the preview then you can see your changes to pre-existent socials.

I would expect that , for a first change, when the partial is not active yet, a preview refresh would have been triggered...

**Comment by ghost** [comment]
ok I'm on it

**Comment by ghost** [comment]
Has it been introduced recently ?

**Comment by eri-trabiccolo** [comment]
Not sure, I think it might be since the "dynamic creation".

**Comment by ghost** [comment]
yeah me too
I'll test the old version  quickly

**Comment by eri-trabiccolo** [comment]
me too 4.1.0 shows the same issue.

**Comment by ghost** [comment]
Ok. Crazy it’s not been reported before

**Comment by ghost** [comment]
Means that once created , the  socials are rarely modified.

**Comment by ghost** [comment]
I remember that you pointed it already last time but this was not for the same scenario

**Comment by eri-trabiccolo** [comment]
Yeah, not the same scenario, I just pointed out that the socials in the preview do not show the partial refresh pencil icon.

**Comment by ghost** [comment]
yep
