### ISSUE TITLE
Checkbox and radio input plugins compatibility regression

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1542]
Basically a while ago, to avoid problems with third party plugins (see: https://github.com/presscustomizr/customizr/issues/1487) we scoped special input treatments to those elements child of `.themeform`, but with this commit:
https://github.com/presscustomizr/customizr/commit/800b4d4e1e732abf304de7c40ad4dae3a74a02c3

I reverted it because of the "wrong" use of the sass @at-root directive, which applies to all the selectors specified in the rule.

:(

I'm on it.

**Comment by ghost** [comment]
ok thanks
has it been reported somewhere already ?

**Comment by eri-trabiccolo** [comment]
Yes, sorry, was about to add the link:
https://secure.helpscout.net/conversation/594684067/163292?folderId=607709

In this case they don't work because theme FontAwesome icon set is not loaded, but still it shown the symptom.

**Comment by ghost** [comment]
ok thanks for the fix.
A new version should be pushed I think

**Comment by ghost** [comment]
I mean, this is critical enough to justify a new release. What do you think ?

**Comment by eri-trabiccolo** [comment]
It's critical for plugins like Formidable Forms and WP Forms at least:
https://github.com/presscustomizr/customizr/issues/1487

**Comment by ghost** [comment]
yes

**Comment by eri-trabiccolo** [comment]
Just one thing.
This fix won't fix the user's issue in the comment form (if any), the user will still need to load the font awesome icons.

**Comment by ghost** [comment]
yep. OK

**Comment by eri-trabiccolo** [comment]
@Nikeo 
Following the conversation with the user in the ticket above, this fix becomes pretty urgent as radio buttons won't work fine, because the `-webkit-appearance ` is set to "none" for all of them, while the "font awesome appearance" is set only to the radio buttons children of `.themeform`.

**Comment by ghost** [comment]
ok. I'll do that tonight then.
thx
