### ISSUE TITLE
Relataed post with zero tags

### ISSUE THREAD

**Issue by JTS-IL** [Nikeo/customizr#1549]
Hi,
When a post has no tags, the 'related posts' displays the post as related to itself...
Is this a bug? was it meant to be like this?
http://www.medi-kal.glezer.co.il/2018/06/10/%D7%94%D7%9E%D7%9C%D7%A6%D7%94-%D7%93%D7%91-2017/ (site in progress...)

**Comment by eri-trabiccolo** [comment]
Hi @JTS-IL 
thanks for reporting this!
It's a bug.
A fix is on the way ;)
