### ISSUE TITLE
Modern: very bad rendering of ordered list item numbers

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1551]
https://demo.presscustomizr.com/layout-test/
<img width="622" alt="2018-06-18_16-36-56" src="https://user-images.githubusercontent.com/7689242/41542711-db55011a-7315-11e8-858e-7a6b7b5680d7.png">

reported here:
https://wordpress.org/support/topic/list-numbers-strange-format/

This is a side effect of this:
https://github.com/presscustomizr/customizr/commit/557b73e87cb93c5cf329acbb38a24d3cf27e8937#diff-b9143ed042ccfd7eeff0fa77e5f6012eR6

**Comment by ghost** [comment]
oh that's not good !
I'm pushing a new release tonight.
Thanks for the PR

**Comment by eri-trabiccolo** [comment]
I really appreciate you not thanking me for introducing the bug :D

**Comment by ghost** [comment]
it was implicit of course ... :)
no worries, I've done this type of mistakes too many times to know how hard to detect it is.

Anyway, this type of issue won't pass our new test process.

**Comment by eri-trabiccolo** [comment]
EDIT: wrong repo :)

**Comment by ghost** [comment]
what are you talking about... :) ?

**Comment by eri-trabiccolo** [comment]
Sorry wrong repo :)
