### ISSUE TITLE
Tests for Customizr free v4.1.7 and Customizr Pro v2.1.6

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1553]
## releases
- https://github.com/presscustomizr/customizr/releases/tag/v4.1.7
- https://github.com/presscustomizr/customizr-pro/releases/tag/v2.1.6

## tests
- [x] related posts
- [x] do nested  ol lists display fine ?
- [x] old php
- [x] customizer : does it load properly ?
- [x] social links : can we add new ?
- [x] slider creation => creating a new slider
- [x] featured page customization
- [x] Pro : does wfc work ?

**Comment by ghost** [comment]
Hello @eri-trabiccolo, my tests have gone fine.
Can you run the following tests on your side this morning ?
Thanks !

**Comment by eri-trabiccolo** [comment]
@Nikeo:
tests passed on my side.
