### ISSUE TITLE
GDPR not translatable

### ISSUE THREAD

**Issue by JTS-IL** [Nikeo/customizr#1554]
Hi,

I want to add Hebrew translation of the GDPR (with checkbox, next to the comments) but I cant find it...

**Comment by eri-trabiccolo** [comment]
Hi @JTS-IL 
that checkbox is not part of the Customizr theme, it's part of WordPress ;)
The Customizr theme doesn't add any checkbox to the contact form :)

I close this.

**Comment by JTS-IL** [comment]
oops...

**Comment by eri-trabiccolo** [comment]
No worries @JTS-IL it happens ;)
