### ISSUE TITLE
Demo content in the previewer is not allowed anymore on wp.org. Featured Pages and slider should be disabled by default.

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1556]
https://themes.trac.wordpress.org/ticket/56237#comment:4

> The team leads have decided to ban manipulating/targeting the .org previewer with dummy content/images.
> Please remove such methods or your theme will be suspended. (do the same for the Hueman theme). The slider and feature boxes need to be disabled by default.
> You have 48 hours to respond.
> Thank you.

**Comment by eri-trabiccolo** [comment]
what about the demo slider?
Do we have to remove it?

**Comment by ghost** [comment]
no, as long as it's not enabled by default, I don't see any reason why we should remove it.

**Comment by ghost** [comment]
Thx. Merged. I'm running some tests.
