### ISSUE TITLE
No main menu (while there's a mobile menu) is shown in the live preview 

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1559]
That's because we don't fall back on the page menu by default anymore in prevdem.

Any idea on what do we have to do?

Ah wait, it should display the page menu actually...

**Comment by ghost** [comment]
Critical ? steps to reproduce ?

**Comment by ghost** [comment]
Main concern : Does it prevent users to display a menu ?

**Comment by eri-trabiccolo** [comment]
look at the preview in wp.org

**Comment by ghost** [comment]
ah ok.

**Comment by ghost** [comment]
thanks for reporting the bug. This can wait the next release I think no ?

**Comment by eri-trabiccolo** [comment]
Well, it only impacts the prevdem, so... marketing choice :D

**Comment by eri-trabiccolo** [comment]
Actually, new users will never see the page-menu there, they have to create a menu and show it in that location, so as of now, not showing the default page-menu there is more consistent with what users will get.
