### ISSUE TITLE
Blank preview with WordPress 4.7.10 (at least)

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1565]
Tested also with 4.8 and 4.8.6 (latest of the 4.8 branch).
<img width="925" alt="error-preview" src="https://user-images.githubusercontent.com/7689242/42086502-8b7b8e1c-7b93-11e8-9d93-f713ac88a51a.png">

(same happens with Hueman)

reported:
https://wordpress.org/support/topic/blank-page-on-customizr-preview-screen/#post-10447320

FYI: 4.9 works

**Comment by ghost** [comment]
OK thanks.
I'm replying to the user in the forum.
