### ISSUE TITLE
Inifinite scroll keeps triggering the post load when reaching the bottom of the page

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1567]
![infinite_scroll_bug](https://user-images.githubusercontent.com/3038156/42527720-ba8eb582-8479-11e8-9e0d-7cdbd70986a7.gif)

**Comment by ghost** [comment]
Not urgent.
In the project list https://github.com/orgs/presscustomizr/projects/2#card-11222698

**Comment by eri-trabiccolo** [comment]
Ok.

**Comment by ghost** [comment]
not opened at the right place ...
