### ISSUE TITLE
smoothscroll => examine disabling it by default

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1571]
I recently received a feedback from a pretty pissed-off user about smooth scrolling.

> why the FUCK websites NEED to scroll-jack?
> 
> your themes forcing scrolling to be "smooth". WHY?
> 
> WHO IS IT FOR?
> 
> i get motion-sickness from this usless shit.

This made me think that this user might not be the only one to experience any unwanted slowness. And that a maybe safe solution would be to disable it by default.

@eri-trabiccolo what do you think ?

**Comment by eri-trabiccolo** [comment]
Let's disable it by default for new users.
But I think that we should apply some kind of smoothness to the user.

I understand that understanding what's the issue it might be hard, but hey that's absolutely not the way to talk.

**Comment by ghost** [comment]
OK. Yes I'm with you. let's do that for the moment.
And yes, not a way to talk ! But the point raised is still interesting to take. The rest is about how this person considers other humans (apparently not with many respect), not my problem, I'm neither his father, nor a monk... :)

**Comment by eri-trabiccolo** [comment]
Aren't you a monk?
Ohhhh

Yeah sure, I see your point.
Anyway it doesn't affect a lot of users, otherwise it would have affected us too.

I think parallax might suffer a little bit about this though (depending on the browser).
