### ISSUE TITLE
New option to display the site title next to the logo 

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1573]
### Customizr
- Add a new checkbox option to the map, only for ms
- Enabled by default for new users
![2018-07-24_18-16-38](https://user-images.githubusercontent.com/3038156/43152063-cf414bda-8f6d-11e8-8de5-13971d0f3b6c.png)
- "Display your site title next to the logo" <= checked by default

### On front
The idea would to display the logo + site title in the same block, inline.
- if "Tagline below" option is enabled => the tagline is displayed below the block of logo + site title
- it "Tagline next" option is enabled => the tagline is displayed below the site title, inside the site title block
![2018-07-24_18-15-41](https://user-images.githubusercontent.com/3038156/43152300-8671622c-8f6e-11e8-8857-0a214bae457a.png)

**Comment by eri-trabiccolo** [comment]
Hi Nico,
prototype here:
https://github.com/presscustomizr/customizr/pull/1574
Tell me what you think, when you want

**Comment by ghost** [comment]
It works as discussed and specified. Thanks.
I'm might simply update the option wording.
Merging
