### ISSUE TITLE
Gutenberg post-format conditional meta-boxes issue

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1576]
The code implemented in https://github.com/presscustomizr/customizr/pull/1500
Doesn't work anymore, 'cause the post-format selector dom element doesn't exist yet at the time we perform the check on its existence.

To rapidly fix this I propose to just delay a little bit our main code execution.
See also https://github.com/presscustomizr/hueman/issues/672#issuecomment-409481887

**Comment by ghost** [comment]
great thanks, I'm on it after lunch
