### ISSUE TITLE
left sidebar RTL issue

### ISSUE THREAD

**Issue by hosseinfarnia** [Nikeo/customizr#1581]
Hi,
The left sidebar is not RTL in right to left languages. I had reported it before but it has not been fixed yet.
https://screencast-o-matic.com/watch/cFj6ehqi7E
Thanks

**Comment by JTS-IL** [comment]
As-salamu alaykum Hossein,

I think it's not RTL issue, It's the design.
A small fix in the css will do the job:
`
.widget-area .widget {
    text-align: start;
}
.tc-sidebar.text-md-left .widget-title::after {
    left: auto;
    right: 0;
}
`

**Comment by hosseinfarnia** [comment]
שלום
תודה על עצתך

**Comment by JTS-IL** [comment]
:-)

**Comment by ghost** [comment]
Bonjour messieurs,
Thanks for reporting this again. We are currently taking a break until August 15th.
We will take care of this issue when back.

**Comment by eri-trabiccolo** [comment]
Hi @hosseinfarnia as @JTS-IL said that's a design choice. The text in the sidebar which appears on the left is aligned to the left, the text in the sidebar which appears on the right is aligned to the right, as you can see in our demo:
https://demo.presscustomizr.com/three-columns-right-and-left-sidebars/

It's the same for RTL.

**Comment by eri-trabiccolo** [comment]
see also: https://wordpress.org/support/topic/for-arabic-website/#post-11073248

**Comment by ghost** [comment]
following @eri-trabiccolo replies I'm closing it
