### ISSUE TITLE
Comment RTL alignment

### ISSUE THREAD

**Issue by JTS-IL** [Nikeo/customizr#1582]
The post comments css on RTL site needs a little fix,
**instead** of 
`.col-md-6 .comment-list ul.children, .col-md-9 .comment-list ul.children {
    margin-left: calc(1.5em + 1.25em);
}
.comment-list ul.children {
    margin-left: calc(3em + 1.25em);
}`
it **should** be
`.col-md-6 .comment-list ul.children, .col-md-9 .comment-list ul.children {
    margin-right: calc(1.5em + 1.25em);
}
.comment-list ul.children {
    margin-right: calc(3em + 1.25em);
}`

**Comment by eri-trabiccolo** [comment]
Hi @JTS-IL 
thanks for reporting this, you're right :)
