### ISSUE TITLE
html validation: A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute with the value IE=edge.

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1583]
Because of:
https://github.com/presscustomizr/customizr/blob/dev/inc/_dev/parts/class-header-header_main.php#L118

Can we remove all the other content attribute values and keep only ID=edge?
Would this have any old ie browsers compatibility negative impact?

reported:
https://secure.helpscout.net/conversation/639345226/164695?folderId=607709

**Comment by eri-trabiccolo** [comment]
Let's get rid of this @Nikeo, we'll add it back if needed... which I don't think.

Also reported here:
https://secure.helpscout.net/conversation/699208975/165922?folderId=607709

**Comment by ghost** [comment]
let's go. With you
