### ISSUE TITLE
Compatibility with learnpress

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1589]
> First I want to thank for such an excellent template, I like it a lot. I'm using the free template, but I found a problem with the Learnpress plugin. Users can not register for courses because the template jumps to an infinite cycle. I would like to know if I buy CUSTOMIZR PRO this error will be solved.
> 
> Thank you very much.

related to #904 ?

**Comment by eri-trabiccolo** [comment]
Well, their related because without the fix for #904 no lp type of content would be accessible at all :D 
And yes, the code we use to fix #904, is responsible of this infinite loop.
