### ISSUE TITLE
ol li before (counter items) and Learndash plugin compatibility

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1591]
Issue with learndash (premium plugin). Reported here:
https://secure.helpscout.net/conversation/644821393/164830?folderId=607709

We know that our list items (mostly for the ordered ones) style can produce some issue with plugins.
Not sure what we can do to avoid the issue tout-court without renouncing to our style, probably nothing...

I'm going to push a simple PR ad hoc for this plugin compatibility

**Comment by ghost** [comment]
thanks.
"tout-court" :)
