### ISSUE TITLE
WooCommerce => no arrows to change the number of products to add to the cart, happens on variable products on Firefox

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1598]
https://wordpress.org/support/topic/good-but-dont-support-woocommerce-correctly/

**Comment by eri-trabiccolo** [comment]
I can reproduce it with the modern style,
don't think it happens with the classical, has it has to do with a specific CSS rule of the modern style, that I think we can totally remove:
here's the themeform input type number
https://github.com/presscustomizr/customizr/blob/dev/assets/front/scss/0_3_components/_forms.scss#L119

here's were we say that the variation form should act like the themeform.
https://github.com/presscustomizr/customizr/blob/dev/assets/front/scss/0_3_components/_plugins.scss#L189


I suppose this started happening only recently, meaning only on recent firefox versions as we never had any report on this... but I can be wrong.
