### ISSUE TITLE
support for Gutenberg : cover image and other blocks

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1601]
- The Ultimate Guide to Gutenberg Image Alignments in WordPress Themes — Rich Tabor https://richtabor.com/gutenberg-image-alignments/
- Get Your WordPress Theme Gutenberg-ready — Ellen Bauer https://www.elmastudio.de/en/get-your-wordpress-theme-gutenberg-ready/
- Getting Your Theme Ready for Gutenberg — Bill Erickson https://www.billerickson.net/getting-your-theme-ready-for-gutenberg/

**Comment by ghost** [comment]
will be done here https://github.com/presscustomizr/hueman/issues/702

**Comment by eri-trabiccolo** [comment]
see also #1611 for blockquotes and pullquotes

**Comment by eri-trabiccolo** [comment]
reopening because of https://github.com/presscustomizr/hueman/issues/702#issuecomment-439007412

**Comment by eri-trabiccolo** [comment]
According to https://richtabor.com/gutenberg-image-alignments/

these are the blocks that support new content alignments:

- [x] Pullquote Block
- [x] Gallery Block
- [x] Image Block
- [x] Cover Image Block
- [x] Video/Audio Block
- [x] Table Block
- [x] Columns Block
- [ ] Text Columns Block
- [x] Categories Block (fullwidth only)
- [x] Embed Block

- [x] Media & Text

I'm going to see which and how to implement their alignment.

Edit:
As of now 15/11/2018:
- no alignwide alignfull classes are added to the Pullquote Block (probably a Gutenberg bug), anyway I "emulated" the test by manually adding those classes.
- couldn't find the Text Columns block, I guess it has been replaced by the Media & Text, that I've added to the list.
- The Table block has been aligned with some additional JS at the moment in the cases:
a) alignwide
b) alignfull and alignwide in a boxed layout

**Comment by ghost** [comment]
OK Thank you.
Let's schedule a chat about this and select2 at around 2PM, what do you think ?

**Comment by eri-trabiccolo** [comment]
Fine for me, talk you later then!

**Comment by ghost** [comment]
https://weblines.com.au/gutenberg-blocks-wide-alignment-full-width/

What Block Types Can Be Full or Wide-Aligned?


> Assuming that your theme supports them, the new alignment options are offered for these blocks:-
> 
> - Cover Image Block
> - Image Block
> - Gallery Block
> - Pullquote Block
> - Video Block
> - Table Block
> - Columns Block
> - Categories Block (fullwidth only)
> - Embed Block

**Comment by eri-trabiccolo** [comment]
see list of succesfully tested blocks with:
https://github.com/presscustomizr/customizr/pull/1628
https://github.com/presscustomizr/customizr-front-js-parts/pull/43

at:
https://github.com/presscustomizr/customizr/issues/1601#issuecomment-439008417
