### ISSUE TITLE
Parallax slider doesn't work fine in Microsoft Edge

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1605]
https://wordpress.org/support/topic/slider-in-microft-edge-on-scroll-shutters-moves-jerky-stutters-using-parallax/

Maybe we can consider to disable it in edge?!

**Comment by ghost** [comment]
yes. I have no problem with that!

**Comment by eri-trabiccolo** [comment]
Anyway I cannot reproduce the issue on the user website (classic style) with Edge.
I've asked the user if he can reproduce the issue on our demo website (modern):
https://demo.presscustomizr.com/full-width-slider-with-call-to-actions/

**Comment by ghost** [comment]
ok. Thanks .
