### ISSUE TITLE
Author info block => author post count does not include CPT ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1614]
https://secure.helpscout.net/conversation/692859521/165799?folderId=607547

> Hi,
> 
> I am using PressCustomizr Pro for a recipe site, with multiple authors.
> 
> The plugin I am using for the recipes, WordPress Ultimate Recipe Premium, allows me to treat recipes as regular posts, and I have activated that option. Thus, all recipes created appear in my posts list in WordPress.
> 
> I have activated the Author Info Block in Customizr Pro. However, when I look at the Author Info Block at the bottom of a page (for example, https://recettes.vg/recettes/baguels-veganes-de-shawinigan/), I see the posts count as zero (0). This inacurate, in the case of that author, who has in fact posted 7 recipes, or posts, as you can see here: https://recettes.vg/author/isabelle/.
> 
> Why is that?
> 
> Thank you!

**Comment by eri-trabiccolo** [comment]
Mmm yes count_user_posts counts only the post post_type by default, anyways the link will still point to the author post archive, no?!
Also the link says "N posts" not "N whatever" or "N posts + whatever"
Will look at it but I would rather go with a won't fix :)
I understand the author box below a CPT saying the author wrote "N posts" doesn't make a lot of sense, and that can be improved!

**Comment by ghost** [comment]
Waiting for the plugin to be tested.
But, we might not be able to fix the reported problem because the wp function that we use can be filtered by the plugin
