### ISSUE TITLE
Event calendar potential bug ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1615]
https://secure.helpscout.net/conversation/688965310/165723/?folderId=607544
> I'm maintaining the website of my children's school, with customizr (free version). I also have a subscription to customizr-pro for work website.
> 
> The problem is about "the events calendar" plugin. I don't know if the problem is related to free version of customizr or not.
> 
> If I display in frontpage the recent articles without any category filter, also events are shown; but if I use a filter on category, only articles are displayed, while events disappear from frontpage. I created the "homepage" category both for articles and events.

**Comment by eri-trabiccolo** [comment]
That's pretty weird, events are CPT how can they appear in the home showing latest posts?
The weird thing to me is the behavior when no filter is applied...
Unless the user is referring to some widget, in that case I can see the point, have to check we alter only the main query. We should do so, and if we do it, this means the problem is not really about us...

**Comment by eri-trabiccolo** [comment]
The Events Calendar plugin has an option that allows to display the Event CPT in the main blog loop.
The Event Category taxonomy is NOT the WordPress Post Category taxonomy, the first is a custom taxonomy.
Our category filter option allows filtering the home blog by WordPress Post Category, not by a custom taxonomy.
Most likely the user created an Event Category with the same name of a Post Category, but this doesn't mean they're the same taxonomy. So, basically, he/she is selecting to filter the home blog by a Post Category, hence the events, that do not have (read: cannot have) that Post Category assigned, will not be displayed, and that's correct.

Maybe we can support custom taxonomies in the future, make that filter much more complex including of course tags and conditional statements, e.g. this cat && this cat, this cat || this tag... (most likely _no_)

**Comment by ghost** [comment]
OK. Makes complete sense. thanks
I'm replying with an almost copy and paste of your analysis to the user.

**Comment by eri-trabiccolo** [comment]
Ah, I can reply doing the same if you want :D
