### ISSUE TITLE
Updating the translation from free to pro ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1616]

**Comment by eri-trabiccolo** [comment]
We said no actually ihihi, that's 'cause there are some steps that must be done manually (no node module available for the gettext msg_merge), but of course we can change idea and do it from time to time :)

**Comment by ghost** [comment]
Yeah I know it has to be manual. I have users asking me about this synchronization free-pro...

**Comment by eri-trabiccolo** [comment]
Yeah the sync cannot really be done for all the locale: it and fr have specific pro translations that will be lost with an automatic task as we don't have a way to merge translations at the moment.
But ok, will look at it :)

**Comment by JTS-IL** [comment]
As a happy user of both free and Pro (and a happy translator of the free Customizr to Hebrew), I would appreciate a sync of the translations, or open the Pro for web translation...

**Comment by ghost** [comment]
+ hueman as discussed today
