### ISSUE TITLE
New option to not "underline" widget titles, featured page titles, ... ?

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1618]
requested:
https://secure.helpscout.net/conversation/694492744/165824?folderId=607709

From one side I would say yes, but from another... well that's distinctive of the theme,
but you know everyone wants and needs to make his/her website as unique as possible.

**Comment by ghost** [comment]
I agree. And keep the distinctive part. let's not implement it for the moment. This is not a priority.
