### ISSUE TITLE
consider adding a {{date}} dynamic parsable variable inside for the credit html

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1622]
The idea would be to filter the footer credits with a callback like here : https://github.com/presscustomizr/nimble-builder/issues/201

reported here : https://secure.helpscout.net/conversation/703323202/166013?folderId=607547

**Comment by eri-trabiccolo** [comment]
Mmm this is for the pro

**Comment by ghost** [comment]
ah yes
