### ISSUE TITLE
General WP 5.0 compatibility tests and patches

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1623]
Following the [bug discovered with Nimble](https://github.com/presscustomizr/nimble-builder/issues/225), we need to 
1. make sure there's no other problems with Customizr free and pro
2. add this compatibility patch
```php
// WP 5.0.0 compat
// @see https://core.trac.wordpress.org/ticket/45292
if ( false !== has_filter( 'content_save_pre', 'wp_targeted_link_rel' ) ) { 
 remove_filter( 'content_save_pre', 'wp_targeted_link_rel' ); 
}
```

**Comment by eri-trabiccolo** [comment]
but we should do this only in the customizer, right?

**Comment by ghost** [comment]
well yes.

Precisely, at the moment the customize changeset post is inserted / updated in database ( this changeset post is reused later, when publishing, and turned into real options ). So this should normally be a scenario easy to target by checking either $_POST or if the global $wp_customize object is set.

But this needs tests. Because there might other scenarios that I don't know, in which the customize changeset is created.

**Comment by eri-trabiccolo** [comment]
The important thing is that we don't remove that filter when it's "needed".

**Comment by ghost** [comment]
yep.

**Comment by eri-trabiccolo** [comment]
see:
https://github.com/presscustomizr/hueman/issues/719#issuecomment-437050927

My memory says that we could have the same issue in:
1) FPU textarea (pro)
2) Footer Credits (pro)

**Comment by eri-trabiccolo** [comment]
to not forget: fpu standalone https://github.com/presscustomizr/tc-unlimited-featured-pages/pull/129
