### ISSUE TITLE
Add an option to remove the various header borders/box-shadow

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1624]
It could be nice especially when combined with the new header transparent option.

requested here:
https://secure.helpscout.net/conversation/704987161/166052?folderId=607709

When the header transparent option is on we remove the box-shadows by default but we keep the tiny borders below the topbar and the header.

@Nikeo when you can let me know if we can consider to accept this as feature request.

**Comment by ghost** [comment]
A checkbox would be fine.
That is a spec!

**Comment by ghost** [comment]
also requested here : https://secure.helpscout.net/conversation/747888661/167023/?folderId=607541

**Comment by ghost** [comment]
checked (removed ) by default, active only when header transparent is on.

**Comment by eri-trabiccolo** [comment]
with "checked by default" I guess we mean for new users.
That's how implemented it in #1660
