### ISSUE TITLE
Get rid of now useless icheck* assets

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1625]
We don't use that library anymore, right?!

**Comment by ghost** [comment]
it's used in the customizer.
The goal would be to replace it everywhere by the gutencheck ultimately yes.

**Comment by eri-trabiccolo** [comment]
Ops, I think I'm confusing the libs, I meant the iphone check ...
Will keep this open for the future, and open a new one :D

**Comment by ghost** [comment]
Ah yes, about the iphone, It's not used anymore. I think we only used it in the post metas boxes, recently replaced by gutenchecks
