### ISSUE TITLE
The Events Calendar Pro: improve Mini Calendar table style compatibility 

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1629]
this is mostly due to the fact we add quite big padding to the table elements by design...
We already avoid this for some specific widgets, e.g. the default wp calendar widget.
In my opinion we have to exclude the mini calendar widget as well.

reported:
https://secure.helpscout.net/conversation/688965310/165723/?folderId=607546

**Comment by ghost** [comment]
ok got it. Thanks

**Comment by ghost** [comment]
I agree; merging
