### ISSUE TITLE
Woocommerce => Add to Cart not working on products displayed on front page with shortcode => common issue

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1634]
https://wordpress.org/support/topic/not-working-add-to-cart-on-products-displayed-on-front-page-with-shortcode/#post-10922515

> hello,
> 
> I am using on the frontpage a shortcode as
> [recent_products per_page=”8″ columns=”4″ orderby=”popularity” order=”rand”]
> 
> and the products display on the front page.
> 
> I have the woocommerce function “REDIRECT TO CHECKOUT PAGE WHEN ADDING PRODUCT TO CART” enabled, and everywhere on my shop when someone clicks on ADD TO CART, he is redirected to cart/checkout page.
> 
> BUT not on the front page.
> 
> When someone clicks ADD TO CART on a product displayed on the front page, the “loading” circle is showing but then nothing happens and customer is not redirected to checkout.
> 
> When clicking on the product picture, customer is correctly redirected to the product page, where he can click ADD TO CART to be redirected to cart/checkout page.
> 
> Can you try to reproduce this ? And do you know how to fix it ?
> 
> Thank you.

**Comment by eri-trabiccolo** [comment]
If it's about the classical style, this is a known bug (tomorrow will find the open issue referencing to this) and depends on a js conflict that generates when the theme target link options (both of them) are enabled.
Disabling the will "fix" the issue.

**Comment by ghost** [comment]
Hey you're back ! :)
Let's schedule a chat tomorrow morning at 10 if you can ?

**Comment by eri-trabiccolo** [comment]
Yeah, back at home a couple of hours ago.
About the chat: fine for me! :)

**Comment by ghost** [comment]
Impacts only the classical style

**Comment by eri-trabiccolo** [comment]
Also reported here https://github.com/presscustomizr/customizr/issues/1155
