### ISSUE TITLE
Incompatible with WPForms Stripe Credit Card Input?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1636]
https://secure.helpscout.net/conversation/720326657/166362/?folderId=607544
> Hello. I manage a site for a nonprofit and recently discovered that we are not able to use WPForms to collect credit card information on our site. When you try to input the credit card, the year will not enter. I did a quick check with twenty seven theme and it seems to works fine there (verified with live preview). I verified that this is not a plug-in incompatibility issue (deactivated every plugin). Can you tell me if you have had other reports of this? I've currently had to rework the donation page to eliminate taking credit cards, which is obviously not going to work long-term. Please see this page for a first-hand look at the issue: teamtomball.com/sponsorship All you have to do is scroll to the bottom of the page, input a month and attempt to input a year and you'll see that it doesn't work. Help!? I've used your theme for a year and a half and we all love it. However, we have to be able to take credit card information on our site.

**Comment by eri-trabiccolo** [comment]
well it depends on our CSS rule which sets the select min-width to 100%, which makes the "expiration" selects sit one on top of each other
I can remove it, or, maybe better, override it for wp-forms.

I think I can either replace the min-width with just width and should be fine. I will check the most important plugins with this change.

**Comment by eri-trabiccolo** [comment]
I went with the width set to 100%, with a minimum code added for WooCommerce.

Anyway the min-width:100% is there since the beginning:
https://github.com/presscustomizr/customizr/commit/ab37c7911dfc0151569b93d1d7f321d7246d8b8a#diff-e53151a497ef302df56b04e0bdc1e567R110

**Comment by ghost** [comment]
ok. So it was useful only for WooCommerce then.
Anyway, a potential regression on another plugin is not that risky. We're only talking of a css rule.

**Comment by eri-trabiccolo** [comment]
Yeah, we'll see :)
