### ISSUE TITLE
Possible issue with WP 5.0 - redirect to login page?

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1641]
https://wordpress.org/support/topic/the-theme-has-a-problem-once-installed-it-makes-access-to-wordpress-blank-page/

I'm not able to reproduce the issue though.

Any idea @Nikeo ?

**Comment by eri-trabiccolo** [comment]
User says it doesn't occur anymore.
I close this.

**Comment by ghost** [comment]
ok. thanks for reporting anyway :)
