### ISSUE TITLE
Gutenberg : style the editor container like Twenty nineteen does

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1642]

**Comment by giorgioriccardi** [comment]
in case this helps: [https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#editor-styles](https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#editor-styles)

**Comment by eri-trabiccolo** [comment]
pushed a PR with a "prototype" as we discussed.
