### ISSUE TITLE
Smartload broken in pages created with Gutenberg ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1647]
I can't reproduce the issue on my side.
@eri-trabiccolo can you ?

Comment posted here : http://presscustomizr.com/release-note-for-customizr-for-customizr-pro-v2-1-12-and-customizr-free-v4-1-23/

> I recorded the update and found that pages created with the Gutenberg Editor have the following problem:
> If I activate the function “Images while scrolling load”, I get in the mobile version with my Android devices no more pictures displayed. However, this is only the case for pages written with the new editor. I’ve just redesigned 2 pages with Gutenberg, but would like to gradually turn everything into blocks. But I will wait until the problem is resolved. Maybe you can check it out and fix it in a next update. Also again the demand, why it could be that my photos of the Featured pages on the start page in the mobile version are out of focus?
> Thank you very much for the help and best regards
> Birgit

**Comment by eri-trabiccolo** [comment]
Mmm, nope I don't seem to be able to reproduce the issue.
Do we have any link to the user website?

**Comment by ghost** [comment]
https://www.goldschmiede-holtmann.com/

**Comment by eri-trabiccolo** [comment]
Thanks.
Though it doesn't really helps at the moment since:
a) we should navigate the whole site looking for a page built with gutenberg - if public :)
b) that site doesn't have the smartload option enabled

also that site has autoptimize active.
