### ISSUE TITLE
Contact Form 7 + Recaptcha problem with Customizr cs ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1649]
https://wordpress.org/support/topic/recaptcha-problem-8/
> I think there is a problem with Customizr and contact form 7 / google recaptcha.
> 
> I received spam email and the recaptcha logo doesn’t appear on the contact page while it is on all my other websites
> 
> Thanks for your help and your wondefull theme
> 
> The page I need help with: https://www.leszikomatics.fr/contact

**Comment by HowdyMcGee** [comment]
I left a similar comment on the forum but it's likely a non-issue and related to the update of Contact Form 7 to 5.1:

> This is likely the 5.1 update to Contact Form 7 which removes the [recaptcha] shortcode and implements Google reCaptcha v3. You would either need to add the API keys for version 3 reCaptcha or install something like Contact Form 7 – reCaptcha v2 plugin to retain the old [recaptcha] tags. Here’s an article on how to set up version 3 reCaptcha in Contact Form 7

**Comment by ghost** [comment]
ok thanks for the feedback. I'm closing it now
