### ISSUE TITLE
Sticky header doesn't appear when scrolling down very fast

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1650]
Of course the **Header menu visibility** on scroll should be set to **Always visible**
to make this happen.

reported:
https://secure.helpscout.net/conversation/731363151/166578?folderId=607709

we actually should catch this edge case here...
https://github.com/presscustomizr/customizr/blob/dev/assets/front/js/_parts/_parts_modern/_main_userxp_1_stickify_header.part.js#L232

**Comment by eri-trabiccolo** [comment]
@Nikeo any idea on how to fix this?
we've been asked for the status of this here https://secure.helpscout.net/conversation/731363151/166578?folderId=607709

**Comment by ghost** [comment]
ok.
This looks like a candidate for `_.debounce`. Needs test.
