### ISSUE TITLE
PHP fatal error when playing with the gallery widget in the customizer

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1652]
I copy here the raw errror message to keep a trace of it. I'm not sure how to reproduce this.

> [19-Dec-2018 18:03:39 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function czr_fn_post_action() in /srv/www/customizr-dev/htdocs/wp-content/themes/customizr/core/front/utils/class-content-gallery.php:217
> Stack trace:
> #0 /srv/www/customizr-dev/htdocs/wp-includes/class-wp-hook.php(286): CZR_gallery->czr_fn_maybe_add_lighbox_button('<a href=http://...', 30, Object(WP_Post))
> #1 /srv/www/customizr-dev/htdocs/wp-includes/plugin.php(203): WP_Hook->apply_filters('<a href=http://...', Array)
> #2 /srv/www/customizr-dev/htdocs/wp-content/themes/customizr/core/front/utils/class-content-gallery.php(157): apply_filters('czr_gallery_ima...', '<a href=http://...', 30, Object(WP_Post))
> #3 /srv/www/customizr-dev/htdocs/wp-includes/class-wp-hook.php(286): CZR_gallery->czr_fn_czr_gallery('', Array, 1)
> #4 /srv/www/customizr-dev/htdocs/wp-includes/plugin.php(203): WP_Hook->apply_filters('', Array)
> #5 /srv/www/customizr-dev/htdocs/wp-includes/media.php(1660): apply_filters('post_gallery', '', Array, 1)
> #6 /srv/www/customizr-dev/htdocs/wp-includes/widgets/class-wp- in /srv/www/customizr-dev/htdocs/wp-content/themes/customizr/core/front/utils/class-content-gallery.php on line 217

**Comment by eri-trabiccolo** [comment]
That's weird indeed.
As If some files weren't loaded...
I've tried to reproduce it as well, no luck at the moment.
