### ISSUE TITLE
Suggestion: An option to hide tags/categories when there are many

### ISSUE THREAD

**Issue by sillyonthestreet** [Nikeo/customizr#1654]
It would be great if there was an option to hide most of the tags and categories when a post has many of them. Something like displaying 3 tags and a clickable button that says "X more tags". This way a post with too many tags or categories won't break the site's layout. Currently, it makes the post lists uneven since one of the posts will be much longer if more categories and tags are used. It looks cluttered too.

**Comment by ghost** [comment]
Triage Sept 2020. 
Closed issues will be used as references for more recent ones.
