### ISSUE TITLE
Change blockquote background

### ISSUE THREAD

**Issue by sillyonthestreet** [Nikeo/customizr#1656]
I'm using the Modern style. By default, the blockquote has no background/a white background. 

I'd like to add a background. Something like #f5f5f5

When adding a CSS rule:

`.blockquote { background: #f5f5f5; }`

It doesn't work. I tried background-color too. I tried using my child theme's style.css and the Additional CSS field from the customizer. I tried adding !important.

Cleared my cache and everything. It works fine when I edit the element via Inspect Element from my browser, but I can't get it to work via the theme's CSS.

What am I missing here?

And wouldn't it be better if the blockquote had some kind of a background by default?

**Comment by eri-trabiccolo** [comment]
Hi,
cannot reproduce your issue, I can definitely style the blockquote background in my child-theme style.css, using the modern style.

You probably want to use
`blockquote { background: #f5f5f5; }`
as the `blockquote` is an HTML element which not necessarily has the `.blockquote` CSS class, hence the CSS rule you're using above just doesn't target the element you want to style.

You might find more about CSS and HTML here:
https://docs.presscustomizr.com/article/72-basics-of-css-and-html-for-wordpress-themes
https://docs.presscustomizr.com/article/63-css-resources-for-wordpress-developers

Hope this helps.

Best regards.

**Comment by sillyonthestreet** [comment]
Ooh, right. Forgot that it's actually an element rather than a class. Works now. Thanks!
