### ISSUE TITLE
smooth scroll only works inside the content wrapper ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1662]
> It seems that the smooth control only works from main content to main content.
> 
> If the Link is in the main navigation or for example in the slider, the smooth scroll is broken. 😊
> 
> # SITE_URL: https://aihro.de

Is that true. What would be the problem to listen to click events on selectors outside main content, like in header and footer ?

**Comment by eri-trabiccolo** [comment]
It's true, only when inside the `#content`, and yes, it has always been so:
https://github.com/presscustomizr/customizr/blob/dev/assets/front/js/_parts/_parts_modern/_main_userxp_9_various.part.js#L576

I think you wanted to limit the "problems" when you firstly implemented it :D eg with dropdown menus...

Needs some testing though.

**Comment by ghost** [comment]
ok. yes the "limiting problems" explanations is probably the right one :)

Is it ok if I add it in your colUMN ? ( i know, i like repetition in jokes... ) Or do you prefer that I handle it ?

**Comment by eri-trabiccolo** [comment]
Fine for me (jokes repetition too), add it ! :D

**Comment by ghost** [comment]
done.
Can you work on the captcha thing before ? Thanks !

**Comment by eri-trabiccolo** [comment]
Let's keep an eye on this recently added CSS property
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior

It might totally replace our js (looked for polyfills too, they seem to be too big, so not really worthwhile, but we can maybe async their loading)

**Comment by eri-trabiccolo** [comment]
In the coming months we might think about the use of
`html {scroll-behavior:smooth}`
which basically uses the native browser "smooth scroll" when clicking on a link to an anchor.

When applied, in fact, it conflicts a little bit with the jQuery('html,body').animate we use in our backToTop code (the js used to implement the back to top button feature):
the page starts scrolling very very slowly and then accelerates, not really beautiful.
This is something we can fix for our code, but made me think about possible conflicts with 3rd party plugin, so let's think about this a little bit more.
