### ISSUE TITLE
Customizr can break the home page when home displays a static page but no page on front has been set

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1666]
https://wordpress.org/support/topic/search-results-dont-display-with-customizr/

**Comment by eri-trabiccolo** [comment]
One hour ago I've seen that the 404 redirects to the home page as well on the user websites.
He now switched to 2019, and the issue is still there. So we can exclude the Customizr theme as source of the issue.

**Comment by ghost** [comment]
yep, I'm actually working on this problem right now. User provided credentials. Still not sure about the cause...
Can you confirm that the following are ok on your side ( on your dev site ) 
- add section to home and customize it quickly so you generate a stylesheet ?
- publish
- perform a search => does it display the home sections ? Is the home css stylesheet requested ?
- same with 404

thx

**Comment by eri-trabiccolo** [comment]
I did what you requested.

- perform a search => does it display the home sections ? Is the home css stylesheet requested ?

No it doesn't display the home sections but the search results, as expected.
No the home css stylesheet is not requested as we're not in home, as expected.

- same with 404

The 404 "is broken": 
does it display the home sections ? => YES
Is the home css stylesheet requested ? => YES

**Comment by eri-trabiccolo** [comment]
@Nikeo ^

**Comment by ghost** [comment]
can we skype ourselves quickly ?

**Comment by ghost** [comment]
**Solved : this was related to the home page setting.**
When using the customizr page, it is possible to set home as static page, without specifying a page on front id. Normally WordPress automatically switch to home as list of posts. But in the Customizr theme, the automatic correction is not done.
=> this can lead to situation where the search and 404 contexts are broken, and _redirected_ to the is_home() context.

**Comment by ghost** [comment]
Probably solved by https://github.com/presscustomizr/customizr/commit/31be718e886afff9b7acde92dc0acf787dfe0752
