### ISSUE TITLE
WooCommerce cart style issue when using several variations

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1667]
This is due to the fact that WC renders these variations with `dl`, `dd`,` dt` 
and the modern style has a special CSS those elements which makes the cart table, mostly when the variations have long "names" (`dl dt` do not wrap), and possibly overflow the "container" (box).

We cannot make miracles and make the cart tables very beautiful but at least we can avoid some messy appearance if caused by some CSS we can certainly avoid to apply there.

reported:
https://secure.helpscout.net/conversation/757306548/167270?folderId=607709

**Comment by ghost** [comment]
Thanks for the PR
