### ISSUE TITLE
Plugin conflict with Contact Form 7 - PayPal Extension

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1677]
https://secure.helpscout.net/conversation/768917496/167614/?folderId=610157

Hello, I noticed that the Contact Form 7 plugin - PayPal extension does not  work with your Customizr theme. It works regularly with other themes. Is  it possible to get help to solve the problem? The plugin conflicts and  does not redirect to the PayPal site for payment. Thank you.

--
# SITE_URL: https://www.laruotadihecate.com

**Comment by eri-trabiccolo** [comment]
I don't seem to be able to reproduce this issue on my end.
I think we need more info, like ... what happens!? :D

**Comment by ghost** [comment]
Thanks for testing.
I've already asked for more informations.
