### ISSUE TITLE
Plugin conflict with Charitable Plugin the PayFast gateway

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1678]
I have been using the Customizr theme for many of my websites, but I now have a problem with my current site. I hope you can assist as I don't want to use another theme.

I have the Charitable Plugin to accept donations, and have installed their plugin for the PayFast gateway. The problem is when you click on the Donate button it does not take the person to the payment gateway, it goes to a different page. We have tried other themes and this problem does not occur. Please can you advise whether there is something I can do without using a different theme?

Here is the required site info:

# SITE_URL: https://thefamilyofdunns.com
# HOME_URL: https://thefamilyofdunns.com

**Comment by eri-trabiccolo** [comment]
the site is under maintenance :/
