### ISSUE TITLE
Modern: Do we want to show the slider arrows in mobiles?

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1680]
Historically we hide them in mobiles (is_mobile).
maybe we can make this optional for the modern style?

reported here:
https://wordpress.org/support/topic/slider-arrows-not-showing-on-mobile-2/

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
let's schedule this for the next release. in your column ( no comment )

**Comment by eri-trabiccolo** [comment]
ahah, ok.
Just remove the is_mobile check then or do we want the option (and handle this in CSS)?

**Comment by ghost** [comment]
Well, in fact I prefer that we stick to the current behaviour.
I'll simply replace the is_mobile check by a CSS display none that user would be able to override.

**Comment by ghost** [comment]
but by default the arrows will be hidden on mobiles
