### ISSUE TITLE
GT metrix says placeholder images miss width and height attributes + double slash in url path

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1684]
I've also noticed that the url of the image has 2 slashes

> 
> Hello,
> 
> GTMetrix says
> The following image(s) are missing width and/or height attributes.
> 
> https://cockie.de/wordpress/wp-content/themes/customizr/assets//front/img/thumb-standard-empty.png (Dimensions: 300 x 300)
> 
> How or where can i change this?
> 
> The page I need help with: https://cockie.de
> 

@eri-trabiccolo is there a quick patch for that ?

![2019-02-14_10-05-34](https://user-images.githubusercontent.com/3038156/52775634-69a56d00-3040-11e9-9a04-cae3f8624cf4.png)

**Comment by eri-trabiccolo** [comment]
Yeah, I'm sure there is, but I honestly do not think the two slashes is a problem at all :D

**Comment by ghost** [comment]
yeah the two slashes is not a real problem. it's just easy to fix :)
