### ISSUE TITLE
Woocommerce conflict ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1694]
https://wordpress.org/support/topic/woocommerce-css-conflict-2/#post-11235468
> Hello. I’m sorry if there is a similar topic already, but I couldn’t find one.
> 
> I’m building a new Woocommerce website on Customizr and noticed a problem with the CSS files. The problem is with the CSS and can be seen on the special woocommerce pages (cart, account, checkout, etc). The website is still on localhost, but I can transfer it if you need that in order to assist me.
> Screenshot: https://goo.gl/64ZJz3
> 
> As you can see on the screenshot, the layout looks really bad. I tried making a child theme and customizing some of the CSS rules, but I keep finding the problem on other pages. I also tried deactivating all plugins (except Woocommerce), but the problem is still at hand. I am using Customizr version: 4.1.28.
> 
> PS: Your theme is great! I don’t know why I just found out about it.
> 
> Thank you in advance.
> Best regards,
> Nick

@eri-trabiccolo can you take a look when you'll have the time ?
We can also do an end-of-the-week quick chat this afternoon if you can.

**Comment by ghost** [comment]
![mu4dwa2wv7wpefz7of3a2a_e1cdmtayix_lv9au-exk7eq3sli5wczt9z_tysmmmklr37n3dqmcjgisnguwn w1920-h954](https://user-images.githubusercontent.com/3038156/53243287-a5c37800-36a7-11e9-89ed-966f9c050c2c.png)

**Comment by eri-trabiccolo** [comment]
Cannot reproduce it to be honest:
![schermata 2019-02-22 alle 14 32 32](https://user-images.githubusercontent.com/7689242/53245742-da86fd80-36ae-11e9-850a-114fab689adf.png)


Let me know about the chat.

**Comment by ghost** [comment]
OK Thanks for the screenshot.
About the chat : if you are available, let's say in a few minutes, 15:15 ?

**Comment by eri-trabiccolo** [comment]
I am, anyway I've found something.
The user has put the [woocommerce_my_account] shortcode into a gutenberg preformatted block.
Not sure why.
