### ISSUE TITLE
Various minor CSS potential improvements

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1695]
reported here : https://secure.helpscout.net/conversation/788538830/174926?folderId=607547

> I've just upgraded to Customizr Pro 2.1.18 and have selected the Modern set versus Classic.
> 
> I'm having troubles finding where to make a few changes:
> 
> Right Sidebar Issues:
> 
> I would like the right sidebar to be Left Aligned (titles and content). I found where to set the alignment for the titles and links, however, I cannot find a way to Left Align the content under the Blog Categories (the Category widget).
> I wanted to change the font and size for the right sidebar content and titles. I've changed the titles with no problem, and have changed the font for the links under Recent Posts, but again cannot find any place to change the font for the content under the Blog Categories heading.
> 
> You May Also Like:
> 
> I also cannot find where to change the font style and size for the "You May Also Like" headings. Currently, that heading is very large and is in uppercase.
>  I also cannot find where to change the font style and size for the text within the thumbnail under the You May Also Like heading - that text is really large.
> 
> Footer:
> 
> When I upgraded to this newest version of Customizr Pro, I also noticed that the Blog Categories in the Footer are now all in uppercase letters. I cannot find a place to change this text back to upper- and lowercase to match the other text in the footer. It's strange that this text is in all uppercase, when the text in the right sidebar is not in uppercase.
>  I found where I can change the font style and size for the Footer credits, but there doesn't seem to be a place to change the font style and size of the text within the footer itself. Right now, that text is very small and not very bright. I'd like to make the text a little larger and more bold.
> 
> Page Numbers:
> 
> The page numbers at the very bottom of the blog 2-column grid are also very small. I cannot find a place to customize the font style or size for this area.
> 
> 
> I've searched through all of the Customizr Pro customization options and simply cannot find where to make the changes above. I'm not sure if I'm just missing this, or if these areas were somehow omitted in the upgrade, or if this is a "bug" in the theme.
> 
> The things I am trying to customize seem to be standard customization issues, since similar customization can be done in other areas. I'm really hoping you can help.
> 
> I really like this new upgrade to Customizr Pro and am anxious to finish customizing my website.
> 
> Thank you for any help you can provide.

@eri-trabiccolo we can schedule a point later today in the afternoon if you can.
This issue will be discussed and other devs on Nimble
Let me know.

**Comment by eri-trabiccolo** [comment]
Ok, let's fix a schedule.
About the first issue as already proposed somewhere :D we can add an option to "revert" the theme default design, see also 
https://github.com/presscustomizr/customizr/issues/1280#issuecomment-341355785

Category Widget list items in whatever sidebar is in uppercase (design choice, why?! not sure :D)

For the rest... font styling stuff achievable with WFC, of course we can add new presets for them.
