### ISSUE TITLE
Would it be possible to add support for WebP Images in slider ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1696]
reported [here](https://secure.helpscout.net/conversation/789386622/174943?folderId=607547).
WordPress does not officially support this format yet : https://codex.wordpress.org/Uploading_Files

There are plugins like https://wordpress.org/plugins/webp-express/

> Hi I recently was trying to get WebP images working with my customizr pro theme. I added this code to the themes function.php for me to be able to upload webp:
> function webp_upload_mimes( $existing_mimes ) {
> // add webp to the list of mime types
> $existing_mimes['webp'] = 'image/webp';
> // return the array back to the function with our added mime type
> return $existing_mimes;
> }
> add_filter( 'mime_types', 'webp_upload_mimes' );
> However once the images were uploaded they are not working correctly in the slider. I have an active slider on my homepage but it isn't working as the images are not displaying properly. I found that legacy wordpress (before gutenberg) was adding these lines to webp images: width="1" height="1" which made them not display. I suspect that the slider for this theme is not properly configured to interpret/display webp images. I was hoping you could tell me what code to add where, to get webp to work on the slider.

**Comment by eri-trabiccolo** [comment]
I've added some webp images (https://developers.google.com/speed/webp/gallery1) to a slider 
and could not reproduce any particular issue.
Yes I can reproduce the width/height set to 1, but that's a wp problem, we use its api to retrieve the image src.

Furthermore the webp images in the slider (the source images, e.g. https://davidlionheart.com/wp-content/uploads/2019/02/kananaskis_valley_slider.webp) seem to look fine in firefox but not in chrome.

**Comment by ghost** [comment]
OK Thanks for this feedback.

What I would like to asses is :, knowing that WP does not officially support this format,  would there be something to add in Customizr and Hueman in order to facilitate the use of webp images ?

Weird about the Chrome issue. Supposed to be supported.
![2019-02-28_10-02-59](https://user-images.githubusercontent.com/3038156/53554460-181cd800-3b40-11e9-9614-f3569e038ef6.png)

**Comment by eri-trabiccolo** [comment]
Sorry but I haven't said that Chrome doesn't support webp.
I can see these with Chrome:
https://developers.google.com/speed/webp/gallery1

But I cannot see this 
https://davidlionheart.com/wp-content/uploads/2019/02/kananaskis_valley_slider.webp
with Chrome, or at least with my version of Chrome, but I can with Firefox.

I don't think the slider has something to do with this to be honest.

> would there be something to add in Customizr and Hueman in order to facilitate the use of webp images ?

Except for allowing this mime type you mean?

**Comment by eri-trabiccolo** [comment]
Oh wait, if in chrome if I open this:
https://davidlionheart.com/wp-content/uploads/2019/02/kananaskis_valley_slider.webp
I see nothing, but if I hard refresh the page I can see it.

Note that I'm still not talking about the slider.
 :)

**Comment by ghost** [comment]
I see it and then it dissapears on chrome.

> would there be something to add in Customizr and Hueman in order to facilitate the use of webp images ?

Yes I mean, if I'm a developer and I add the webp mime type to Hueman and Customizr, and it doesn't work on Firefox, what do I have to do ?

**Comment by eri-trabiccolo** [comment]
Ah, ok I see, something like the opposite of the retina js.
Generate jpg from webp, and serve them when the browser doesn't support webp?

**Comment by ghost** [comment]
OK. Thanks
So about webp our reply will be : 
1- this is not yet supported by WP
2- if you are a developer you can add support for it and it will work with Hueman and Customizr
3- be aware that some browsers do not support this format.

OK with that answer ?

**Comment by eri-trabiccolo** [comment]
Yes as long as I can see.
Anyway the problem with that user images are the images themselves, sometimes show up in chrome sometimes not, most of the times not, that's weird.

**Comment by ghost** [comment]
OK.
yes, no explanations about this.
