### ISSUE TITLE
PHP fatal error using PHP < 5.4 because of the use of the short array syntax

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1697]
reported here:
https://wordpress.org/support/topic/updated-and-now-my-website-is-not-working/

see:
https://github.com/presscustomizr/customizr/blob/v4.1.29/core/init-base.php#L1146

We support PHP 5.3 too:
https://github.com/presscustomizr/customizr/blob/v4.1.29/functions.php#L16

@Nikeo ^

**Comment by ghost** [comment]
aaah damn it.
OK I'm on it thanks
