### ISSUE TITLE
Remove title attribute "Permalink To" on thumbnails links in post lists

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1698]
As fixed for Hueman, let's also do it for Customizr + pro addon
https://github.com/presscustomizr/hueman/issues/763

**Comment by eri-trabiccolo** [comment]
Done in #1745
also took the chance to remove the title attribute where totally superfluous, e.g. in post title links.
The PR contains two commits, the second one applies the title attribute removal to the featured pages thumbnail links too, which I think is something we wanted as well, but in case you don't it'll be pretty easy to revert just that commit.

**Comment by ghost** [comment]
OK. perfect yes. thanks
