### ISSUE TITLE
Plugin conflict: Elementor menu not working

### ISSUE THREAD

**Issue by emran1** [Nikeo/customizr#1701]
https://wordpress.org/support/topic/poder-anadir-un-menu-elementor-al-header/

**Comment by eri-trabiccolo** [comment]
Not sure how to reproduce this.
What's the Elementor menu? Is it part of the pro?

**Comment by ghost** [comment]
@eri-trabiccolo this is not urgent. We'll discuss if it needs further investigation. thanks
