### ISSUE TITLE
Wrong Gutenberg editor size.

### ISSUE THREAD

**Issue by PeopleInside** [Nikeo/customizr#1705]
Hi, i truly believe this issue is not of the theme but someone of the Gutenberg editor say the issue is the theme so i am opening this for check with you.

The Gutenberg editor is so small in the center of the page, this should be improved with CSS:
```
.wp-block {
	max-width: 98%;
}
```
You can find more details here: https://github.com/WordPress/gutenberg/issues/14405

I don't believe this issue is from the theme as i found this issue on different themes... but seems my issue in Gutenberg has been closed as question and has been not recognized as bug.

**Comment by youknowriad** [comment]
Let's continue discussing in #14405 and if there something that needs to happen in Gutenberg it will be reopened.

**Comment by ghost** [comment]
@PeopleInside thanks for reporting your problem.
We have added support and compatibility patches for Gutenberg as you can see in those issues : https://github.com/presscustomizr/customizr/issues?utf8=%E2%9C%93&q=gutenberg
This includes a specific patch for the editor size : https://github.com/presscustomizr/customizr/pull/1648/commits/01124dc98e5c4d8294ab4620803e71e8580b6de4
I'm closing this issue for the moment.
Thank you
