### ISSUE TITLE
Plugin conflict with mobile menu: Jetpack

### ISSUE THREAD

**Issue by emran1** [Nikeo/customizr#1706]
https://wordpress.org/support/topic/mobile-not-displaying-properly-2/

**Comment by eri-trabiccolo** [comment]
Hi @emran1.
Thanks for reporting, though as I wrote on the forum, I don't see a compatibility issue there.
But let's wait for the user feedback.

**Comment by eri-trabiccolo** [comment]
Closing this after the user feedback which confirms there's no compatibility issue :)
