### ISSUE TITLE
Mobile submenus should expand even when the parent item is not a link

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1712]
> Hi, I read the guide on how to build a menu but I can't solve it. I created the main menu for my site and it works fine. The only thing I don't like is that to open the submenus with mobile devices you have to click on the arrow. I would like the menu to expand even by clicking on the word as it happens in your demo. How can I do? thank you
https://pavimentomoderno.it

**Comment by eri-trabiccolo** [comment]
https://github.com/presscustomizr/customizr/blob/dev/assets/front/js/_parts/_parts_modern/_main_dropdowns.part.js#L305

which means that basically if the user leaves the "#" as menu item URL it works as he/she wants.

Anyways we can "enhance" that code to include even the no href case.

To be honest, though, links without href are supposed to be not clickable...

**Comment by ghost** [comment]
ok thanks for the quick feedback.

yes that's right, links without href are not supposed to be clickable... but, you'll agree that it's simpler sometimes to make our own interpretation of the W3C specs, than to teach thousands of users a rule they don't really care about ... :)

**Comment by eri-trabiccolo** [comment]
Well yes but,
1) When you create a menu item WP forces you to specify an URL: to have a menu item without URL you have firstly create it with an URL, then add it to the menu, then expand the menu item in the menu and then remove the URL and save it;
2) links without URL are NOT "navigable" with the keyboard (=> accessibility issue);
3) we have to add more code to allow something which is not really good in terms of w3c specs, accessibility, and that requires the user do all the steps in 1) why should he/she? what's the purpose? who guided this user into this practice?

But anyway, as said, no problem to add more code for that. ;)

**Comment by ghost** [comment]
yes we'll adapt the code. simpler than explaining all your ( totally relevant ) points.

**Comment by eri-trabiccolo** [comment]
same in Hueman, as I ported the Customizr code there:
https://github.com/presscustomizr/hueman/blob/dev/assets/front/js/_parts/_main_userxp_1_mobile_menu_toggle.part.js#L239
