### ISSUE TITLE
Related post not disabled despite selecting the "disabled" option 

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1713]
https://secure.helpscout.net/conversation/808034735/216686?folderId=607547
@eri-trabiccolo when you'll have the time, can you let me know if this is something you can reproduce.
I'm not able to reproduce it for the moment.

**Comment by eri-trabiccolo** [comment]
I was opening the issue.
I'm going to push a fix.
My fault, again. Introduced with the Events calendar tickets compatibility fix. I disable the related posts in events the wrong way.

reported here too:
https://secure.helpscout.net/conversation/807601639/216682?folderId=607544
(here the user talks about a slider issue tied to the featured pages, which I don't understand though)
