### ISSUE TITLE
Menus => disable by default  the styling ( underline, background, ... ) of contextually active item

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1718]
![2019-03-23_10-43-16](https://user-images.githubusercontent.com/3038156/54864508-96902280-4d58-11e9-8d78-9f421b394a0e.jpg)

- add a new check option in header > navigation menus. disabled by default. even for old users
- option title : Highlight contextually active menu items

Important when testing => make sure it is disabled for all contextually active candidates : ancestor, parent, etc

**Comment by eri-trabiccolo** [comment]
Should be 2-ms only.

**Comment by ghost** [comment]
@eri-trabiccolo I assign it to you. When you can.
spec updated

**Comment by eri-trabiccolo** [comment]
Just one more thing.
At the moment this option:
**Global Settings -> Formatting -> Animated underline effect on link hover**

controls also the underlining for the current menu item.
Meaning that, if that option is disabled, the current menu item "underline" is not present.

I would say that with the introduction of the new option the current menu item underline should not depend on the **Global Settings -> Formatting -> Animated underline effect** on link hover anymore

Agreed?!

**Comment by ghost** [comment]
yes agreed thanks.

**Comment by eri-trabiccolo** [comment]
(I pushed a first version, which is not a PR yet as I need to do some more tests)

**Comment by eri-trabiccolo** [comment]
Test ran fine on my side.
The two options:
Global Settings -> Formatting -> Animated underline effect on link hover
and
Header -> General design settings -> Highlight contextually active menu items

are totally decoupled.

**Comment by ghost** [comment]
also reported here : https://secure.helpscout.net/conversation/816950762/216807?folderId=607547
