### ISSUE TITLE
Addition of new ‘wp_body_open’ hook (?!)

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1722]
https://make.wordpress.org/themes/2019/03/29/addition-of-new-wp_body_open-hook/

**Comment by ghost** [comment]
Let's implement tadlock solution in comments https://make.wordpress.org/themes/2019/03/29/addition-of-new-wp_body_open-hook/#comment-43714

> I’m pretty sure the Theme Sniffer is going to complain about unprefixed functions. Themers can just do this for the same:
> 
> do_action( 'wp_body_open' );
> 
> Or this for just back-compat:
> 
> if ( function_exists( 'wp_body_open' ) ) {
> 	wp_body_open();
> }

**Comment by ghost** [comment]
in your devs @eri-trabiccolo 
we can chat about this during the next dev skype

**Comment by ghost** [comment]
implemented with a shim to prevent fatal error
https://make.wordpress.org/core/2019/04/24/miscellaneous-developer-updates-in-5-2/
