### ISSUE TITLE
Is Customizr theme outputting the correct markup for Google structured data when the option to show the update date is enabled?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1726]
![2019-04-03_21-13-13](https://user-images.githubusercontent.com/3038156/55506346-72d0b480-5655-11e9-8c5f-3f2b3d51e42a.jpg)

reported here : https://secure.helpscout.net/conversation/818376242/216831/?folderId=607547

> 
>  hentry Date of updated and published is the same
> When I checked a website with Google's structured data test tool, hentry's updated and published dates are the same.
> 
> The actual update date is March 21, 2019.
> Is Customizr theme outputting the correct markup when the option to show the update date is enabled?

**Comment by ghost** [comment]
This is how the most popular magazine handles it

`<span class="td-post-date"><time class="entry-date updated td-module-date" datetime="2017-03-22T05:47:36+00:00">Mar 22, 2017</time></span>`

https://demo.tagdiv.com/newspaper/the-most-anticipated-charter-flights-in-the-canary-islands/

![2019-04-03_21-49-59](https://user-images.githubusercontent.com/3038156/55508598-85012180-565a-11e9-95d0-ab312876c5d8.jpg)

**Comment by eri-trabiccolo** [comment]
In the screenshot the two dates are different BUT the published date (the one with the `.published` class, which makes is a structured data) has also the `.updated` class, which, I think creates the issue: two `updated` data, probably only the first is taken into account.

I think the `updated` class has been added to respond to address a common "issue" (request), back in the past (in the classical style), which had to do with the `required` structured data of an `hentry`, see http://microformats.org/wiki/hentry.

The difference with the classical style is that the "published" date element in the classical style has no `published` class, while it has an `update` class, this is still wrong as you can still have an `updated` data referring to a "wrong" data, and still have 2 `.updated` elements as well.

So we need to test what is really needed and make sure what is needed is always present despite the user visual choice, I think. I mean, if the user doesn't want to display the update date element we still need the `.updated` and it still has to be consistent, referring to the actual updated date.

**Comment by eri-trabiccolo** [comment]
> https://demo.tagdiv.com/newspaper/the-most-anticipated-charter-flights-in-the-canary-islands/

I see what you mean, and probably having only one `.updated`, and no `.published` (which is not mandatory), it's enough for google, but still consider that in the link above, the date element with `.updated` says: 
`"2017-03-22T05:47:36+00:00"`
while the actual update date of that article is 
`"2018-06-15T13:12:25+00:00"`
(as you can see from the source, look for: `<meta property=og:updated_time content="2018-06-15T13:12:25+00:00" />`)
 
I think we have to decouple the structured data (we can always print and not display them) from what we refer to as post "metas" whose presence is more a visual thing than anything else.

**Comment by ghost** [comment]
thanks for the feedback.
yes I remember the trick about adding updated.

To put it simple : the problem to solve is : what is the correctly written line of code that we have to print on the page so Google reads a correct update date info.

I have no real clue what Google uses on the page to determine the structured data. This needs research and test.
We'll discuss it during our next chat.

**Comment by eri-trabiccolo** [comment]
Yeah that's what I tried to say :)
We need to know what google wants, which means what's the correct structured data expected for an .hentry (see the link above).
Hence we have to print this data anyways whether or not the user wants to display the update date meta (a similar thing with happen for the author, if the user doesn't display it).

**Comment by ghost** [comment]
yes !

**Comment by eri-trabiccolo** [comment]
Maybe if we don't print any "data" related stuff would be fine too, and suggest the Yoast SEO plugin it would be enough:
https://yoast.com/yoast-seo-11-0/#utm_source=wordpress.org&utm_medium=referral&utm_campaign=release-11-19
that's their field :D

**Comment by ghost** [comment]
@eri-trabiccolo @emran : from now on, we recommend Yoast SEO to manage the Google structured data markup in the Customizr theme.
Thanks
