### ISSUE TITLE
Bug Latest theme version: Featured images hidden from featured pages

### ISSUE THREAD

**Issue by emran1** [Nikeo/customizr#1731]
https://secure.helpscout.net/conversation/821689369/216872?folderId=1845241

I also replicated the issue at my end as well using latest theme version:

http://prntscr.com/n9e4y8

Featured image appears for a second on page load and then disappears:

http://wordpress-187399-635064.cloudwaysapps.com/

**Comment by eri-trabiccolo** [comment]
Thanks for reporting @emran1 
see also #1730
