### ISSUE TITLE
New problem with the letters "span" used in categories

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1734]
## USER PROBLEM

> I had this problem 5 years ago and after an update it is back:
> 
> I have a travel blog and one of my catogories is 'Spanje', the Dutch word for Spain. 

> All blogposts with that category have a problem with the 'span'. There is no space left between the text and my right side bar. This is because 'Spanje' is my only category with the word 'span' in it, which causes a bug/fault in the theme. Could you please solve this?

> This problem occurs in every browser type.
> My website: https://www.travellust.nl/

## TECHNICAL REASONS
@eri-trabiccolo We know this problem. https://github.com/presscustomizr/customizr/issues/521

You can see it on this page : https://www.travellust.nl/doen-op-ibiza/

![2019-04-12_11-30-50](https://user-images.githubusercontent.com/3038156/56028150-cf983300-5d17-11e9-844d-9b47c313a144.jpg)

The issue occurs with classical and is caused by the following bootstrap rule
```
[class*="span"] {
    float: left;
    min-height: 1px;
    margin-left: 30px;
}
```

generated here : https://github.com/presscustomizr/customizr/blob/dev/inc/assets/less/bootstrap/mixins.less#L593

## POSSIBLE SOLUTION
A possible solution would be to replace the original CSS rule by

```
.span1,.span2,.span3,.span4,.span5,.span6,.span7,.span8,.span9,.span10,.span11,.span12 { 
    float: left;
    min-height: 1px;
    margin-left: 30px;
}

```
Either with a Less formula or hard coded in the less file.
@eri-trabiccolo any opinion ?

**Comment by eri-trabiccolo** [comment]
I'm with you, it should be fine.
