### ISSUE TITLE
feature request | preload CSS in customizr theme from-support-form

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1736]
https://secure.helpscout.net/conversation/825892072/216939?folderId=610157

http://aachenerkinder.de/

> Hello,
> I just did a test of our website aachenerkinder.de on PageSpeed Insights with the following result.
> Question to the developers of Customizr: Wouldn't it make sense if the CSS files mentioned were loaded by the Customizr theme via preload, as described in the following link, in order to get better loading times ?

![2019-04-13_10-57-44](https://user-images.githubusercontent.com/3038156/56077319-03885c80-5ddb-11e9-8edd-9086d7bd57b3.jpg)

**Comment by hagege** [comment]
Hello, 
can you tell me if you are still working on a solution for this (small) improvement ?
That would be great, but not dramatically important.
Thanks and best regards,
Hans-Gerd
