### ISSUE TITLE
Add a help button linking to doc

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1737]
![2019-04-17_09-23-55](https://user-images.githubusercontent.com/3038156/56269107-355b3500-60f3-11e9-9fd8-66726705cc51.jpg)

**Comment by eri-trabiccolo** [comment]
Is it allowed?
I remember that we had to remove it from the adminbar, but maybe that's a forbidden area and this one is not :D

**Comment by ghost** [comment]
There's no clear requirement preventing those type of additions in the customizer. It's always the same question to me, does it impact the user experience? In this case, clearly no. It's not plugin territory. It's not upsell. I don't really see why it should be forbidden.
If the TRT says it's not authorized then we'll get rid of it.

**Comment by eri-trabiccolo** [comment]
For what it's worth... I'm with you ;)
