### ISSUE TITLE
New option of 3.3.26 not translatable

### ISSUE THREAD

**Issue by JTS-IL** [Nikeo/customizr#174]
After installing 3.2.26 discovered that the new options:
-Galleries
-Post/page navigation
and their sub options are not available for translation.

please add the relevant phrases for translation :-)

**Comment by eri-trabiccolo** [comment]
Hello Yaacov ,
do you mean that they're not loaded in the .po file?
If you use poedit to make your translations you can still update the catalog from the sources, as they're already predisposed for the translation.

**Comment by JTS-IL** [comment]
Yea, I meant it"s not in the .po file.
After each build I checked the PO file to see if there are changes, in this way I can translate the new phrases before the new Verizon is released. I will do the current translation soon. What is the best way to be updated on new or edited phrases?

**Comment by eri-trabiccolo** [comment]
Well, I use poedit and update the catalog from the source every time...

**Comment by JTS-IL** [comment]
:-)
I use poedit too, but didn't use the update from source...
Will start now.
Can I define the source to be the github?

**Comment by eri-trabiccolo** [comment]
Mmm,
the source is specified in the catalog properties -> Sources paths
Then I click the Update button -> http://i59.tinypic.com/29ly5b9.jpg
:D
