### ISSUE TITLE
.czr__r-w16by9 {   @include czr__responsive-wrapper( 16, 9 ); } => breaks video post format

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1742]
![2019-04-25_11-40-10](https://user-images.githubusercontent.com/3038156/56726448-083fff80-674f-11e9-915f-ed33a5535823.jpg)

This can be reproduced when creating post with the video post format.

https://github.com/presscustomizr/customizr/blob/065e60a1e3d0a1a2538de98c7b574c8dbd78812d/assets/front/scss/0_1_base/_utilities.scss#L119

@eri-trabiccolo any idea why? Can I assign this issue to you ?
Thanks

**Comment by eri-trabiccolo** [comment]
can you point me to the support request?
Because that might be a plugin conflict.

that's OUR way to have responsive videos for the video post formats only.
see: https://demo.presscustomizr.com/video-post/

there's no bug in that.

To be more clear, the problem is that, on that website, the actual video iframe is wrapped into a div (`.wp-video`), this happens, I think, because of some plugin filtering the WP embed.

That's my guess...

**Comment by ghost** [comment]
No plugins enabled. This is something I discovered on a personal site.

But OK, I think we designed a solution working for vimeo and youtube only.
But it breaks when embedding a self hosted mp4 video or a facebook video.

**Comment by eri-trabiccolo** [comment]
perfect, I'm on it then.

**Comment by eri-trabiccolo** [comment]
Ah wait, didn't test the facebook video thing, how can I?

**Comment by eri-trabiccolo** [comment]
Ok found it, I'm about to force the previous commit.

**Comment by ghost** [comment]
use this one for example : https://www.facebook.com/cerveauxnondisponibles/videos/335019190485345/

**Comment by eri-trabiccolo** [comment]
you're creepy man :P 
The latest commit is fine ;)

**Comment by eri-trabiccolo** [comment]
Naa it's not, doesn't work fine with fb... meaning that the video won't be responsive.
This makes things a little harder, and means that before "wrapping" into a responsive div we might need to know the source.

I close the PR for the moment.

I think we will end up making only wp-video and more standard video embeds (youtube, vimeo) to be responsive, skipping the others.

**Comment by ghost** [comment]
> I think we will end up making only wp-video and more standard video embeds (youtube, vimeo) to be responsive, skipping the others.

I'm fine with that

**Comment by eri-trabiccolo** [comment]
Ok, cannot make wp-video responsive, so only videos which are iframes will be responsive.
