### ISSUE TITLE
User reports an instable body font setting

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1747]
Reported by a user
> Eyerytime I change the size of the body font it set it back after changing anything else in customizr.

![google_fonts](https://user-images.githubusercontent.com/3038156/57278451-c3995a00-70a6-11e9-9540-a63170d8f2c6.jpg)

@eri-trabiccolo can you reproduce the problem ?
Issue reported here : https://secure.helpscout.net/conversation/845829765/217182/?folderId=607547

**Comment by ghost** [comment]
hello @eri-trabiccolo, hope you're doing good.
No emergency about this. When you can !

**Comment by eri-trabiccolo** [comment]
@Nikeo I cannot reproduce the issue :/

**Comment by ghost** [comment]
OK @eri-trabiccolo thanks.
( I'll be mid-off today ... )

**Comment by eri-trabiccolo** [comment]
Ah but maybe the "issue" is another one.
Basically the font-size changes are applied with the `postMessage` transport method and in pixels.
While in front we build up the CSS rules in em, so they might not exactly correspond (if you think about small variations): when changing a different setting without having saved the font-size changes, the live preview reloads applying the front method.

side note: I see we allow half pixels, e.g. 20,5 but it's still saved as 20.

**Comment by ghost** [comment]
OK
