### ISSUE TITLE
Remove offset for 2nd level submenu in desktops

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1748]
https://secure.helpscout.net/conversation/851362855/217247/?folderId=607547

> Hi team, The 2nd level menu(see the screenshot) is offset from main menu,  which makes a constant complaint from our customer, they always missed  the 2nd level menu is so easy to disappear, could we fix this?  Thank you,  Haoyu
> --
> 

![enu](https://user-images.githubusercontent.com/3038156/57604724-30a86600-7565-11e9-8456-10d40951eba0.png)

**Comment by ghost** [comment]
@eri-trabiccolo are you available for a quick chat this morning ?

**Comment by eri-trabiccolo** [comment]
yes @Nikeo

**Comment by ghost** [comment]
OK I'll be ready to chat in 15 mins if that works for you !

**Comment by eri-trabiccolo** [comment]
@Nikeo it does! 👍
