### ISSUE TITLE
Conflict with Elementor ( video ) Menu don`t show when scrol down

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1750]
video => https://www.loom.com/share/86a0bb122d1b42aca6bed6b50cf25610

I have found it`s works well in firefox.. but not in chrome.

I have also updated update Elementor pro to Version 2.5.8 |
but has no effect.

reported here https://secure.helpscout.net/conversation/845489124/217175?folderId=607547

**Comment by eri-trabiccolo** [comment]
I'm not able to reproduce the issue in local with Elementor (not Pro).

Also, it happens in the home only because of the slider (so the slider there is what creates the actual issue, not sure why).

Elementor (not Pro) doesn't provide a slider module...
