### ISSUE TITLE
Remove the H1 of the site title

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1760]
related to #1406
related to #1431

reported again here https://secure.helpscout.net/conversation/880785357/217733?folderId=607547

@eri-trabiccolo we had the discussion several times, let me know if you see any technical possible regression

**Comment by eri-trabiccolo** [comment]
What I see is that several other users requested the h1 tag e.g. in home when displaying latest posts and a logo image, why? always for the same reason: "seo" :/

If we remove it I'm certain other people will complain about that.

Maybe we have to think about introducing an option, at least for the home page.

**Comment by ghost** [comment]
You know what ?
SEO is just the biggest bulls*** of the web.
Did I just say that? Oh yes.

**Comment by JTS-IL** [comment]
Please allow me to disagree.
The H1 is not just for SEO, It's very important for accessibility, specially for those who cannot read, and use screen readers. They have the option to skip through the hierarchy of the headers, and that's why a page has to be with only one H1.
Since Google, and other search engines give significant weight to accessibility, having the right hierarchy gives a page better score.

**Comment by ghost** [comment]
Thanks for jumping in @JTS-IL . Indeed, the accessibility question is to me more relevant than SEO considerations.
If we remove the H1 tag for the logo / title, there will be pages, like post lists, where there won't be H1 tag. So the heading's hierarchy will start from an inferior H, typically H2, but hierarchy navigation will still be possible. So I don't see it as a problem for accessibility. Should I ?
In terms of SEO, there will be pages without H1, which is not optimal for robots. But on the other end I don't think it really make sense to keep telling Google that all pages have the same H1, the site title, as we do right now.
So my idea is to remove the H1 tag for the title for the moment. Then if we get many SEO related complaints about this missing H1 on some pages, we could explore an option allowing users to wrap their site title inside a H1 tag on home and all "H1-less" pages.

**Comment by JTS-IL** [comment]
As I remember, there was an issue with multiple h1 in the man slider (which I fixed locally on my sites).
A page must have one, and only one h1, and it should be the post or page title, not the site title.
webpages that are not post or 'page', should have some kind of 'system-generated' h1, like archives or 404 etc.

**Comment by eri-trabiccolo** [comment]
Also reported here: https://wordpress.org/support/topic/how-to-remove-multiple-h1-tags/
