### ISSUE TITLE
For new users, set the default global layout to full width instead of left sidebar

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1763]
@eri-trabiccolo to be discussed during our next dev chat

**Comment by eri-trabiccolo** [comment]
It should be already so...
https://github.com/presscustomizr/customizr/blob/dev/core/core-settings-map.php#L1337

**Comment by ghost** [comment]
ah yes, that's implemented.
This site made me doubt : https://wpbeta.oceanodunes.org/2018/03/18/offshore-silica/
OK. thanks
