### ISSUE TITLE
Feature request: Breadcrumbs Showing child category also

### ISSUE THREAD

**Issue by emran1** [Nikeo/customizr#1765]
https://secure.helpscout.net/conversation/896085816/217925?folderId=1845241

**Comment by eri-trabiccolo** [comment]
Hi @emran1 
thanks for reporting this.
Not sure it depends on the theme, see the demo:
https://demo.presscustomizr.com/product/happy-ninja-2/
There you can see the child category too...

Maybe the user is using the Yoast SEO breadrcumb ?!
It can be disabled, so to use the theme's breadcrumbs, in Appearance->Customize-> Main content -> Breadcrumb -> Use Yoast SEO breadcrumbs
(which, btw, should be disabled by default...)

**Comment by emran1** [comment]
Thanks Rocco, I'll check and reply the user and post here if they reply back. Have a good day!
