### ISSUE TITLE
Feature Request: Adding social icons in top menu

### ISSUE THREAD

**Issue by emran1** [Nikeo/customizr#1766]
https://secure.helpscout.net/conversation/896596753/217936/

**Comment by ghost** [comment]
@emran1 in the demo, we display the social links in the topbar
https://demo.presscustomizr.com/

the setting is available in the customizer
![2019-07-08_12-00-04](https://user-images.githubusercontent.com/3038156/60801930-262ad700-a178-11e9-8dcc-c57c7748fa1d.jpg)

**Comment by emran1** [comment]
@Nikeo Oh I'll just rectify and answer the user. Thanks!

**Comment by ghost** [comment]
OK thanks. 
For the next support request, make sure you spent a few minutes checking the demos and explore a little bit the customizer options before replying the user and opening an issue ! 
The themes have lots of settings and it's difficult to remember them all. Thanks

**Comment by emran1** [comment]
Yes, exactly sure I'll keep in mind. Just missed that setting in the first
place. Thanks!
