### ISSUE TITLE
Tab navigation => make sure menu items are outlined on focus in major browsers

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1771]
Following new TRT requirement : https://make.wordpress.org/themes/2019/08/03/planning-for-keyboard-navigation/

https://make.wordpress.org/themes/handbook/review/accessibility/required/#keyboard-navigation

**Comment by eri-trabiccolo** [comment]
modern part at 8a52025
will do the classical part (which i've started to investigate) tomorrow.

**Comment by ghost** [comment]
I'm working on classical part now.
Thanks
