### ISSUE TITLE
Post format metaboxes not working in the block editor if the editor loads with the Status & Visibility accordion collapsed

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1773]
When the block editor loads with the accordion below collapsed
![Schermata 2019-08-29 alle 12 16 07](https://user-images.githubusercontent.com/7689242/63932121-d28d8900-ca56-11e9-9ea5-7df0a0dbfc03.png)

the post format selector is not rendered yet hence our js code that bases on its value to show/hide the metaboxes doesn't init.

When this happens the only way to make it work again is:
1) uncollapse that accordion
2) reload the page so that the block editor, which "caches the preferences", will load with that accordion uncollapsed.

A fix is on the way.

n.b. of course this affects hueman too.

**Comment by ghost** [comment]
Excellent catch thanks. Was it reported by a user or did you find it by yourself ?

**Comment by eri-trabiccolo** [comment]
By myself while testing the other hueman dev (related posts on mobile).
