### ISSUE TITLE
Accessibility - TabIndex

### ISSUE THREAD

**Issue by JTS-IL** [Nikeo/customizr#1776]
Hi!
I'm glad to see all the work to improve accessibility of my favorite theme.
I want to suggest two simple but meaningful improvements:
1. Featured pages - add "tabindex=-1" to the featured page image - there is no need for double clickable object for the same page.
2. Featured post image on post grid - same action, same reason.

**Comment by eri-trabiccolo** [comment]
Hi @JTS-IL 
thanks!
I see what you mean, it's just that in some cases - although rare, I have to admit,- the featured image link it's the only link available... E.g. a post with no title and no post metas shown.

What you propose it's definitely a solution we can explore, but we need to make it work considering the edge cases too. :D

**Comment by JTS-IL** [comment]
YEP!!!
I didn't think of this rare situation.
I will think of a more robust solution
