### ISSUE TITLE
Plugin conflict: metaslider and nextgen

### ISSUE THREAD

**Issue by emran1** [Nikeo/customizr#1780]
https://secure.helpscout.net/conversation/960813404/218681?folderId=607544

**Comment by eri-trabiccolo** [comment]
Can you confirm we're talking about the Nimble Builder conflicts with the above plugins?

**Comment by emran1** [comment]
Yes, this is nimble builder conflict with those plugins.

**Comment by eri-trabiccolo** [comment]
Thanks @emran1 !

**Comment by emran1** [comment]
No problem man!

**Comment by eri-trabiccolo** [comment]
I'm closing the issue here as we're going to track it in a different repo, thanks again!

**Comment by Nikeo** [comment]
From what I could see during my tests, when the shortcode is pasted in the editor of the shortcode Nimble module, it is not converted at first.
<img src="https://presscustomizr.com/wp-content/uploads/2019/10/2019-10-04_16-57-01.jpg" />

Then when I published and refresh the page, I can see the shortcode.
<img src="https://presscustomizr.com/wp-content/uploads/2019/10/2019-10-04_16-57-23.jpg" />

This is not ideal, but this is a work around for you.
Now we need to fix the problem of the gallery not being converted right away. I'm exploring it!
