### ISSUE TITLE
Caption text style not applied to image blocks with WP 5.3

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1789]
reported:
https://wordpress.org/support/topic/caption-font-not-being-styled-correctly/

we should copy our style for `.wp-caption-text` and apply it to `.wp-block-image figcaption`

Similar to: https://github.com/presscustomizr/hueman/issues/835

**Comment by ghost** [comment]
yep. thx for reporting.
If you can we can do a skype chat in the coming days ?
