### ISSUE TITLE
[Slider] when customizing, image layout is broken after previewer refresh

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1791]
![2019-12-16_09-11-36](https://user-images.githubusercontent.com/3038156/70890012-42af2300-1fe4-11ea-95be-4d95571d3d32.jpg)

**Comment by eri-trabiccolo** [comment]
Weird enough I cannot reproduce this... might depend on some settings configuration?!

**Comment by ghost** [comment]
ah ok, that's rather a good news. I'll see what is specific to the demo ( where I can reproduce it ).
Thanks
