### ISSUE TITLE
contact information should be on one row in topbar on mobile devices

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1805]
https://secure.helpscout.net/conversation/1083847854/220199/
Test if getting rid of the following CSS rule creates any regression 
```
@media (max-width:575px) {
.topbar-contact__info li {
    width: 100%;
}
}
```

![2020-02-16_19-25-50](https://user-images.githubusercontent.com/3038156/74610337-b65bd200-50f2-11ea-888a-6cd0e747bd8c.jpg)

**Comment by eri-trabiccolo** [comment]
This was a design choice (mostly yours 😋) and it made sense, whatever you choose there someone would complain.
We can add a new option, or we can use some css to display them on one line until they're too wide, then they'll drop automatically on a new line...
