### ISSUE TITLE
[Search form] on desktop make full screen optional and propose a smaller form by default

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1807]
like the one in Hueman.

https://secure.helpscout.net/conversation/1086969972/220226/

**Comment by ghost** [comment]
@eri-trabiccolo I know that you will ask when we discussed this internally (as I replied on the support topic ). :) 
At least I remember discussing it internally myself...

**Comment by eri-trabiccolo** [comment]
@Nikeo eheh naa I was more wondering if that should be the default or not.
You know Customizr has some distinctive traits...
But if we think that's a bad ux experience then no objections :D
