### ISSUE TITLE
Style conflict with the Ninja Forms date picker

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1810]
reported on hs: https://secure.helpscout.net/conversation/1095750606/220335

The idea would be to add another exclusion selector [here](https://github.com/presscustomizr/customizr/blob/v4.1.55/assets/front/scss/0_4_layout/_content.scss#L153):
`.pika-table`

**Comment by ghost** [comment]
OK thanks.
There should be a new release of Customizr by the end of the week.

**Comment by eri-trabiccolo** [comment]
@Nikeo bump
are we going to release a fix for this soon?

**Comment by ghost** [comment]
Hello, Rocco can we chat quickly ?

**Comment by eri-trabiccolo** [comment]
sure nico

**Comment by eri-trabiccolo** [comment]
@Nikeo 
Customizr-Pro?

**Comment by ghost** [comment]
on the way as fast as I can 🚀.
Things are getting more complicated with fuc.... coronavirus. I guess this is the same for you unfortunately.

**Comment by eri-trabiccolo** [comment]
Yes, a virtual hug!

**Comment by eri-trabiccolo** [comment]
@Nikeo how r you?
user's waiting for this fix to be released in Customizr-Pro

**Comment by ghost** [comment]
Fine thanks! and you ?
Release today!

**Comment by eri-trabiccolo** [comment]
I'm fine too thanks. :D
