### ISSUE TITLE
Turning on High Resolution (Retina) Support in Image Settings break animated Gifs on "retina" devices.

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1819]
Reported https://secure.helpscout.net/conversation/1116776932/220602/

**Comment by eri-trabiccolo** [comment]
@Nikeo 
Gifs are loaded (the customer amended his sentence), although @2x version of animated gifs "lose" the animation - which as we know also happens with the thumbnails, this is just how the thumbnails generation works.

The thing is that we should avoid creating the retina "sizes" for gifs (even if non animated gifs will work justfine) and then not process them in the retina js (this can actually be done by adding `data-no-retina` attribute to the images in php, but can be expensive, maybe would be better to "patch" the retina js to exclude gifs).

The js processing thing is important for two reasons:
1) already generated @2x must be not used
2) we should totally avoid trying to fetch something that we know it must not exist

**Comment by ghost** [comment]
ok make sense thanks. Let's do the js approach!

**Comment by ghost** [comment]
Let me know if you feel like doing it or not. Not a pb in any case!

**Comment by eri-trabiccolo** [comment]
Oh yes, no problem I can do it. :D
