### ISSUE TITLE
[gutenberg editor] grid block not working on home page ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1823]
https://secure.helpscout.net/conversation/1132162474/220817?folderId=607547

**Comment by ghost** [comment]
Hello @eri-trabiccolo do you have time to explore the problem ?
Let me know, have a good day

**Comment by eri-trabiccolo** [comment]
@Nikeo 
the user expects that the "Latest posts" Gutenberg's block produces a masonry grid, like he has in his blog page (where he has a masonry grid). That's what I got.

Plus the user did not even set the block's option to display the posts featured image - as far as I can see. If he did and the thumbs still do not show up... well I cannot reproduce it.

So this is not a theme bug, at most we can consider how to better style that block, or creating gb bocks, but sure that gb block will never look like our masonry grid :D 

The best solution we have for the moment is using Nimble.

**Comment by eri-trabiccolo** [comment]
I meant this option:
![Schermata 2020-04-09 alle 10 05 38](https://user-images.githubusercontent.com/7689242/78872578-c97f8400-7a49-11ea-8a16-042dd26ff821.png)

**Comment by ghost** [comment]
OK Thanks for the quick response and analysis.
Yes, the user might expect to see a masonry grid, that's a possibility indeed.
I'll reply to the user with your screenhot !
