### ISSUE TITLE
[Woocommerce][Gutenberg] products blocks don’t work

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1829]
https://wordpress.org/support/topic/woocommerce-products-blocks-dont-work/

> 
> Helo
> I am making a post with products, using woocommerce products block, but the add to cart button does not work, a rotating icon appears. In the browser console it indicates an error when pressing the product button:
> TypeError: 'toString' called on an object that does not implement interface HTMLAnchorElement. jquery.js:4:24838
> 
> I have added the products with shorcode [products ids = “”] and it works fine with the Customizr theme
> 
> I have tried the Storefront template using woocommerce products block, and the button works well, when I press the message “see cart” appears below the button
> 
> Greetings, Teresa
> 
> WordPress Versión 5.4
> Theme Customizr versión 4.2.4
> WooCommerce Versión 4.0.1

**Comment by eri-trabiccolo** [comment]
@Nikeo 
this should basically be the same of this: https://github.com/presscustomizr/customizr/issues/1634

so it should only affect the classic style

**Comment by ghost** [comment]
OK.
According to this reply, disabling external link option is the workaround  :
https://github.com/presscustomizr/customizr/issues/1155#issuecomment-386019669
Do you confirm ?

**Comment by eri-trabiccolo** [comment]
both the "external links" options, yeah.
I can reproduce it with classic, the 2 external links options enabled, and a products block (actually the shortcode should produce the same issue as well...).

p.s.
Chrome returns a different js error, while Firefox will return exactly the same error the user reported.
