### ISSUE TITLE
NOK => userXP ... errors or warnings!

### ISSUE THREAD

**Issue by alegomezs** [Nikeo/customizr#1867]
I have this 3 lines from the same file tc-scripts.min.js?ver=2.3.6:

```
NOK => userXP::stickifyHeader => TypeError: _.contains is not a function
tc-scripts.min.js?ver=2.3.6:1  
NOK => userXP::headerSearchToLife => TypeError: _.contains is not a function
tc-scripts.min.js?ver=2.3.6:1  
NOK => userXP::mayBePrintFrontNote => TypeError: _.contains is not a function
```

Also I have this error
`Uncaught TypeError: _.object is not a function      tc-scripts.min.js?ver=2.3.6:`

**The header isn't sticky anymore.**

**Comment by ghost** [comment]
Thanks for reporting.
It seems that your site misses the underscore library. It can have various cause.
To narrow down the cause of the problem, I recommend to follow the troubleshooting steps listed here : https://wordpress.org/support/topic/troubleshooting-tips-for-customizr-theme/
