### ISSUE TITLE
[WP Gallery Block] padding style conflict created by the theme

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1873]
https://secure.helpscout.net/conversation/1361045539/224111/
![2020-12-08_10-32-27](https://user-images.githubusercontent.com/3038156/101467158-41d47700-3942-11eb-8557-a1f678d30805.jpg)

**Comment by eri-trabiccolo** [comment]
I remember I addressed this here:
https://github.com/presscustomizr/customizr/blob/v4.3.13/assets/front/scss/0_3_components/_gallery.scss#L11

back in the past. I guess the block classes are changed in the meantime... :D

**Comment by ghost** [comment]
Yes we've worked on this compatibility already.
Yes due to an update of the block
