### ISSUE TITLE
Incredibly bad page load due to preload issue

### ISSUE THREAD

**Issue by wifiuk** [Nikeo/customizr#1879]
Consider using `<link rel=preload>` to prioritize fetching resources that are currently requested later in page load.

I'm getting up to 3s delay due to
hXXps://www.<DOMAIN-HERE>/wp-content/themes/customizr/assets/shared/fonts/customizr/customizr.woff2?128396981

What manual workaround can I do for now until this is resolved in the theme itself? Im already using a child theme for some small customisations

**Comment by ghost** [comment]
Thanks for reporting this. An issue is already opened about this problem. https://github.com/presscustomizr/customizr/issues/1835
Exploring a fix for the coming releases.

**Comment by ghost** [comment]
Before the update you'll need to add a line of code to the `<head>` tag in order to preload the font.
See : https://web.dev/codelab-preload-web-fonts/
