### ISSUE TITLE
Customizr Theme conflict with Elementor Pro (blocking comments)

### ISSUE THREAD

**Issue by mcfilms** [Nikeo/customizr#1882]
There is a conflict between Elementor Pro and the Press Customizr theme. I found that comments WOULD show in themes like Twenty Nineteen, Twenty Twenty. Twenty Twenty-One, Purse, and Freedom. But not in Customizr with the Elementor Pro plugin enabled. If I disabled PRO, they would show up.

This issue has been replicated by Elementor and Press Customizr support. I have opened an issue on the Elementor Pro tech support as well as on their github page. (https://github.com/elementor/elementor/issues/13568#issue-783640650)  I’ve looked in support threads and I cannot seem to find this exact issue.

All needed plug-ins and the theme are updated to the very latest version. 

An example page I am having this issue with is:
https://racingnelliebly.us/strange_times/top-five-secrets-victorian-era-sea-bathing/#comments
Which shows that there ARE comments, but doesn't list the 3 comments.

Nicolas (@Nikeo) suggests that something must be conflicting in this template :
https://github.com/presscustomizr/customizr/blob/dev/templates/parts/content/singular/comments/comment_list.php.

**Comment by ghost** [comment]
fixed in https://github.com/presscustomizr/customizr/commit/ed15c9c418e602930e90e652b2c7716ffd4c6c4c
