### ISSUE TITLE
remove W3C deprecated attributes for script and style tags

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1902]
https://wordpress.org/support/topic/warnig-w3c/

**Comment by eri-trabiccolo** [comment]
Well but wp does in the first place.
The theme is only reponsible for inline style/scripts added without using the wp api (meaning without using `wp_add_inline_style/script`).

**Comment by eri-trabiccolo** [comment]
Ohh but:
https://wordpress.stackexchange.com/a/353546

**Comment by ghost** [comment]
ah yes that's right. I'm going to re-check if at least we're generating a correct markup for our part...
Thanks man, good to read you!

**Comment by ghost** [comment]
Ok, that should be a simple update of this line : https://github.com/presscustomizr/customizr/blob/dev/core/class-fire-init.php#L214

**Comment by eri-trabiccolo** [comment]
yup, at least will remove those attributes from the enqueued assets using the wp api.
There might still be some styles/scripts added by the addons as..
`add_action( 'wp_footer', function() { ?> <script type="text/javascript">...</script><?php});`


so technically the theme doesn't add... it doesn't remove :D

**Comment by ghost** [comment]
yes that's right :D
