### ISSUE TITLE
entry-meta in post list and single post are not fully output

### ISSUE THREAD

**Issue by giorgioriccardi** [Nikeo/customizr#197]
Hi guys,
maybe you know this already and I just missed the tread, but the entry-meta are displayed partially.
It basically outputs:
'date' in 'category' by 'author'
I've noticed it after testing this <a href="http://presscustomizr.com/snippet/remove-post-meta-details/">snippet</a> on Customizr Pro 1.1.10

Did not try to fix it yet

**Comment by eri-trabiccolo** [comment]
Hello Giorgio,
cannot reproduce this.
Here I can output:
(text only)
25 Jun, 2015  in Uncategorized  tagged a by admin 
or
(text and buttons)
This entry was posted in Uncategorized  and tagged a  on 25 June, 2015 by admin

Did you set them in Appearance -> Customize -> Content -> Post Metas
right?

**Comment by giorgioriccardi** [comment]
Sorry guys,
I missed the part where you loose the introductory text when switching between options text and button+text
I did not follow that tread and therefore I assumed it was still behaving like in the past.
Thanks Rocco!

**Comment by eri-trabiccolo** [comment]
Dunno if there is/were a part stating that :D 
I think that is so since that new option has been added, but I'm not fully positive.
You're welcome Giorgio ;).
