### ISSUE TITLE
Add slider image size

### ISSUE THREAD

**Issue by nikolov-tmw** [Nikeo/customizr#2]
I just installed your theme and decided to try-out the slider. When I uploaded a pretty big image, I got a wide, but short image, instead of the nicely proportioned images that you can see in the demo slider. 

So I looked-up the documentation of the theme, but couldn't find the size for the images being mentioned anywhere. Then I went to the support forums on WordPress.org and I found another user asking the same question. 

I then checked the original image sizes of the demo slider images via Chrome's developer tools and I found-out that it's 1200 x 500px. 

It would be good to offer automatic photo cropping via WordPress's `add_image_size()` function. 
Since this function might crop the image in a way the user doesn't want to, it should also be mentioned what the desired size/ratio for the images is, so that the user can manually resize them if necessary.

Again - I can work on that and do a pull request if necessary.

**Comment by Nikeo** [comment]
sorry about the veeeery late reply @nikolov-tmw :|
The theme now offers this possibility in the customizer
