### ISSUE TITLE
Tutorials on how to use the Customizer?

### ISSUE THREAD

**Issue by paaljoachim** [Nikeo/customizr#281]
Hi

I am gathering resources for a longer article about the Customizer. Showing sample code along the way.
Do you have some tutorials going more into the depth of how you use the Customizer that I can learn from and perhaps steal from for my article?

I make tutorials: http://easywebdesigntutorials.com/

Thanks!

**Comment by Nikeo** [comment]
Hi Joachim,

There's a lot of materials available in the doc or in the snippets.
http://doc.presscustomizr.com/customizr/
http://presscustomizr.com/code-snippets/

Please use our contact form for future references...
http://presscustomizr.com/contact/

We use the github issues section only to report...code issues :) 

Cheers.

**Comment by paaljoachim** [comment]
Hey Nikeo

I appologize for posting the question here... (I also sent a message through Facebook... for whatever reason I did not use the contact form...)
I have found the links. My question is: will these also work within the customizer of other themes?
Can the pages be used by anyone using the Customizer feature in WordPress?

Have a great day!
