### ISSUE TITLE
Social media icons broken in german translation

### ISSUE THREAD

**Issue by gendalus** [Nikeo/customizr#3]
When using the german translation of Customizr, the social media icons are broken. According to [this forum thread](http://wordpress.org/support/topic/social-media-icon-do-not-appear) the problem seems to be the the case of the services in the german translation file.

A hot-fix is to change the service names in the translation file to lower case. But this has to be fixed in the code.

**Comment by Nikeo** [comment]
If this (very old) issue is still to be addresses, could you make a pull request ?
Thanks !
