### ISSUE TITLE
Needs better filtering code for some areas where it's replacing title=" inside hrefs

### ISSUE THREAD

**Issue by Frumph** [Nikeo/customizr#47]
Ref:
https://wordpress.org/support/topic/integrating-comic-easel-plugin?replies=19#post-6503393

**Comment by Nikeo** [comment]
Thanks for reporting this

**Comment by Frumph** [comment]
Scratch this, I think.  A loop coming from my plugin was forcing in_the_loop = true and not resetting, fixed for next update and should resolve it.

Will keep you updated; was so obscure I would have never thought of that.

**Comment by eri-trabiccolo** [comment]
This has been fixed with Customizr 3.3.0
