### ISSUE TITLE
Add option to display a featured image with Post listings

### ISSUE THREAD

**Issue by ddrscott** [Nikeo/customizr#5]
Current listings only show a title and snippet.

I personally haven't worked with PHP/WorkPress themes to know where to extract the featured image info.

Looks like https://github.com/Nikeo/customizr/blob/master/parts/class-main-content.php is trying to do something with thumbnail, so this could be a bug instead of a feature request.

http://wp-themes.com/customizr/ was used as reference to indicate the missing image.

```html
<article id="post-19" class="post-19 post type-post status-publish format-standard hentry category-uncategorized tag-boat tag-lake row-fluid">
        <div class="tc-content span12">
                    <header class="entry-header">
                <h2 class="entry-title format-icon"><a href="http://wp-themes.com/?p=19" title="Permalink to Worth A Thousand Words" rel="bookmark">Worth A Thousand Words</a> </h2>  
            <div class="entry-meta">
            </div><!-- .entry-meta -->
        </header><!-- .entry-header -->
                        <div class="entry-summary">
                            <p>Boat.</p>
                        </div><!-- .entry-summary -->
                    <footer class="entry-meta">
        </footer><!-- .entry-meta -->
        </div>
</article>
```

![screen shot 2013-08-29 at 10 19 37 am](https://f.cloud.github.com/assets/1975119/1050725/766fb218-10be-11e3-9150-9ab4ff1f6744.png)

**Comment by Nikeo** [comment]
Hi, this is now part of the core.
Thanks and sorry for the very late reply :)
