### ISSUE TITLE
Catalan translations is not fully displayed

### ISSUE THREAD

**Issue by somenxavier** [Nikeo/customizr#85]
Hi,

In [our site](http://www.cepasud.net/), we have your theme but there are parcial contents which are displayed in english, not in catalan. But the site is configured by using catalan as the language.

What can I do?
Thanks a lot,

**Comment by eri-trabiccolo** [comment]
Hi somenxavier,
well translations are mostly provided by users, and for your language there are untranslated strings.

If you want to improve your language translation you might find this useful:
http://doc.themesandco.com/customizr/translating-customizr/

And then if you want to share your translations, it will be greatly appreciated! :D

Cheers

**Comment by somenxavier** [comment]
Thanks @eri-trabiccolo  I will check it and if missing, I will submit new translations...

**Comment by somenxavier** [comment]
Even if I set language in wp-config to `ca_ES` then customizr also does not translate the sentences.

**Comment by somenxavier** [comment]
Perhaps the deprecation of `WPLANG` is related. See [this](https://wordpress.org/support/topic/broken-wplang-_e-functions-not-selecting-good-language)

**Comment by somenxavier** [comment]
Why?

**Comment by Nikeo** [comment]
well sorry I should have given a reason :)
=> Like Rocco said, translations are not fully completed right now. When a string is not translated, it is displayed in English, the default theme language.

This is a general issue.

I'm open for help if you're willing to submit a translation for the theme :)
http://doc.themesandco.com/customizr/translating-customizr/
