### ISSUE TITLE
Woocommerce Checkout page - returning customer and coupon links broken

### ISSUE THREAD

**Issue by andporter** [Nikeo/customizr#87]
You can see the issue from the customizr demo site. 

http://demo.themesandco.com/checkout/

You need to add some items to the cart and proceed to checkout, but then click the links next to returning customer or have a coupon to see the issue. They don't appear to do anything and there are not javascript errors in the web developer console.

The issue seems to be related to jQuery. If I update to the latest version of jQuery on my wordpress those links work, but then there are other issues with the customizr theme on latest jQuery such as "TypeError: undefined is not an object (evaluating 'a.browser.msie')" since .browser is not supported in jQuery anymore. 

![screen shot](https://cloud.githubusercontent.com/assets/10969796/6648663/62c8ff28-c9a2-11e4-8fab-1b5e250f3404.png)

**Comment by eri-trabiccolo** [comment]
Hi andporter,
thanks for reporting this.
Do you want to try disabling the smooth scroll? 
Apperance -> Customize -> General Settings -> Links style and effects and disabled -> Enable/disable smooth scroll on click
http://doc.themesandco.com/customizr/global-settings/#links-style-and-effects

When you upgrade jquery those links work 'cause as you said it breaks tc-scripts with "TypeError: undefined is not an object (evaluating 'a.browser.msie')" , so also the smoot on scroll js function doesn't work => no conflict with those links :D

**Comment by andporter** [comment]
Awesome thank you for replying! Disabling the smooth scroll worked.

Thank you for such an awesome theme!
