### ISSUE TITLE
Warning: sprintf(): Too few arguments in /wp-content/themes/customizr/inc/czr-front.php on line 6918

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#875]
https://wordpress.org/support/topic/warning-sprintf-too-few-arguments-chinese-only/
> Customizer 3.5.11
> 
> I’m asking here first since the error specifies a file in the theme.
> 
> Warning: sprintf(): Too few arguments in /home/huayecss/public_html/wp-content/themes/customizr/inc/czr-front.php on line 6918
> 
> Image example
> 
> This happens only in Chinese. English and Spanish do not have this error. I created a test post in Chinese (via Polylang) and the error appears. If I simply change the language setting to English, it vanishes.
> 
> It happens if the post is entirely written in English, but set to “Chinese”, so it’s not the Chinese characters causing it. It does it with any author, so it’s not that. It does it with all meta info entered (alt text, title, etc.) and with all left empty. And it happens in any screen that shows the thumbnails (categories, author, news).
> 
> As we’re a business site with visitors 24/7, I’d prefer to not go through the “turn off all plug-ins” procedure if possible.
> 
> If anyone has any ideas as to the cause, I’d appreciate hearing them.

**Comment by ghost** [comment]
@eri-trabiccolo can you have a look to it ?

**Comment by eri-trabiccolo** [comment]
That's pretty weird... the problem might be due to the translated string (chinese mo)

**Comment by eri-trabiccolo** [comment]
Yeah,
you see:
https://translate.wordpress.org/projects/wp-themes/customizr/zh-cn/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=505155&filters%5Btranslation_id%5D=45137190

The translation refers to %3$s and %4$s

I'm not sure how to solve this. That translation must be changed.
We can instruct users to either submit a correct translation, or to amend the downloaded (from translate.wordpress.org) po file and compile it (mo).

EDIT:
In our PRO langs that string is fuzzy:
https://github.com/presscustomizr/customizr/blob/v3.5.11/lang_pro/zh_CN.po#L3304

For some reason it's not on translate
