### ISSUE TITLE
Menu position for the horizontal menu ( Setting in Customizer )

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#879]
Hi,

There is a problem for menu position for the horizontal menu setting in customizer.
If you select -> Menu centered. It will revert to -> Menu on the right when you re-visit the customizer.

This is how I replicate the issue.
I have a center logo/title. Vertical main menu and secondary horizontal menu.

In Appearance -> Customize -> Header -> Design and layout
Find the setting -> Choose a layout for the header
Select -> Logo / title centered

In Appearance -> Customize -> Header -> Navigation menus
Find the setting -> Menu position (for the horizontal menu)
Select -> Menu centered.

Save changes.
Visit homepage.

Click on Customize button and navigate back to Appearance -> Customize -> Header -> Navigation menus. 
Find the setting -> Menu position (for the horizontal menu)
It's revert to -> Menu on the right instead of the selected -> Menu centered.

Please see my screen-cast.
http://screencast-o-matic.com/watch/cbhVVeXFaV

Thank you

Best Regards,
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks Denzel for reporting this!
Rocco
