### ISSUE TITLE
Validation Warning

### ISSUE THREAD

**Issue by Gecko52** [Nikeo/customizr#882]
I got the following validation warning at validator.w3.org
“Warning: The banner role is unnecessary for element header.”
I chased down the file that is loading the offending header element and it’s the header.php file in the parent Customizr theme Version: 3.5.11.

After doing some research (see the ARIA documentation https://www.w3.org/TR/html-aria/#docconformance) the header element includes a role=banner attribute by default so using the roll=”banner” ARIA within the header element throws the warning error.

**Comment by eri-trabiccolo** [comment]
I propose to remove the obsolete `role=banner` from our main header element (we don't use it in the modern style).
