### ISSUE TITLE
Are Tables responsive in Customizr v3

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#910]
> Hi, i'm using your theme from October 2016 and i noticed that the tables in articles and pages aren't responsive. I tryed differents devices with google chrome.
> 
> I don't know if the problem depends on you, but i wanna advice you about it.

	
ticket : https://secure.helpscout.net/conversation/373576798/27924/

**Comment by ghost** [comment]
not urgent. not to check or fix before next week.
Thank you

**Comment by eri-trabiccolo** [comment]
Tables are not really responsive in CSS by definition :)
We can only try to make them max width 100% if bootstrap 4 doesn't do that
by itself.

edit:
just noticed it was about v3 and not v4 :/
