### ISSUE TITLE
STYLE-RTL.CSS

### ISSUE THREAD

**Issue by JTS-IL** [Nikeo/customizr#926]
WP 4.8 (Hebrew)
Customizr 3.5.13
On the edit post screen:
"Failed to load content css: http://www.spotting.co.il/wp-content/themes/customizr/assets/back/css/editor-style-rtl.css"

There is no such file in the directory

**Comment by ghost** [comment]
Hello Yaacov, thank you for reporting the problem. Rocco and I will work on it asap.

**Comment by eri-trabiccolo** [comment]
Hi Yaacov (@JTS-IL), can you confirm this happens also with Customizr 3.5.12 and WP 4.8 ?

**Comment by JTS-IL** [comment]
I've already upgraded all my sites :-(

**Comment by eri-trabiccolo** [comment]
Ok no problems,
thanks :D

**Comment by eri-trabiccolo** [comment]
Is it blocking?
I mean you can still work with the editor and publish, right?

**Comment by JTS-IL** [comment]
Sure, can work, add and edit posts.
It's just a little annoying for those who don't understand the message :-)

**Comment by eri-trabiccolo** [comment]
Yeah, sure you're right.
Thanks again Yaacov!
We're on it! :D

**Comment by eri-trabiccolo** [comment]
fixes in v3.5.14
