### ISSUE TITLE
Missing rtl editor style css 

### ISSUE THREAD

**Issue by elico** [Nikeo/customizr#937]
When I am editing a page I am recieving the next error in a pop up:

> Failed to load content css: http://ngtech.co.il/lectures-he/wp-content/themes/customizr/assets/back/css/editor-style-rtl.css

I am using latest wordpress.

**Comment by eri-trabiccolo** [comment]
Hi @elico,
thanks for reporting this.
We're about to release a fix :D 

duplicate of #926

**Comment by eri-trabiccolo** [comment]
Hi elico,
fixed in v3.5.14

**Comment by elico** [comment]
Thanks. 
Will test today.
