### ISSUE TITLE
Allow a more big logo when the page is scroll down

### ISSUE THREAD

**Issue by PeopleInside** [Nikeo/customizr#947]
![screen](https://user-images.githubusercontent.com/5006150/27014862-72b378e6-4f01-11e7-8c3e-3481fc07a57e.png)

The logo can be better, more big, showed better and is not. I have no control in the settings for show better.
https://www.peopleinside.it/video/musicali/

**Comment by eri-trabiccolo** [comment]
Hi there,
there's an option in
Appearance -> Customize -> Header -> Design .. ->Sticky header : shrink title / logo

doesn't work?

**Comment by PeopleInside** [comment]
Found. There are an option to restrict the logo. Thanks
