### ISSUE TITLE
Save and Publish Button does not show Saved ( Customizr Theme )

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#950]
Hi,

The save and publish button in Customizr Theme does not show "Saved".
Please refer to my screen-cast
http://screencast-o-matic.com/watch/cb1IVrXPD9

Although the option values are saved, but Save and Published button does not show "Saved" state and browser prompts when you try to leave customizer.

The following is my system information
<pre># SITE_URL:                 http://localhost/customizr
# HOME_URL:                 http://localhost/customizr
# IS MULTISITE :            No

# THEME | VERSION :         customizr | v3.5.14# WP VERSION :              4.8
# PERMALINK STRUCTURE :     /%year%/%monthnum%/%day%/%postname%/

# ACTIVE PLUGINS :

PHP Version:              7.1.0
MySQL Version:            5.6.34
Web Server Info:          Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.12 PHP/7.1.0 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

WordPress Memory Limit:   40MB
PHP Memory Limit:         256M
PHP Upload Max Size:      32M
PHP Post Max Size:        32M
PHP Upload Max Filesize:  32M
PHP Time Limit:           30
PHP Max Input Vars:       1000
PHP Arg Separator:        &
PHP Allow URL File Open:  Yes
WP_DEBUG:                 Enabled

Show On Front:            posts
Page On Front:             (#0)
Page For Posts:            (#0)
</pre>

Thank you

**Comment by eri-trabiccolo** [comment]
Hi @denzelchia,
thanks for reporting this.

Any error in the js console, or in debug.log?

**Comment by denzelchia** [comment]
Hi Rocco,

I am not seeing any error in js console.

Thank you

**Comment by eri-trabiccolo** [comment]
https://wordpress.org/support/topic/save-publish-not-working-3/

@nikeo , can you reproduce it?

**Comment by JTS-IL** [comment]
Hi,
Happens to me too :-(

**Comment by eri-trabiccolo** [comment]
Hi there.
Thanks

**Comment by eri-trabiccolo** [comment]
Hi @JTS-IL ,
same to you? Meaning that the settings are actually saved even if the button stays on Save and Publish ?
Plus, no errors in the console nor in debug.log?!
What browser are you using? On which O.S.?

Thanks

**Comment by JTS-IL** [comment]
win 10. chrome.
no js errors,
changed from child to main - same behavior.

**Comment by eri-trabiccolo** [comment]
Thanks JTS,
we individuated the issue
It should be tied to #957
Thanks Denzel too!

**Comment by denzelchia** [comment]
Hi Rocco,

I had updated to Customizr Theme version 3.5.15
Works for me now. 

Save and Publish button shows "Saved" when clicked and there is no browser prompt when leaving the Customizer.

http://screencast-o-matic.com/watch/cb1oewXRTI

Thank you!

**Comment by eri-trabiccolo** [comment]
Thanks Denzel,
glad to hear this.

So it was #957
weird that it produced no error messages on your system, and no errors at all on ours.
Very subtle bug.

Thanks again to you all.

I close this then
Fixed in 0d12373

**Comment by JTS-IL** [comment]
Works fine!
