### ISSUE TITLE
Warning: Cannot modify header information - headers are already sent by (output started at .../wp-content/themes/customizr/core/czr-customize.php:666)

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#957]
Reported by email and also in a review by the same user https://wordpress.org/support/topic/ships-broken/

@eri-trabiccolo any idea ?

**Comment by eri-trabiccolo** [comment]
Yeah,
space between 
closing `<?`
and opening
`<?php`
:(

read: too many new lines at the end of czr-customizr.php

**Comment by eri-trabiccolo** [comment]
It might even be tied to #950

**Comment by ghost** [comment]
yes I've seen that but shouldn't break the theme ?

**Comment by eri-trabiccolo** [comment]
I think that is most likely what produced #950 

Weird enough git doesn't show that additional new line (it should be line 666 the number of ... you know it)

**Comment by ghost** [comment]
OK good.
yeah I know this number. It is anti trinidad stuff.
'd
'child theme safe

**Comment by eri-trabiccolo** [comment]
:D
