### ISSUE TITLE
Go Pro button not well displayed on small screens

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#968]
![2017-06-17_19-39-24](https://user-images.githubusercontent.com/3038156/27254999-c35325c0-5394-11e7-8da5-4851cc383156.jpg)

**Comment by eri-trabiccolo** [comment]
yeah and with localization can be even worse
(theme czr fmk. since it's shared)

**Comment by eri-trabiccolo** [comment]
We should handle this like WP does with the active theme + change button
