### ISSUE TITLE
 ‘>’ can break the caption of embedded images in posts ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#970]
> Not sure if it’s for my site only, but the design breaks if you include pictures with captions AND the ‘>’ (greater than) character in the body text. In my specific case, I had 10+ images in my post, all with captions, titles, and alt text. In one of my tags, I had the ‘>’ character in the heading and it broke the design of my site.

**Comment by eri-trabiccolo** [comment]
Looks like I'm not able to reproduce this.
Maybe with an use case, or a link to the user's website...

Might even be a plugin's fault.
