### ISSUE TITLE
Fatal error: Uncaught Error: Class ‘CZR__’ not found in files/themes/customizr

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#972]
> Fatal error: Uncaught Error: Class ‘CZR__’ not found in files/themes/customizr
> 
> /inc/czr-init.php:2939 Stack trace: #0 /files/themes/customizr/inc/czr-init.php(2888): CZR_init_retro_compat->czr_fn_maybe_move_old_socials_to_customizer_fmk(Array) #1 /files/themes/customizr/inc/czr-init.php(128): CZR_init_retro_compat->__construct() #2 /wp-includes/class-wp-hook.php(298): CZR___->czr_fn__(Array) #3 /wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(”, Array) #4 /wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 files/themes/customizr/inc/czr-init.php(5297): do_action(‘czr_load’) #6 files/themes/customizr/core/init-base.php(857): require_once(‘/home/gutterti/…’) #7 files/themes in files/themes/customizr/inc/czr-init.php on line 2939

**Comment by eri-trabiccolo** [comment]
maybe a search so that we're sure we have no other occurrences of CZR__ 
it must be CZR___ (3 underscores)
