### ISSUE TITLE
500 Server error after update

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#973]
https://wordpress.org/support/topic/500-server-error-after-update-2/

> 
> After upgrading to 3.5.16 my dashboard died. Everything looks just fine when visiting the website from ‘outside’, but as soon as I log in I immediately get a 500 Server Error, on both the website and the dashboard.
> Had to ftp my old version (3.4.37) back to get into dashboard again.
> 
> What weird voodoo has crept into Customizr?

**Comment by eri-trabiccolo** [comment]
We need a log.
Maybe #972 produces this.
