### ISSUE TITLE
Failed to load content css with Wordpress 4.8

### ISSUE THREAD

**Issue by mjromero** [Nikeo/customizr#984]
Since I update to WP 4.8 when I try to edit a page or create a new page I have a popup with this text "Failed to load content css:  ...wp-content/themes/customizr-child/style.css"

I have the last version of customizr free theme

This is my style.css of my customizr-child theme:

```
/*
Theme Name: Customizr child
Description: tema hijo de customizr para añadir las plantillas de páginas nuestras y otras cosas como cookies
Author: Manuel Romero
Template: customizr
*/
@import url(“../customizr/style.css”);
/* =Las modificaciones comienzan a partir de aquí*/
.uneditable-input, input[type="color"], input[type="date"], input[type="datetime-local"], input[type="datetime"], input[type="email"], input[type="month"], input[type="number"], input[type="password"], input[type="search"], input[type="tel"], input[type="text"], input[type="time"], input[type="url"], input[type="week"], select, textarea {
    border-radius: 4px;
    color: #555;
    display: inline-block;
    font-size: 14px;
    height: 40px;
    line-height: 20px;
    margin-bottom: 10px;
    margin-top: 10px;
    padding: 4px 6px;
    vertical-align: middle;
}
.wpcf7 input[type="text"] {width:250px;}
.wpcf7 textarea.wpcf7-textarea { width:250px;}
```

**Comment by eri-trabiccolo** [comment]
Hi there,
cannot reproduce this issue.
Anyway, try to clean your child-theme style.css a little bit, like:
 @import url(“../customizr/style.css”);

the line above is:
1) not needed as the Customizr theme is able to load the correct parent theme style when you're running a child-theme without the import directive
2) The double quotes around "../customizr/style.css" are not well formed. they should be " " instead they are “ ”

the 2) produces the error.

Hope this helps.

N.B.
the team handles the free theme support on 
https://wordpress.org/support/theme/customizr/

Next time you might want to open a new issue there ;)
Thanks
