### ISSUE TITLE
No thumbnail image if image is already in use

### ISSUE THREAD

**Issue by JTS-IL** [Nikeo/customizr#985]
Came across this strange behavior - if a post has only one image, and this image already is in use by an older post, it looks like the post doesn't have an image on the grid display.
Of course if I set this image as main post image, it is displayed.

Happens on both Pro and free.
Bug? Feature? Intended to be like this?

**Comment by eri-trabiccolo** [comment]
Actually this is how WordPress does.
An attachment has only one parent (you can see it displaying the media library as a list).
This theme allows to show, in the lists of posts or in the slider of posts, the first attachment image as thumb. But it must to be actually a WP attachment.
;)

Hope this helps

**Comment by JTS-IL** [comment]
It took me 2 hours to find the reason for the "imageless" post. I didn't know that it's WP-core.
Thank you for the explanation!
