### ISSUE TITLE
help placeholders blocks on front => transfer 100% to modern.

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#989]

**Comment by ghost** [comment]
- move CZR_placeholders from inc/_dev to core/_dev
- modify inc/_dev/a_init_load-and-instantiate.php to remove instantation there
- setup instantiation in core/init.php
- port the css for help notice to modern style => create a separate css file to enqueued when conditions are met : user-loggedin and option checked
- split the js => extract the help block part from the front fmk and enqueue it separately when conditions are met
- in modern, gather all display call ( hooks + callbacks ) in one file located in `core/front/utils`

**Comment by ghost** [comment]
I see many websites with an empty sidebar in single posts => http://wherecouldibenow.com/insane-error-fare-to-australia/
An informative placeholder is becoming urgent

**Comment by ghost** [comment]
### Priority placeholders to implement:
- The footer has no widgets yet
- All context => widget notes in left and / or right sidebars, if they are displayed with no widget set
- Singulars => featured image note on top of the main heading
- Singulars => lazy load notice when posts has images

### Code
The placeholders will be displayed in modern style only.

- move CZR_placeholders from inc/_dev to core/_dev
- modify inc/_dev/a_init_load-and-instantiate.php to remove instantation there
- port the css for help notice to modern style => create a separate css file to enqueued when conditions are met : user-loggedin and option checked
- split the js => extract the help block part from the front fmk and enqueue it separately when conditions are met

**Comment by ghost** [comment]
Other placehoders:
Like in hueman, when customizing, print a message indicating that the widget zone can be edited
![widget_placeholders](https://user-images.githubusercontent.com/3038156/36374848-1f35116a-156d-11e8-8772-778e1827a796.jpg)

**Comment by eri-trabiccolo** [comment]
Customizr: https://github.com/presscustomizr/customizr/pull/1474
front js: https://github.com/presscustomizr/customizr-front-js-parts/pull/36
grunt tasks: https://github.com/presscustomizr/customizr-grunt-tasks/pull/8

Considerations:
1) I use only one nonce for all the notices, no need to create N nonces for N notices.
2) js params are not localized anymore, instead they will be element attributes
3) I haven't added any menu notice: we now display an **Add menu** button in the main header so we don't need help blocks for the menus. 
4) I haven't added the slider notice: we display a button in the slider that says **Customize or remove the posts slider**, so I thought we didn't need any other help for this
5) I set the display front help block default to 0 for old modern users, explained here:
https://github.com/presscustomizr/customizr/pull/1474/commits/69d11b2bb6835994b5b1cfbcafdcff43488303d9#diff-f54424c17a661e350bba8856d2a758deR2240
6) I used the old CSS as we agreed, bearing in mind we have to change it.
7) CSS and JS files are loaded separately and not minified at the moment (I don't think we need).

for 3) and 4) I kept the "{notice}_is_on" code, might be useful if we change idea.

Let me know what you think when you can.

**Comment by ghost** [comment]
1. ok
2. better! 
3. yes
4. yes
5. I understand your choice but I think that many "old" users of the modern style should see the placeholders .  I'm thinking in particular about the empty sidebars that I keep seeing on modern style websites. If we receive a lot of bad feedbacks we'll disable it for old users as you propose.
6. yes. I'll propose something
7. yes. should be loaded separately and no need to minify

**Comment by eri-trabiccolo** [comment]
Thanks for the quick feedback,
5. I "fake revert" the latest commit then
:)
